// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/settings/v2beta/security_settings.proto

package settings

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecuritySettings struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	EmbeddedIframe      *EmbeddedIframeSettings `protobuf:"bytes,1,opt,name=embedded_iframe,json=embeddedIframe,proto3" json:"embedded_iframe,omitempty"`
	EnableImpersonation bool                    `protobuf:"varint,2,opt,name=enable_impersonation,json=enableImpersonation,proto3" json:"enable_impersonation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SecuritySettings) Reset() {
	*x = SecuritySettings{}
	mi := &file_zitadel_settings_v2beta_security_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecuritySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecuritySettings) ProtoMessage() {}

func (x *SecuritySettings) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_settings_v2beta_security_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecuritySettings.ProtoReflect.Descriptor instead.
func (*SecuritySettings) Descriptor() ([]byte, []int) {
	return file_zitadel_settings_v2beta_security_settings_proto_rawDescGZIP(), []int{0}
}

func (x *SecuritySettings) GetEmbeddedIframe() *EmbeddedIframeSettings {
	if x != nil {
		return x.EmbeddedIframe
	}
	return nil
}

func (x *SecuritySettings) GetEnableImpersonation() bool {
	if x != nil {
		return x.EnableImpersonation
	}
	return false
}

type EmbeddedIframeSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AllowedOrigins []string               `protobuf:"bytes,2,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmbeddedIframeSettings) Reset() {
	*x = EmbeddedIframeSettings{}
	mi := &file_zitadel_settings_v2beta_security_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddedIframeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddedIframeSettings) ProtoMessage() {}

func (x *EmbeddedIframeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_settings_v2beta_security_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddedIframeSettings.ProtoReflect.Descriptor instead.
func (*EmbeddedIframeSettings) Descriptor() ([]byte, []int) {
	return file_zitadel_settings_v2beta_security_settings_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddedIframeSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EmbeddedIframeSettings) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

var File_zitadel_settings_v2beta_security_settings_proto protoreflect.FileDescriptor

const file_zitadel_settings_v2beta_security_settings_proto_rawDesc = "" +
	"\n" +
	"/zitadel/settings/v2beta/security_settings.proto\x12\x17zitadel.settings.v2beta\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd4\x01\n" +
	"\x10SecuritySettings\x12X\n" +
	"\x0fembedded_iframe\x18\x01 \x01(\v2/.zitadel.settings.v2beta.EmbeddedIframeSettingsR\x0eembeddedIframe\x12f\n" +
	"\x14enable_impersonation\x18\x02 \x01(\bB3\x92A02(default language for the current contextJ\x04\"en\"R\x13enableImpersonation\"\xf6\x01\n" +
	"\x16EmbeddedIframeSettings\x12P\n" +
	"\aenabled\x18\x01 \x01(\bB6\x92A321states if iframe embedding is enabled or disabledR\aenabled\x12\x89\x01\n" +
	"\x0fallowed_origins\x18\x02 \x03(\tB`\x92A]28origins allowed loading ZITADEL in an iframe if enabled.J![\"foo.bar.com\", \"localhost:8080\"]R\x0eallowedOriginsB>Z<github.com/zitadel/zitadel/pkg/grpc/settings/v2beta;settingsb\x06proto3"

var (
	file_zitadel_settings_v2beta_security_settings_proto_rawDescOnce sync.Once
	file_zitadel_settings_v2beta_security_settings_proto_rawDescData []byte
)

func file_zitadel_settings_v2beta_security_settings_proto_rawDescGZIP() []byte {
	file_zitadel_settings_v2beta_security_settings_proto_rawDescOnce.Do(func() {
		file_zitadel_settings_v2beta_security_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_settings_v2beta_security_settings_proto_rawDesc), len(file_zitadel_settings_v2beta_security_settings_proto_rawDesc)))
	})
	return file_zitadel_settings_v2beta_security_settings_proto_rawDescData
}

var file_zitadel_settings_v2beta_security_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zitadel_settings_v2beta_security_settings_proto_goTypes = []any{
	(*SecuritySettings)(nil),       // 0: zitadel.settings.v2beta.SecuritySettings
	(*EmbeddedIframeSettings)(nil), // 1: zitadel.settings.v2beta.EmbeddedIframeSettings
}
var file_zitadel_settings_v2beta_security_settings_proto_depIdxs = []int32{
	1, // 0: zitadel.settings.v2beta.SecuritySettings.embedded_iframe:type_name -> zitadel.settings.v2beta.EmbeddedIframeSettings
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zitadel_settings_v2beta_security_settings_proto_init() }
func file_zitadel_settings_v2beta_security_settings_proto_init() {
	if File_zitadel_settings_v2beta_security_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_settings_v2beta_security_settings_proto_rawDesc), len(file_zitadel_settings_v2beta_security_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_settings_v2beta_security_settings_proto_goTypes,
		DependencyIndexes: file_zitadel_settings_v2beta_security_settings_proto_depIdxs,
		MessageInfos:      file_zitadel_settings_v2beta_security_settings_proto_msgTypes,
	}.Build()
	File_zitadel_settings_v2beta_security_settings_proto = out.File
	file_zitadel_settings_v2beta_security_settings_proto_goTypes = nil
	file_zitadel_settings_v2beta_security_settings_proto_depIdxs = nil
}
