// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/internal_permission/v2beta/internal_permission_service.proto

package internal_permission

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v2beta "github.com/zitadel/zitadel/pkg/grpc/filter/v2beta"
	_ "github.com/zitadel/zitadel/pkg/grpc/protoc/v2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAdministratorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List limitations and ordering.
	Pagination *v2beta.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	// The field the result is sorted by. The default is the creation date. Beware that if you change this, your result pagination might be inconsistent.
	SortingColumn *AdministratorFieldName `protobuf:"varint,2,opt,name=sorting_column,json=sortingColumn,proto3,enum=zitadel.internal_permission.v2beta.AdministratorFieldName,oneof" json:"sorting_column,omitempty"`
	// Filter the administrator roles to be returned.
	Filters       []*AdministratorSearchFilter `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdministratorsRequest) Reset() {
	*x = ListAdministratorsRequest{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdministratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdministratorsRequest) ProtoMessage() {}

func (x *ListAdministratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdministratorsRequest.ProtoReflect.Descriptor instead.
func (*ListAdministratorsRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAdministratorsRequest) GetPagination() *v2beta.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAdministratorsRequest) GetSortingColumn() AdministratorFieldName {
	if x != nil && x.SortingColumn != nil {
		return *x.SortingColumn
	}
	return AdministratorFieldName_ADMINISTRATOR_FIELD_NAME_UNSPECIFIED
}

func (x *ListAdministratorsRequest) GetFilters() []*AdministratorSearchFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListAdministratorsResponse struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Pagination     *v2beta.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Administrators []*Administrator           `protobuf:"bytes,2,rep,name=administrators,proto3" json:"administrators,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAdministratorsResponse) Reset() {
	*x = ListAdministratorsResponse{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdministratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdministratorsResponse) ProtoMessage() {}

func (x *ListAdministratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdministratorsResponse.ProtoReflect.Descriptor instead.
func (*ListAdministratorsResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdministratorsResponse) GetPagination() *v2beta.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAdministratorsResponse) GetAdministrators() []*Administrator {
	if x != nil {
		return x.Administrators
	}
	return nil
}

type GetAdministratorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the unique identifier of the administrator.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdministratorRequest) Reset() {
	*x = GetAdministratorRequest{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdministratorRequest) ProtoMessage() {}

func (x *GetAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdministratorRequest.ProtoReflect.Descriptor instead.
func (*GetAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdministratorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAdministratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Administrator *Administrator         `protobuf:"bytes,1,opt,name=administrator,proto3" json:"administrator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdministratorResponse) Reset() {
	*x = GetAdministratorResponse{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdministratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdministratorResponse) ProtoMessage() {}

func (x *GetAdministratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdministratorResponse.ProtoReflect.Descriptor instead.
func (*GetAdministratorResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdministratorResponse) GetAdministrator() *Administrator {
	if x != nil {
		return x.Administrator
	}
	return nil
}

type CreateAdministratorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserID is the ID of the user who should be granted the administrator role.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Resource is the type of the resource the administrator roles should be granted for.
	Resource *ResourceType `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Roles are the roles that should be granted to the user for the specified resource.
	// Note that roles are currently specific to the resource type.
	// This means that if you want to grant a user the administrator role for an organization and a project,
	// you need to create two administrator roles.
	Roles         []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdministratorRequest) Reset() {
	*x = CreateAdministratorRequest{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdministratorRequest) ProtoMessage() {}

func (x *CreateAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdministratorRequest.ProtoReflect.Descriptor instead.
func (*CreateAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdministratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAdministratorRequest) GetResource() *ResourceType {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CreateAdministratorRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ResourceType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource is the type of the resource the administrator roles should be granted for.
	//
	// Types that are valid to be assigned to Resource:
	//
	//	*ResourceType_Instance
	//	*ResourceType_OrganizationId
	//	*ResourceType_ProjectId
	//	*ResourceType_ProjectGrant_
	Resource      isResourceType_Resource `protobuf_oneof:"resource"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceType) Reset() {
	*x = ResourceType{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceType) ProtoMessage() {}

func (x *ResourceType) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceType.ProtoReflect.Descriptor instead.
func (*ResourceType) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceType) GetResource() isResourceType_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceType) GetInstance() bool {
	if x != nil {
		if x, ok := x.Resource.(*ResourceType_Instance); ok {
			return x.Instance
		}
	}
	return false
}

func (x *ResourceType) GetOrganizationId() string {
	if x != nil {
		if x, ok := x.Resource.(*ResourceType_OrganizationId); ok {
			return x.OrganizationId
		}
	}
	return ""
}

func (x *ResourceType) GetProjectId() string {
	if x != nil {
		if x, ok := x.Resource.(*ResourceType_ProjectId); ok {
			return x.ProjectId
		}
	}
	return ""
}

func (x *ResourceType) GetProjectGrant() *ResourceType_ProjectGrant {
	if x != nil {
		if x, ok := x.Resource.(*ResourceType_ProjectGrant_); ok {
			return x.ProjectGrant
		}
	}
	return nil
}

type isResourceType_Resource interface {
	isResourceType_Resource()
}

type ResourceType_Instance struct {
	// Instance is the resource type for granting administrator privileges on the instance level.
	Instance bool `protobuf:"varint,1,opt,name=instance,proto3,oneof"`
}

type ResourceType_OrganizationId struct {
	// OrganizationID is required to grant administrator privileges for a specific organization.
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3,oneof"`
}

type ResourceType_ProjectId struct {
	// ProjectID is required to grant administrator privileges for a specific project.
	ProjectId string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3,oneof"`
}

type ResourceType_ProjectGrant_ struct {
	// ProjectGrantID is required to grant administrator privileges for a specific project grant.
	ProjectGrant *ResourceType_ProjectGrant `protobuf:"bytes,4,opt,name=project_grant,json=projectGrant,proto3,oneof"`
}

func (*ResourceType_Instance) isResourceType_Resource() {}

func (*ResourceType_OrganizationId) isResourceType_Resource() {}

func (*ResourceType_ProjectId) isResourceType_Resource() {}

func (*ResourceType_ProjectGrant_) isResourceType_Resource() {}

type CreateAdministratorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CreationDate is the timestamp when the administrator role was created.
	CreationDate  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdministratorResponse) Reset() {
	*x = CreateAdministratorResponse{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdministratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdministratorResponse) ProtoMessage() {}

func (x *CreateAdministratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdministratorResponse.ProtoReflect.Descriptor instead.
func (*CreateAdministratorResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAdministratorResponse) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

type UpdateAdministratorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserID is the ID of the user who should have his administrator roles update.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Resource is the type of the resource the administrator roles should be granted for.
	Resource *ResourceType `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Roles are the roles that the user should be granted.
	// Note that any role previously granted to the user and not present in the list will be revoked.
	Roles         []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdministratorRequest) Reset() {
	*x = UpdateAdministratorRequest{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdministratorRequest) ProtoMessage() {}

func (x *UpdateAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdministratorRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAdministratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAdministratorRequest) GetResource() *ResourceType {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *UpdateAdministratorRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateAdministratorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ChangeDate is the timestamp when the administrator role was last updated.
	ChangeDate    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=change_date,json=changeDate,proto3" json:"change_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdministratorResponse) Reset() {
	*x = UpdateAdministratorResponse{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdministratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdministratorResponse) ProtoMessage() {}

func (x *UpdateAdministratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdministratorResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdministratorResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAdministratorResponse) GetChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeDate
	}
	return nil
}

type DeleteAdministratorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UserID is the ID of the user who should have his administrator roles removed.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Resource is the type of the resource the administrator roles should be removed for.
	Resource      *ResourceType `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdministratorRequest) Reset() {
	*x = DeleteAdministratorRequest{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdministratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdministratorRequest) ProtoMessage() {}

func (x *DeleteAdministratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdministratorRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdministratorRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAdministratorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteAdministratorRequest) GetResource() *ResourceType {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteAdministratorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DeletionDate is the timestamp when the administrator role was deleted.
	// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
	// In case the deletion occurred in a previous request, the deletion date might not be set.
	DeletionDate  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deletion_date,json=deletionDate,proto3" json:"deletion_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdministratorResponse) Reset() {
	*x = DeleteAdministratorResponse{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdministratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdministratorResponse) ProtoMessage() {}

func (x *DeleteAdministratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdministratorResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdministratorResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAdministratorResponse) GetDeletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionDate
	}
	return nil
}

type ResourceType_ProjectGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectID is required to grant administrator privileges for a specific project.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// OrganizationID is required to grant administrator privileges for a specific project grant.
	OrganizationId string `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceType_ProjectGrant) Reset() {
	*x = ResourceType_ProjectGrant{}
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceType_ProjectGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceType_ProjectGrant) ProtoMessage() {}

func (x *ResourceType_ProjectGrant) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceType_ProjectGrant.ProtoReflect.Descriptor instead.
func (*ResourceType_ProjectGrant) Descriptor() ([]byte, []int) {
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ResourceType_ProjectGrant) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ResourceType_ProjectGrant) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

var File_zitadel_internal_permission_v2beta_internal_permission_service_proto protoreflect.FileDescriptor

const file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDesc = "" +
	"\n" +
	"Dzitadel/internal_permission/v2beta/internal_permission_service.proto\x12\"zitadel.internal_permission.v2beta\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a+zitadel/protoc_gen_zitadel/v2/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"zitadel/filter/v2beta/filter.proto\x1a.zitadel/internal_permission/v2beta/query.proto\"\xfd\x02\n" +
	"\x19ListAdministratorsRequest\x12M\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2(.zitadel.filter.v2beta.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01\x12\x95\x01\n" +
	"\x0esorting_column\x18\x02 \x01(\x0e2:.zitadel.internal_permission.v2beta.AdministratorFieldNameB-\x92A*:(\"ADMINISTRATOR_FIELD_NAME_CREATION_DATE\"H\x01R\rsortingColumn\x88\x01\x01\x12W\n" +
	"\afilters\x18\x03 \x03(\v2=.zitadel.internal_permission.v2beta.AdministratorSearchFilterR\afiltersB\r\n" +
	"\v_paginationB\x11\n" +
	"\x0f_sorting_column\"\xc2\x01\n" +
	"\x1aListAdministratorsResponse\x12I\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2).zitadel.filter.v2beta.PaginationResponseR\n" +
	"pagination\x12Y\n" +
	"\x0eadministrators\x18\x02 \x03(\v21.zitadel.internal_permission.v2beta.AdministratorR\x0eadministrators\"5\n" +
	"\x17GetAdministratorRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x02id\"s\n" +
	"\x18GetAdministratorResponse\x12W\n" +
	"\radministrator\x18\x01 \x01(\v21.zitadel.internal_permission.v2beta.AdministratorR\radministrator\"\xb8\x01\n" +
	"\x1aCreateAdministratorRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x06userId\x12L\n" +
	"\bresource\x18\x02 \x01(\v20.zitadel.internal_permission.v2beta.ResourceTypeR\bresource\x12'\n" +
	"\x05roles\x18\x03 \x03(\tB\x11\xfaB\x0e\x92\x01\v\x18\x01\"\ar\x05\x10\x01\x18\xc8\x01R\x05roles\"\xe8\x02\n" +
	"\fResourceType\x12%\n" +
	"\binstance\x18\x01 \x01(\bB\a\xfaB\x04j\x02\b\x01H\x00R\binstance\x12)\n" +
	"\x0forganization_id\x18\x02 \x01(\tH\x00R\x0eorganizationId\x12\x1f\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tH\x00R\tprojectId\x12d\n" +
	"\rproject_grant\x18\x04 \x01(\v2=.zitadel.internal_permission.v2beta.ResourceType.ProjectGrantH\x00R\fprojectGrant\x1an\n" +
	"\fProjectGrant\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationIdJ\x04\b\x02\x10\x03R\x10project_grant_idB\x0f\n" +
	"\bresource\x12\x03\xf8B\x01\"^\n" +
	"\x1bCreateAdministratorResponse\x12?\n" +
	"\rcreation_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationDate\"\xb8\x01\n" +
	"\x1aUpdateAdministratorRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x06userId\x12L\n" +
	"\bresource\x18\x02 \x01(\v20.zitadel.internal_permission.v2beta.ResourceTypeR\bresource\x12'\n" +
	"\x05roles\x18\x03 \x03(\tB\x11\xfaB\x0e\x92\x01\v\x18\x01\"\ar\x05\x10\x01\x18\xc8\x01R\x05roles\"Z\n" +
	"\x1bUpdateAdministratorResponse\x12;\n" +
	"\vchange_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeDate\"\x8f\x01\n" +
	"\x1aDeleteAdministratorRequest\x12#\n" +
	"\auser_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x06userId\x12L\n" +
	"\bresource\x18\x02 \x01(\v20.zitadel.internal_permission.v2beta.ResourceTypeR\bresource\"^\n" +
	"\x1bDeleteAdministratorResponse\x12?\n" +
	"\rdeletion_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fdeletionDate2\xe7\t\n" +
	"\x19InternalPermissionService\x12\xaf\x02\n" +
	"\x12ListAdministrators\x12=.zitadel.internal_permission.v2beta.ListAdministratorsRequest\x1a>.zitadel.internal_permission.v2beta.ListAdministratorsResponse\"\x99\x01\x92AYJ8\n" +
	"\x03200\x121\n" +
	"/A list of all administrators matching the queryJ\x1b\n" +
	"\x03400\x12\x14\n" +
	"\x12invalid list queryX\x01\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v2beta/administrators/search\x12\xb7\x02\n" +
	"\x13CreateAdministrator\x12>.zitadel.internal_permission.v2beta.CreateAdministratorRequest\x1a?.zitadel.internal_permission.v2beta.CreateAdministratorResponse\"\x9e\x01\x92AeJ+\n" +
	"\x03200\x12$\n" +
	"\"Administrator created successfullyJ4\n" +
	"\x03409\x12-\n" +
	"+The administrator to create already exists.X\x01\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2beta/administrators\x12\xd3\x02\n" +
	"\x13UpdateAdministrator\x12>.zitadel.internal_permission.v2beta.UpdateAdministratorRequest\x1a?.zitadel.internal_permission.v2beta.UpdateAdministratorResponse\"\xba\x01\x92AwJ=\n" +
	"\x03200\x126\n" +
	"4Administrator successfully updated or left unchangedJ4\n" +
	"\x03404\x12-\n" +
	"+The administrator to update does not exist.X\x01\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02%:\x01*\" /v2beta/administrators/{user_id}\x12\x87\x02\n" +
	"\x13DeleteAdministrator\x12>.zitadel.internal_permission.v2beta.DeleteAdministratorRequest\x1a?.zitadel.internal_permission.v2beta.DeleteAdministratorResponse\"o\x92A/J+\n" +
	"\x03200\x12$\n" +
	"\"Administrator deleted successfullyX\x01\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02\"* /v2beta/administrators/{user_id}B\xc1\b\x92A\xe9\a\x12\xc7\x02\n" +
	"\x1bInternal Permission Service\x12\xa4\x01This API is intended to manage internal permissions in ZITADEL. This service is in beta state. It can AND will continue breaking until a stable version is released.\".\n" +
	"\aZITADEL\x12\x13https://zitadel.com\x1a\x0ehi@zitadel.com*G\n" +
	"\n" +
	"Apache 2.0\x129https://github.com/zitadel/zitadel/blob/main/LICENSING.md2\b2.0-beta\x1a\x0e$CUSTOM-DOMAIN\"\x01/*\x02\x02\x012\x10application/json2\x10application/grpc2\x1aapplication/grpc-web+proto:\x10application/json:\x10application/grpc:\x1aapplication/grpc-web+protoRm\n" +
	"\x03403\x12f\n" +
	"GReturned when the user does not have permission to access the resource.\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusRP\n" +
	"\x03404\x12I\n" +
	"*Returned when the resource does not exist.\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusZ\xc2\x01\n" +
	"\xbf\x01\n" +
	"\x06OAuth2\x12\xb4\x01\b\x03(\x042!$CUSTOM-DOMAIN/oauth/v2/authorize:\x1d$CUSTOM-DOMAIN/oauth/v2/tokenBl\n" +
	"\x10\n" +
	"\x06openid\x12\x06openid\n" +
	"X\n" +
	"*urn:zitadel:iam:org:project:id:zitadel:aud\x12*urn:zitadel:iam:org:project:id:zitadel:audb@\n" +
	">\n" +
	"\x06OAuth2\x124\n" +
	"\x06openid\n" +
	"*urn:zitadel:iam:org:project:id:zitadel:audr>\n" +
	"\"Detailed information about ZITADEL\x12\x18https://zitadel.com/docsZRgithub.com/zitadel/zitadel/pkg/grpc/internal_permission/v2beta;internal_permissionb\x06proto3"

var (
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescOnce sync.Once
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescData []byte
)

func file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescGZIP() []byte {
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescOnce.Do(func() {
		file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDesc), len(file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDesc)))
	})
	return file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDescData
}

var file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_zitadel_internal_permission_v2beta_internal_permission_service_proto_goTypes = []any{
	(*ListAdministratorsRequest)(nil),   // 0: zitadel.internal_permission.v2beta.ListAdministratorsRequest
	(*ListAdministratorsResponse)(nil),  // 1: zitadel.internal_permission.v2beta.ListAdministratorsResponse
	(*GetAdministratorRequest)(nil),     // 2: zitadel.internal_permission.v2beta.GetAdministratorRequest
	(*GetAdministratorResponse)(nil),    // 3: zitadel.internal_permission.v2beta.GetAdministratorResponse
	(*CreateAdministratorRequest)(nil),  // 4: zitadel.internal_permission.v2beta.CreateAdministratorRequest
	(*ResourceType)(nil),                // 5: zitadel.internal_permission.v2beta.ResourceType
	(*CreateAdministratorResponse)(nil), // 6: zitadel.internal_permission.v2beta.CreateAdministratorResponse
	(*UpdateAdministratorRequest)(nil),  // 7: zitadel.internal_permission.v2beta.UpdateAdministratorRequest
	(*UpdateAdministratorResponse)(nil), // 8: zitadel.internal_permission.v2beta.UpdateAdministratorResponse
	(*DeleteAdministratorRequest)(nil),  // 9: zitadel.internal_permission.v2beta.DeleteAdministratorRequest
	(*DeleteAdministratorResponse)(nil), // 10: zitadel.internal_permission.v2beta.DeleteAdministratorResponse
	(*ResourceType_ProjectGrant)(nil),   // 11: zitadel.internal_permission.v2beta.ResourceType.ProjectGrant
	(*v2beta.PaginationRequest)(nil),    // 12: zitadel.filter.v2beta.PaginationRequest
	(AdministratorFieldName)(0),         // 13: zitadel.internal_permission.v2beta.AdministratorFieldName
	(*AdministratorSearchFilter)(nil),   // 14: zitadel.internal_permission.v2beta.AdministratorSearchFilter
	(*v2beta.PaginationResponse)(nil),   // 15: zitadel.filter.v2beta.PaginationResponse
	(*Administrator)(nil),               // 16: zitadel.internal_permission.v2beta.Administrator
	(*timestamppb.Timestamp)(nil),       // 17: google.protobuf.Timestamp
}
var file_zitadel_internal_permission_v2beta_internal_permission_service_proto_depIdxs = []int32{
	12, // 0: zitadel.internal_permission.v2beta.ListAdministratorsRequest.pagination:type_name -> zitadel.filter.v2beta.PaginationRequest
	13, // 1: zitadel.internal_permission.v2beta.ListAdministratorsRequest.sorting_column:type_name -> zitadel.internal_permission.v2beta.AdministratorFieldName
	14, // 2: zitadel.internal_permission.v2beta.ListAdministratorsRequest.filters:type_name -> zitadel.internal_permission.v2beta.AdministratorSearchFilter
	15, // 3: zitadel.internal_permission.v2beta.ListAdministratorsResponse.pagination:type_name -> zitadel.filter.v2beta.PaginationResponse
	16, // 4: zitadel.internal_permission.v2beta.ListAdministratorsResponse.administrators:type_name -> zitadel.internal_permission.v2beta.Administrator
	16, // 5: zitadel.internal_permission.v2beta.GetAdministratorResponse.administrator:type_name -> zitadel.internal_permission.v2beta.Administrator
	5,  // 6: zitadel.internal_permission.v2beta.CreateAdministratorRequest.resource:type_name -> zitadel.internal_permission.v2beta.ResourceType
	11, // 7: zitadel.internal_permission.v2beta.ResourceType.project_grant:type_name -> zitadel.internal_permission.v2beta.ResourceType.ProjectGrant
	17, // 8: zitadel.internal_permission.v2beta.CreateAdministratorResponse.creation_date:type_name -> google.protobuf.Timestamp
	5,  // 9: zitadel.internal_permission.v2beta.UpdateAdministratorRequest.resource:type_name -> zitadel.internal_permission.v2beta.ResourceType
	17, // 10: zitadel.internal_permission.v2beta.UpdateAdministratorResponse.change_date:type_name -> google.protobuf.Timestamp
	5,  // 11: zitadel.internal_permission.v2beta.DeleteAdministratorRequest.resource:type_name -> zitadel.internal_permission.v2beta.ResourceType
	17, // 12: zitadel.internal_permission.v2beta.DeleteAdministratorResponse.deletion_date:type_name -> google.protobuf.Timestamp
	0,  // 13: zitadel.internal_permission.v2beta.InternalPermissionService.ListAdministrators:input_type -> zitadel.internal_permission.v2beta.ListAdministratorsRequest
	4,  // 14: zitadel.internal_permission.v2beta.InternalPermissionService.CreateAdministrator:input_type -> zitadel.internal_permission.v2beta.CreateAdministratorRequest
	7,  // 15: zitadel.internal_permission.v2beta.InternalPermissionService.UpdateAdministrator:input_type -> zitadel.internal_permission.v2beta.UpdateAdministratorRequest
	9,  // 16: zitadel.internal_permission.v2beta.InternalPermissionService.DeleteAdministrator:input_type -> zitadel.internal_permission.v2beta.DeleteAdministratorRequest
	1,  // 17: zitadel.internal_permission.v2beta.InternalPermissionService.ListAdministrators:output_type -> zitadel.internal_permission.v2beta.ListAdministratorsResponse
	6,  // 18: zitadel.internal_permission.v2beta.InternalPermissionService.CreateAdministrator:output_type -> zitadel.internal_permission.v2beta.CreateAdministratorResponse
	8,  // 19: zitadel.internal_permission.v2beta.InternalPermissionService.UpdateAdministrator:output_type -> zitadel.internal_permission.v2beta.UpdateAdministratorResponse
	10, // 20: zitadel.internal_permission.v2beta.InternalPermissionService.DeleteAdministrator:output_type -> zitadel.internal_permission.v2beta.DeleteAdministratorResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_zitadel_internal_permission_v2beta_internal_permission_service_proto_init() }
func file_zitadel_internal_permission_v2beta_internal_permission_service_proto_init() {
	if File_zitadel_internal_permission_v2beta_internal_permission_service_proto != nil {
		return
	}
	file_zitadel_internal_permission_v2beta_query_proto_init()
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes[5].OneofWrappers = []any{
		(*ResourceType_Instance)(nil),
		(*ResourceType_OrganizationId)(nil),
		(*ResourceType_ProjectId)(nil),
		(*ResourceType_ProjectGrant_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDesc), len(file_zitadel_internal_permission_v2beta_internal_permission_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zitadel_internal_permission_v2beta_internal_permission_service_proto_goTypes,
		DependencyIndexes: file_zitadel_internal_permission_v2beta_internal_permission_service_proto_depIdxs,
		MessageInfos:      file_zitadel_internal_permission_v2beta_internal_permission_service_proto_msgTypes,
	}.Build()
	File_zitadel_internal_permission_v2beta_internal_permission_service_proto = out.File
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_goTypes = nil
	file_zitadel_internal_permission_v2beta_internal_permission_service_proto_depIdxs = nil
}
