// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: zitadel/instance.proto

package instance

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	object "github.com/zitadel/zitadel/pkg/grpc/object"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = object.TextQueryMethod(0)
)

// Validate checks the field values on Instance with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Instance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Instance with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InstanceMultiError, or nil
// if none found.
func (m *Instance) ValidateAll() error {
	return m.validate(true)
}

func (m *Instance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InstanceValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InstanceValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InstanceValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for State

	// no validation rules for Name

	// no validation rules for Version

	for idx, item := range m.GetDomains() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InstanceValidationError{
						field:  fmt.Sprintf("Domains[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InstanceValidationError{
						field:  fmt.Sprintf("Domains[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InstanceValidationError{
					field:  fmt.Sprintf("Domains[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return InstanceMultiError(errors)
	}

	return nil
}

// InstanceMultiError is an error wrapping multiple validation errors returned
// by Instance.ValidateAll() if the designated constraints aren't met.
type InstanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InstanceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InstanceMultiError) AllErrors() []error { return m }

// InstanceValidationError is the validation error returned by
// Instance.Validate if the designated constraints aren't met.
type InstanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InstanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InstanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InstanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InstanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InstanceValidationError) ErrorName() string { return "InstanceValidationError" }

// Error satisfies the builtin error interface
func (e InstanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInstance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InstanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InstanceValidationError{}

// Validate checks the field values on InstanceDetail with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *InstanceDetail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InstanceDetail with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in InstanceDetailMultiError,
// or nil if none found.
func (m *InstanceDetail) ValidateAll() error {
	return m.validate(true)
}

func (m *InstanceDetail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InstanceDetailValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InstanceDetailValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InstanceDetailValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for State

	// no validation rules for Name

	// no validation rules for Version

	for idx, item := range m.GetDomains() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InstanceDetailValidationError{
						field:  fmt.Sprintf("Domains[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InstanceDetailValidationError{
						field:  fmt.Sprintf("Domains[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InstanceDetailValidationError{
					field:  fmt.Sprintf("Domains[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return InstanceDetailMultiError(errors)
	}

	return nil
}

// InstanceDetailMultiError is an error wrapping multiple validation errors
// returned by InstanceDetail.ValidateAll() if the designated constraints
// aren't met.
type InstanceDetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InstanceDetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InstanceDetailMultiError) AllErrors() []error { return m }

// InstanceDetailValidationError is the validation error returned by
// InstanceDetail.Validate if the designated constraints aren't met.
type InstanceDetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InstanceDetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InstanceDetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InstanceDetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InstanceDetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InstanceDetailValidationError) ErrorName() string { return "InstanceDetailValidationError" }

// Error satisfies the builtin error interface
func (e InstanceDetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInstanceDetail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InstanceDetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InstanceDetailValidationError{}

// Validate checks the field values on Query with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Query) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Query with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in QueryMultiError, or nil if none found.
func (m *Query) ValidateAll() error {
	return m.validate(true)
}

func (m *Query) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *Query_IdQuery:
		if v == nil {
			err := QueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetIdQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryValidationError{
						field:  "IdQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryValidationError{
						field:  "IdQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetIdQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryValidationError{
					field:  "IdQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Query_DomainQuery:
		if v == nil {
			err := QueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetDomainQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryValidationError{
						field:  "DomainQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryValidationError{
						field:  "DomainQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDomainQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryValidationError{
					field:  "DomainQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := QueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return QueryMultiError(errors)
	}

	return nil
}

// QueryMultiError is an error wrapping multiple validation errors returned by
// Query.ValidateAll() if the designated constraints aren't met.
type QueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryMultiError) AllErrors() []error { return m }

// QueryValidationError is the validation error returned by Query.Validate if
// the designated constraints aren't met.
type QueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryValidationError) ErrorName() string { return "QueryValidationError" }

// Error satisfies the builtin error interface
func (e QueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryValidationError{}

// Validate checks the field values on IdsQuery with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IdsQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdsQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IdsQueryMultiError, or nil
// if none found.
func (m *IdsQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *IdsQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IdsQueryMultiError(errors)
	}

	return nil
}

// IdsQueryMultiError is an error wrapping multiple validation errors returned
// by IdsQuery.ValidateAll() if the designated constraints aren't met.
type IdsQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdsQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdsQueryMultiError) AllErrors() []error { return m }

// IdsQueryValidationError is the validation error returned by
// IdsQuery.Validate if the designated constraints aren't met.
type IdsQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdsQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdsQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdsQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdsQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdsQueryValidationError) ErrorName() string { return "IdsQueryValidationError" }

// Error satisfies the builtin error interface
func (e IdsQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdsQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdsQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdsQueryValidationError{}

// Validate checks the field values on DomainsQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DomainsQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainsQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DomainsQueryMultiError, or
// nil if none found.
func (m *DomainsQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainsQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetDomains()) > 20 {
		err := DomainsQueryValidationError{
			field:  "Domains",
			reason: "value must contain no more than 20 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetDomains() {
		_, _ = idx, item

		if l := utf8.RuneCountInString(item); l < 1 || l > 100 {
			err := DomainsQueryValidationError{
				field:  fmt.Sprintf("Domains[%v]", idx),
				reason: "value length must be between 1 and 100 runes, inclusive",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return DomainsQueryMultiError(errors)
	}

	return nil
}

// DomainsQueryMultiError is an error wrapping multiple validation errors
// returned by DomainsQuery.ValidateAll() if the designated constraints aren't met.
type DomainsQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainsQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainsQueryMultiError) AllErrors() []error { return m }

// DomainsQueryValidationError is the validation error returned by
// DomainsQuery.Validate if the designated constraints aren't met.
type DomainsQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainsQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainsQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainsQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainsQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainsQueryValidationError) ErrorName() string { return "DomainsQueryValidationError" }

// Error satisfies the builtin error interface
func (e DomainsQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainsQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainsQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainsQueryValidationError{}

// Validate checks the field values on Domain with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Domain) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Domain with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DomainMultiError, or nil if none found.
func (m *Domain) ValidateAll() error {
	return m.validate(true)
}

func (m *Domain) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DomainValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DomainValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DomainValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Domain

	// no validation rules for Primary

	// no validation rules for Generated

	if len(errors) > 0 {
		return DomainMultiError(errors)
	}

	return nil
}

// DomainMultiError is an error wrapping multiple validation errors returned by
// Domain.ValidateAll() if the designated constraints aren't met.
type DomainMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainMultiError) AllErrors() []error { return m }

// DomainValidationError is the validation error returned by Domain.Validate if
// the designated constraints aren't met.
type DomainValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainValidationError) ErrorName() string { return "DomainValidationError" }

// Error satisfies the builtin error interface
func (e DomainValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomain.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainValidationError{}

// Validate checks the field values on DomainSearchQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DomainSearchQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainSearchQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DomainSearchQueryMultiError, or nil if none found.
func (m *DomainSearchQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainSearchQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *DomainSearchQuery_DomainQuery:
		if v == nil {
			err := DomainSearchQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetDomainQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DomainSearchQueryValidationError{
						field:  "DomainQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DomainSearchQueryValidationError{
						field:  "DomainQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDomainQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DomainSearchQueryValidationError{
					field:  "DomainQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *DomainSearchQuery_GeneratedQuery:
		if v == nil {
			err := DomainSearchQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetGeneratedQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DomainSearchQueryValidationError{
						field:  "GeneratedQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DomainSearchQueryValidationError{
						field:  "GeneratedQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetGeneratedQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DomainSearchQueryValidationError{
					field:  "GeneratedQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *DomainSearchQuery_PrimaryQuery:
		if v == nil {
			err := DomainSearchQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetPrimaryQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DomainSearchQueryValidationError{
						field:  "PrimaryQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DomainSearchQueryValidationError{
						field:  "PrimaryQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPrimaryQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DomainSearchQueryValidationError{
					field:  "PrimaryQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := DomainSearchQueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DomainSearchQueryMultiError(errors)
	}

	return nil
}

// DomainSearchQueryMultiError is an error wrapping multiple validation errors
// returned by DomainSearchQuery.ValidateAll() if the designated constraints
// aren't met.
type DomainSearchQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainSearchQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainSearchQueryMultiError) AllErrors() []error { return m }

// DomainSearchQueryValidationError is the validation error returned by
// DomainSearchQuery.Validate if the designated constraints aren't met.
type DomainSearchQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainSearchQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainSearchQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainSearchQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainSearchQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainSearchQueryValidationError) ErrorName() string {
	return "DomainSearchQueryValidationError"
}

// Error satisfies the builtin error interface
func (e DomainSearchQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainSearchQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainSearchQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainSearchQueryValidationError{}

// Validate checks the field values on DomainQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DomainQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DomainQueryMultiError, or
// nil if none found.
func (m *DomainQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDomain()) > 200 {
		err := DomainQueryValidationError{
			field:  "Domain",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := DomainQueryValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DomainQueryMultiError(errors)
	}

	return nil
}

// DomainQueryMultiError is an error wrapping multiple validation errors
// returned by DomainQuery.ValidateAll() if the designated constraints aren't met.
type DomainQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainQueryMultiError) AllErrors() []error { return m }

// DomainQueryValidationError is the validation error returned by
// DomainQuery.Validate if the designated constraints aren't met.
type DomainQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainQueryValidationError) ErrorName() string { return "DomainQueryValidationError" }

// Error satisfies the builtin error interface
func (e DomainQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainQueryValidationError{}

// Validate checks the field values on DomainGeneratedQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DomainGeneratedQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainGeneratedQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DomainGeneratedQueryMultiError, or nil if none found.
func (m *DomainGeneratedQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainGeneratedQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Generated

	if len(errors) > 0 {
		return DomainGeneratedQueryMultiError(errors)
	}

	return nil
}

// DomainGeneratedQueryMultiError is an error wrapping multiple validation
// errors returned by DomainGeneratedQuery.ValidateAll() if the designated
// constraints aren't met.
type DomainGeneratedQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainGeneratedQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainGeneratedQueryMultiError) AllErrors() []error { return m }

// DomainGeneratedQueryValidationError is the validation error returned by
// DomainGeneratedQuery.Validate if the designated constraints aren't met.
type DomainGeneratedQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainGeneratedQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainGeneratedQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainGeneratedQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainGeneratedQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainGeneratedQueryValidationError) ErrorName() string {
	return "DomainGeneratedQueryValidationError"
}

// Error satisfies the builtin error interface
func (e DomainGeneratedQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainGeneratedQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainGeneratedQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainGeneratedQueryValidationError{}

// Validate checks the field values on DomainPrimaryQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DomainPrimaryQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainPrimaryQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DomainPrimaryQueryMultiError, or nil if none found.
func (m *DomainPrimaryQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainPrimaryQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Primary

	if len(errors) > 0 {
		return DomainPrimaryQueryMultiError(errors)
	}

	return nil
}

// DomainPrimaryQueryMultiError is an error wrapping multiple validation errors
// returned by DomainPrimaryQuery.ValidateAll() if the designated constraints
// aren't met.
type DomainPrimaryQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainPrimaryQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainPrimaryQueryMultiError) AllErrors() []error { return m }

// DomainPrimaryQueryValidationError is the validation error returned by
// DomainPrimaryQuery.Validate if the designated constraints aren't met.
type DomainPrimaryQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainPrimaryQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainPrimaryQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainPrimaryQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainPrimaryQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainPrimaryQueryValidationError) ErrorName() string {
	return "DomainPrimaryQueryValidationError"
}

// Error satisfies the builtin error interface
func (e DomainPrimaryQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainPrimaryQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainPrimaryQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainPrimaryQueryValidationError{}

// Validate checks the field values on TrustedDomain with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TrustedDomain) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrustedDomain with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TrustedDomainMultiError, or
// nil if none found.
func (m *TrustedDomain) ValidateAll() error {
	return m.validate(true)
}

func (m *TrustedDomain) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TrustedDomainValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TrustedDomainValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TrustedDomainValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Domain

	if len(errors) > 0 {
		return TrustedDomainMultiError(errors)
	}

	return nil
}

// TrustedDomainMultiError is an error wrapping multiple validation errors
// returned by TrustedDomain.ValidateAll() if the designated constraints
// aren't met.
type TrustedDomainMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrustedDomainMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrustedDomainMultiError) AllErrors() []error { return m }

// TrustedDomainValidationError is the validation error returned by
// TrustedDomain.Validate if the designated constraints aren't met.
type TrustedDomainValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrustedDomainValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrustedDomainValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrustedDomainValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrustedDomainValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrustedDomainValidationError) ErrorName() string { return "TrustedDomainValidationError" }

// Error satisfies the builtin error interface
func (e TrustedDomainValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrustedDomain.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrustedDomainValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrustedDomainValidationError{}

// Validate checks the field values on TrustedDomainSearchQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TrustedDomainSearchQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrustedDomainSearchQuery with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TrustedDomainSearchQueryMultiError, or nil if none found.
func (m *TrustedDomainSearchQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *TrustedDomainSearchQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *TrustedDomainSearchQuery_DomainQuery:
		if v == nil {
			err := TrustedDomainSearchQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetDomainQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TrustedDomainSearchQueryValidationError{
						field:  "DomainQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TrustedDomainSearchQueryValidationError{
						field:  "DomainQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDomainQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TrustedDomainSearchQueryValidationError{
					field:  "DomainQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := TrustedDomainSearchQueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return TrustedDomainSearchQueryMultiError(errors)
	}

	return nil
}

// TrustedDomainSearchQueryMultiError is an error wrapping multiple validation
// errors returned by TrustedDomainSearchQuery.ValidateAll() if the designated
// constraints aren't met.
type TrustedDomainSearchQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrustedDomainSearchQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrustedDomainSearchQueryMultiError) AllErrors() []error { return m }

// TrustedDomainSearchQueryValidationError is the validation error returned by
// TrustedDomainSearchQuery.Validate if the designated constraints aren't met.
type TrustedDomainSearchQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrustedDomainSearchQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrustedDomainSearchQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrustedDomainSearchQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrustedDomainSearchQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrustedDomainSearchQueryValidationError) ErrorName() string {
	return "TrustedDomainSearchQueryValidationError"
}

// Error satisfies the builtin error interface
func (e TrustedDomainSearchQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrustedDomainSearchQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrustedDomainSearchQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrustedDomainSearchQueryValidationError{}
