// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: zitadel/analytics/v2beta/telemetry_service.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_ReportBaseInformation_FullMethodName = "/zitadel.analytics.v2beta.TelemetryService/ReportBaseInformation"
	TelemetryService_ReportResourceCounts_FullMethodName  = "/zitadel.analytics.v2beta.TelemetryService/ReportResourceCounts"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The TelemetryService is used to report telemetry such as usage statistics of the ZITADEL instance(s).
// back to a central storage.
// It is used to collect anonymized data about the usage of ZITADEL features, capabilities, and configurations.
// ZITADEL acts as a client of the TelemetryService.
//
// Reports are sent periodically based on the system's runtime configuration.
// The content of the reports, respectively the data collected, can be configured in the system's runtime configuration.
//
// All endpoints follow the same error and retry handling:
// In case of a failure to report the usage, ZITADEL will retry to report the usage
// based on the configured retry policy and error type:
// - Client side errors will not be retried, as they indicate a misconfiguration or an invalid request:
//   - `INVALID_ARGUMENT`: The request was malformed.
//   - `NOT_FOUND`: The TelemetryService's endpoint is likely misconfigured.
//
// - Connection / transfer errors will be retried based on the retry policy configured in the system's runtime configuration:
//   - `DEADLINE_EXCEEDED`: The request took too long to complete, it will be retried.
//   - `RESOURCE_EXHAUSTED`: The request was rejected due to resource exhaustion, it will be retried after a backoff period.
//   - `UNAVAILABLE`: The TelemetryService is currently unavailable, it will be retried after a backoff period.
//
// Server side errors will also be retried based on the information provided by the server:
//   - `FAILED_PRECONDITION`: The request failed due to a precondition, e.g. the report ID does not exists,
//     does not correspond to the same system ID or previous reporting is too old, do not retry.
//   - `INTERNAL`: An internal error occurred. Check details and logs.
type TelemetryServiceClient interface {
	// ReportBaseInformation is used to report the base information of the ZITADEL system,
	// including the version, instances, their creation date and domains.
	// The response contains a report ID to link it to the resource counts or other reports.
	// The report ID is only valid for the same system ID.
	ReportBaseInformation(ctx context.Context, in *ReportBaseInformationRequest, opts ...grpc.CallOption) (*ReportBaseInformationResponse, error)
	// ReportResourceCounts is used to report the resource counts such as amount of organizations
	// or users per organization and much more.
	// Since the resource counts can be reported in multiple batches,
	// the response contains a report ID to continue reporting.
	// The report ID is only valid for the same system ID.
	ReportResourceCounts(ctx context.Context, in *ReportResourceCountsRequest, opts ...grpc.CallOption) (*ReportResourceCountsResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) ReportBaseInformation(ctx context.Context, in *ReportBaseInformationRequest, opts ...grpc.CallOption) (*ReportBaseInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportBaseInformationResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ReportBaseInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) ReportResourceCounts(ctx context.Context, in *ReportResourceCountsRequest, opts ...grpc.CallOption) (*ReportResourceCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResourceCountsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ReportResourceCounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
//
// The TelemetryService is used to report telemetry such as usage statistics of the ZITADEL instance(s).
// back to a central storage.
// It is used to collect anonymized data about the usage of ZITADEL features, capabilities, and configurations.
// ZITADEL acts as a client of the TelemetryService.
//
// Reports are sent periodically based on the system's runtime configuration.
// The content of the reports, respectively the data collected, can be configured in the system's runtime configuration.
//
// All endpoints follow the same error and retry handling:
// In case of a failure to report the usage, ZITADEL will retry to report the usage
// based on the configured retry policy and error type:
// - Client side errors will not be retried, as they indicate a misconfiguration or an invalid request:
//   - `INVALID_ARGUMENT`: The request was malformed.
//   - `NOT_FOUND`: The TelemetryService's endpoint is likely misconfigured.
//
// - Connection / transfer errors will be retried based on the retry policy configured in the system's runtime configuration:
//   - `DEADLINE_EXCEEDED`: The request took too long to complete, it will be retried.
//   - `RESOURCE_EXHAUSTED`: The request was rejected due to resource exhaustion, it will be retried after a backoff period.
//   - `UNAVAILABLE`: The TelemetryService is currently unavailable, it will be retried after a backoff period.
//
// Server side errors will also be retried based on the information provided by the server:
//   - `FAILED_PRECONDITION`: The request failed due to a precondition, e.g. the report ID does not exists,
//     does not correspond to the same system ID or previous reporting is too old, do not retry.
//   - `INTERNAL`: An internal error occurred. Check details and logs.
type TelemetryServiceServer interface {
	// ReportBaseInformation is used to report the base information of the ZITADEL system,
	// including the version, instances, their creation date and domains.
	// The response contains a report ID to link it to the resource counts or other reports.
	// The report ID is only valid for the same system ID.
	ReportBaseInformation(context.Context, *ReportBaseInformationRequest) (*ReportBaseInformationResponse, error)
	// ReportResourceCounts is used to report the resource counts such as amount of organizations
	// or users per organization and much more.
	// Since the resource counts can be reported in multiple batches,
	// the response contains a report ID to continue reporting.
	// The report ID is only valid for the same system ID.
	ReportResourceCounts(context.Context, *ReportResourceCountsRequest) (*ReportResourceCountsResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) ReportBaseInformation(context.Context, *ReportBaseInformationRequest) (*ReportBaseInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportBaseInformation not implemented")
}
func (UnimplementedTelemetryServiceServer) ReportResourceCounts(context.Context, *ReportResourceCountsRequest) (*ReportResourceCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResourceCounts not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_ReportBaseInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportBaseInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ReportBaseInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ReportBaseInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ReportBaseInformation(ctx, req.(*ReportBaseInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_ReportResourceCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportResourceCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ReportResourceCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ReportResourceCounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ReportResourceCounts(ctx, req.(*ReportResourceCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zitadel.analytics.v2beta.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportBaseInformation",
			Handler:    _TelemetryService_ReportBaseInformation_Handler,
		},
		{
			MethodName: "ReportResourceCounts",
			Handler:    _TelemetryService_ReportResourceCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zitadel/analytics/v2beta/telemetry_service.proto",
}
