// Code generated by protoc-gen-zitadel. DO NOT EDIT.

package saml

import (
	"github.com/zitadel/zitadel/internal/api/authz"
)

var SAMLService_AuthMethods = authz.MethodMapping{

	SAMLService_GetSAMLRequest_FullMethodName: authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},

	SAMLService_CreateResponse_FullMethodName: authz.Option{
		Permission: "authenticated",
		CheckParam: "",
	},
}
