// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: zitadel/analytics/v2beta/telemetry.proto

package analytics

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on InstanceInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InstanceInformation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InstanceInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InstanceInformationMultiError, or nil if none found.
func (m *InstanceInformation) ValidateAll() error {
	return m.validate(true)
}

func (m *InstanceInformation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InstanceInformationValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InstanceInformationValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InstanceInformationValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InstanceInformationMultiError(errors)
	}

	return nil
}

// InstanceInformationMultiError is an error wrapping multiple validation
// errors returned by InstanceInformation.ValidateAll() if the designated
// constraints aren't met.
type InstanceInformationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InstanceInformationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InstanceInformationMultiError) AllErrors() []error { return m }

// InstanceInformationValidationError is the validation error returned by
// InstanceInformation.Validate if the designated constraints aren't met.
type InstanceInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InstanceInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InstanceInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InstanceInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InstanceInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InstanceInformationValidationError) ErrorName() string {
	return "InstanceInformationValidationError"
}

// Error satisfies the builtin error interface
func (e InstanceInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInstanceInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InstanceInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InstanceInformationValidationError{}

// Validate checks the field values on ResourceCount with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ResourceCount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceCount with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceCountMultiError, or
// nil if none found.
func (m *ResourceCount) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceCount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InstanceId

	// no validation rules for ParentType

	// no validation rules for ParentId

	// no validation rules for ResourceName

	// no validation rules for TableName

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceCountValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceCountValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceCountValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Amount

	if len(errors) > 0 {
		return ResourceCountMultiError(errors)
	}

	return nil
}

// ResourceCountMultiError is an error wrapping multiple validation errors
// returned by ResourceCount.ValidateAll() if the designated constraints
// aren't met.
type ResourceCountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceCountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceCountMultiError) AllErrors() []error { return m }

// ResourceCountValidationError is the validation error returned by
// ResourceCount.Validate if the designated constraints aren't met.
type ResourceCountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceCountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceCountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceCountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceCountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceCountValidationError) ErrorName() string { return "ResourceCountValidationError" }

// Error satisfies the builtin error interface
func (e ResourceCountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceCount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceCountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceCountValidationError{}
