// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/feature/v2beta/user.proto

package feature

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v2beta "github.com/zitadel/zitadel/pkg/grpc/object/v2beta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserFeatureRequest) Reset() {
	*x = SetUserFeatureRequest{}
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserFeatureRequest) ProtoMessage() {}

func (x *SetUserFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserFeatureRequest.ProtoReflect.Descriptor instead.
func (*SetUserFeatureRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_feature_v2beta_user_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserFeatureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SetUserFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *v2beta.Details        `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserFeaturesResponse) Reset() {
	*x = SetUserFeaturesResponse{}
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserFeaturesResponse) ProtoMessage() {}

func (x *SetUserFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserFeaturesResponse.ProtoReflect.Descriptor instead.
func (*SetUserFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_feature_v2beta_user_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserFeaturesResponse) GetDetails() *v2beta.Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type ResetUserFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserFeaturesRequest) Reset() {
	*x = ResetUserFeaturesRequest{}
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserFeaturesRequest) ProtoMessage() {}

func (x *ResetUserFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserFeaturesRequest.ProtoReflect.Descriptor instead.
func (*ResetUserFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_feature_v2beta_user_proto_rawDescGZIP(), []int{2}
}

func (x *ResetUserFeaturesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetUserFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *v2beta.Details        `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserFeaturesResponse) Reset() {
	*x = ResetUserFeaturesResponse{}
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserFeaturesResponse) ProtoMessage() {}

func (x *ResetUserFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserFeaturesResponse.ProtoReflect.Descriptor instead.
func (*ResetUserFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_feature_v2beta_user_proto_rawDescGZIP(), []int{3}
}

func (x *ResetUserFeaturesResponse) GetDetails() *v2beta.Details {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetUserFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Inheritance   bool                   `protobuf:"varint,2,opt,name=inheritance,proto3" json:"inheritance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeaturesRequest) Reset() {
	*x = GetUserFeaturesRequest{}
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeaturesRequest) ProtoMessage() {}

func (x *GetUserFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeaturesRequest.ProtoReflect.Descriptor instead.
func (*GetUserFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_feature_v2beta_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserFeaturesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserFeaturesRequest) GetInheritance() bool {
	if x != nil {
		return x.Inheritance
	}
	return false
}

type GetUserFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *v2beta.Details        `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFeaturesResponse) Reset() {
	*x = GetUserFeaturesResponse{}
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFeaturesResponse) ProtoMessage() {}

func (x *GetUserFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_feature_v2beta_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFeaturesResponse.ProtoReflect.Descriptor instead.
func (*GetUserFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_feature_v2beta_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserFeaturesResponse) GetDetails() *v2beta.Details {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_zitadel_feature_v2beta_user_proto protoreflect.FileDescriptor

const file_zitadel_feature_v2beta_user_proto_rawDesc = "" +
	"\n" +
	"!zitadel/feature/v2beta/user.proto\x12\x16zitadel.feature.v2beta\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\"zitadel/object/v2beta/object.proto\x1a$zitadel/feature/v2beta/feature.proto\"Z\n" +
	"\x15SetUserFeatureRequest\x12A\n" +
	"\auser_id\x18\x01 \x01(\tB(\x92A\x1bJ\x13\"69629023906488334\"x\xc8\x01\x80\x01\x01\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x06userId\"S\n" +
	"\x17SetUserFeaturesResponse\x128\n" +
	"\adetails\x18\x01 \x01(\v2\x1e.zitadel.object.v2beta.DetailsR\adetails\"]\n" +
	"\x18ResetUserFeaturesRequest\x12A\n" +
	"\auser_id\x18\x01 \x01(\tB(\x92A\x1bJ\x13\"69629023906488334\"x\xc8\x01\x80\x01\x01\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x06userId\"U\n" +
	"\x19ResetUserFeaturesResponse\x128\n" +
	"\adetails\x18\x01 \x01(\v2\x1e.zitadel.object.v2beta.DetailsR\adetails\"\xd8\x03\n" +
	"\x16GetUserFeaturesRequest\x12A\n" +
	"\auser_id\x18\x01 \x01(\tB(\x92A\x1bJ\x13\"69629023906488334\"x\xc8\x01\x80\x01\x01\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x06userId\x12\xfa\x02\n" +
	"\vinheritance\x18\x02 \x01(\bB\xd7\x02\x92A\xd3\x022\xca\x02Inherit unset features from the resource owners. This option is recursive: if the flag is set, the resource's ancestors are consulted up to system defaults. If this option is disabled and the feature is not set on the user, it will be ommitted from the response or Not Found is returned when the user has no features flags at all.J\x04trueR\vinheritance\"S\n" +
	"\x17GetUserFeaturesResponse\x128\n" +
	"\adetails\x18\x01 \x01(\v2\x1e.zitadel.object.v2beta.DetailsR\adetailsB<Z:github.com/zitadel/zitadel/pkg/grpc/feature/v2beta;featureb\x06proto3"

var (
	file_zitadel_feature_v2beta_user_proto_rawDescOnce sync.Once
	file_zitadel_feature_v2beta_user_proto_rawDescData []byte
)

func file_zitadel_feature_v2beta_user_proto_rawDescGZIP() []byte {
	file_zitadel_feature_v2beta_user_proto_rawDescOnce.Do(func() {
		file_zitadel_feature_v2beta_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_feature_v2beta_user_proto_rawDesc), len(file_zitadel_feature_v2beta_user_proto_rawDesc)))
	})
	return file_zitadel_feature_v2beta_user_proto_rawDescData
}

var file_zitadel_feature_v2beta_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zitadel_feature_v2beta_user_proto_goTypes = []any{
	(*SetUserFeatureRequest)(nil),     // 0: zitadel.feature.v2beta.SetUserFeatureRequest
	(*SetUserFeaturesResponse)(nil),   // 1: zitadel.feature.v2beta.SetUserFeaturesResponse
	(*ResetUserFeaturesRequest)(nil),  // 2: zitadel.feature.v2beta.ResetUserFeaturesRequest
	(*ResetUserFeaturesResponse)(nil), // 3: zitadel.feature.v2beta.ResetUserFeaturesResponse
	(*GetUserFeaturesRequest)(nil),    // 4: zitadel.feature.v2beta.GetUserFeaturesRequest
	(*GetUserFeaturesResponse)(nil),   // 5: zitadel.feature.v2beta.GetUserFeaturesResponse
	(*v2beta.Details)(nil),            // 6: zitadel.object.v2beta.Details
}
var file_zitadel_feature_v2beta_user_proto_depIdxs = []int32{
	6, // 0: zitadel.feature.v2beta.SetUserFeaturesResponse.details:type_name -> zitadel.object.v2beta.Details
	6, // 1: zitadel.feature.v2beta.ResetUserFeaturesResponse.details:type_name -> zitadel.object.v2beta.Details
	6, // 2: zitadel.feature.v2beta.GetUserFeaturesResponse.details:type_name -> zitadel.object.v2beta.Details
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zitadel_feature_v2beta_user_proto_init() }
func file_zitadel_feature_v2beta_user_proto_init() {
	if File_zitadel_feature_v2beta_user_proto != nil {
		return
	}
	file_zitadel_feature_v2beta_feature_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_feature_v2beta_user_proto_rawDesc), len(file_zitadel_feature_v2beta_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_feature_v2beta_user_proto_goTypes,
		DependencyIndexes: file_zitadel_feature_v2beta_user_proto_depIdxs,
		MessageInfos:      file_zitadel_feature_v2beta_user_proto_msgTypes,
	}.Build()
	File_zitadel_feature_v2beta_user_proto = out.File
	file_zitadel_feature_v2beta_user_proto_goTypes = nil
	file_zitadel_feature_v2beta_user_proto_depIdxs = nil
}
