// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/user/v2beta/password.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_Unspecified NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_Email       NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SMS         NotificationType = 2
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_Unspecified",
		1: "NOTIFICATION_TYPE_Email",
		2: "NOTIFICATION_TYPE_SMS",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_Unspecified": 0,
		"NOTIFICATION_TYPE_Email":       1,
		"NOTIFICATION_TYPE_SMS":         2,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_user_v2beta_password_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_zitadel_user_v2beta_password_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_user_v2beta_password_proto_rawDescGZIP(), []int{0}
}

type Password struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Password       string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	ChangeRequired bool                   `protobuf:"varint,2,opt,name=change_required,json=changeRequired,proto3" json:"change_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Password) Reset() {
	*x = Password{}
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2beta_password_proto_rawDescGZIP(), []int{0}
}

func (x *Password) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Password) GetChangeRequired() bool {
	if x != nil {
		return x.ChangeRequired
	}
	return false
}

type HashedPassword struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hash           string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ChangeRequired bool                   `protobuf:"varint,2,opt,name=change_required,json=changeRequired,proto3" json:"change_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HashedPassword) Reset() {
	*x = HashedPassword{}
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashedPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashedPassword) ProtoMessage() {}

func (x *HashedPassword) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashedPassword.ProtoReflect.Descriptor instead.
func (*HashedPassword) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2beta_password_proto_rawDescGZIP(), []int{1}
}

func (x *HashedPassword) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *HashedPassword) GetChangeRequired() bool {
	if x != nil {
		return x.ChangeRequired
	}
	return false
}

type SendPasswordResetLink struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NotificationType NotificationType       `protobuf:"varint,1,opt,name=notification_type,json=notificationType,proto3,enum=zitadel.user.v2beta.NotificationType" json:"notification_type,omitempty"`
	UrlTemplate      *string                `protobuf:"bytes,2,opt,name=url_template,json=urlTemplate,proto3,oneof" json:"url_template,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendPasswordResetLink) Reset() {
	*x = SendPasswordResetLink{}
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetLink) ProtoMessage() {}

func (x *SendPasswordResetLink) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetLink.ProtoReflect.Descriptor instead.
func (*SendPasswordResetLink) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2beta_password_proto_rawDescGZIP(), []int{2}
}

func (x *SendPasswordResetLink) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_NOTIFICATION_TYPE_Unspecified
}

func (x *SendPasswordResetLink) GetUrlTemplate() string {
	if x != nil && x.UrlTemplate != nil {
		return *x.UrlTemplate
	}
	return ""
}

type ReturnPasswordResetCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnPasswordResetCode) Reset() {
	*x = ReturnPasswordResetCode{}
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnPasswordResetCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnPasswordResetCode) ProtoMessage() {}

func (x *ReturnPasswordResetCode) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnPasswordResetCode.ProtoReflect.Descriptor instead.
func (*ReturnPasswordResetCode) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2beta_password_proto_rawDescGZIP(), []int{3}
}

type SetPassword struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PasswordType:
	//
	//	*SetPassword_Password
	//	*SetPassword_HashedPassword
	PasswordType isSetPassword_PasswordType `protobuf_oneof:"password_type"`
	// Types that are valid to be assigned to Verification:
	//
	//	*SetPassword_CurrentPassword
	//	*SetPassword_VerificationCode
	Verification  isSetPassword_Verification `protobuf_oneof:"verification"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPassword) Reset() {
	*x = SetPassword{}
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPassword) ProtoMessage() {}

func (x *SetPassword) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2beta_password_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPassword.ProtoReflect.Descriptor instead.
func (*SetPassword) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2beta_password_proto_rawDescGZIP(), []int{4}
}

func (x *SetPassword) GetPasswordType() isSetPassword_PasswordType {
	if x != nil {
		return x.PasswordType
	}
	return nil
}

func (x *SetPassword) GetPassword() *Password {
	if x != nil {
		if x, ok := x.PasswordType.(*SetPassword_Password); ok {
			return x.Password
		}
	}
	return nil
}

func (x *SetPassword) GetHashedPassword() *HashedPassword {
	if x != nil {
		if x, ok := x.PasswordType.(*SetPassword_HashedPassword); ok {
			return x.HashedPassword
		}
	}
	return nil
}

func (x *SetPassword) GetVerification() isSetPassword_Verification {
	if x != nil {
		return x.Verification
	}
	return nil
}

func (x *SetPassword) GetCurrentPassword() string {
	if x != nil {
		if x, ok := x.Verification.(*SetPassword_CurrentPassword); ok {
			return x.CurrentPassword
		}
	}
	return ""
}

func (x *SetPassword) GetVerificationCode() string {
	if x != nil {
		if x, ok := x.Verification.(*SetPassword_VerificationCode); ok {
			return x.VerificationCode
		}
	}
	return ""
}

type isSetPassword_PasswordType interface {
	isSetPassword_PasswordType()
}

type SetPassword_Password struct {
	Password *Password `protobuf:"bytes,1,opt,name=password,proto3,oneof"`
}

type SetPassword_HashedPassword struct {
	HashedPassword *HashedPassword `protobuf:"bytes,2,opt,name=hashed_password,json=hashedPassword,proto3,oneof"`
}

func (*SetPassword_Password) isSetPassword_PasswordType() {}

func (*SetPassword_HashedPassword) isSetPassword_PasswordType() {}

type isSetPassword_Verification interface {
	isSetPassword_Verification()
}

type SetPassword_CurrentPassword struct {
	CurrentPassword string `protobuf:"bytes,3,opt,name=current_password,json=currentPassword,proto3,oneof"`
}

type SetPassword_VerificationCode struct {
	VerificationCode string `protobuf:"bytes,4,opt,name=verification_code,json=verificationCode,proto3,oneof"`
}

func (*SetPassword_CurrentPassword) isSetPassword_Verification() {}

func (*SetPassword_VerificationCode) isSetPassword_Verification() {}

var File_zitadel_user_v2beta_password_proto protoreflect.FileDescriptor

const file_zitadel_user_v2beta_password_proto_rawDesc = "" +
	"\n" +
	"\"zitadel/user/v2beta/password.proto\x12\x13zitadel.user.v2beta\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"z\n" +
	"\bPassword\x12E\n" +
	"\bpassword\x18\x01 \x01(\tB)\x92A\x19J\x11\"Secr3tP4ssw0rd!\"x\xc8\x01\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xc8\x01R\bpassword\x12'\n" +
	"\x0fchange_required\x18\x02 \x01(\bR\x0echangeRequired\"\xa5\x02\n" +
	"\x0eHashedPassword\x12\xe9\x01\n" +
	"\x04hash\x18\x01 \x01(\tB\xd4\x01\x92A\xc3\x012{\"Encoded hash of a password in Modular Crypt Format: https://zitadel.com/docs/concepts/architecture/secrets#hashed-secrets\"J>\"$2a$12$lJ08fqVr8bFJilRVnDT9QeULI7YW.nT3iwUv6dyg0aCrfm3UY8XR2\"x\xc8\x01\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x04hash\x12'\n" +
	"\x0fchange_required\x18\x02 \x01(\bR\x0echangeRequired\"\xe5\x03\n" +
	"\x15SendPasswordResetLink\x12R\n" +
	"\x11notification_type\x18\x01 \x01(\x0e2%.zitadel.user.v2beta.NotificationTypeR\x10notificationType\x12\xe6\x02\n" +
	"\furl_template\x18\x02 \x01(\tB\xbd\x02\x92A\xaf\x022\xcb\x01\"Optionally set a url_template, which will be used in the password reset mail sent by ZITADEL to guide the user to your password change page. If no template is set, the default ZITADEL url will be used.\"JY\"https://example.com/password/changey?userID={{.UserID}}&code={{.Code}}&orgID={{.OrgID}}\"x\xc8\x01\x80\x01\x01\xfaB\ar\x05\x10\x01\x18\xc8\x01H\x00R\vurlTemplate\x88\x01\x01B\x0f\n" +
	"\r_url_template\"\x19\n" +
	"\x17ReturnPasswordResetCode\"\xa6\x03\n" +
	"\vSetPassword\x12;\n" +
	"\bpassword\x18\x01 \x01(\v2\x1d.zitadel.user.v2beta.PasswordH\x00R\bpassword\x12N\n" +
	"\x0fhashed_password\x18\x02 \x01(\v2#.zitadel.user.v2beta.HashedPasswordH\x00R\x0ehashedPassword\x12V\n" +
	"\x10current_password\x18\x03 \x01(\tB)\x92A\x19J\x11\"Secr3tP4ssw0rd!\"x\xc8\x01\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xc8\x01H\x01R\x0fcurrentPassword\x12\x90\x01\n" +
	"\x11verification_code\x18\x04 \x01(\tBa\x92AR2?\"the verification code generated during password reset request\"J\n" +
	"\"SKJd342k\"x\x14\x80\x01\x01\xe0A\x02\xfaB\x06r\x04\x10\x01\x18\x14H\x01R\x10verificationCodeB\x0f\n" +
	"\rpassword_typeB\x0e\n" +
	"\fverification*m\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_Unspecified\x10\x00\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_Email\x10\x01\x12\x19\n" +
	"\x15NOTIFICATION_TYPE_SMS\x10\x02B6Z4github.com/zitadel/zitadel/pkg/grpc/user/v2beta;userb\x06proto3"

var (
	file_zitadel_user_v2beta_password_proto_rawDescOnce sync.Once
	file_zitadel_user_v2beta_password_proto_rawDescData []byte
)

func file_zitadel_user_v2beta_password_proto_rawDescGZIP() []byte {
	file_zitadel_user_v2beta_password_proto_rawDescOnce.Do(func() {
		file_zitadel_user_v2beta_password_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_user_v2beta_password_proto_rawDesc), len(file_zitadel_user_v2beta_password_proto_rawDesc)))
	})
	return file_zitadel_user_v2beta_password_proto_rawDescData
}

var file_zitadel_user_v2beta_password_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zitadel_user_v2beta_password_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zitadel_user_v2beta_password_proto_goTypes = []any{
	(NotificationType)(0),           // 0: zitadel.user.v2beta.NotificationType
	(*Password)(nil),                // 1: zitadel.user.v2beta.Password
	(*HashedPassword)(nil),          // 2: zitadel.user.v2beta.HashedPassword
	(*SendPasswordResetLink)(nil),   // 3: zitadel.user.v2beta.SendPasswordResetLink
	(*ReturnPasswordResetCode)(nil), // 4: zitadel.user.v2beta.ReturnPasswordResetCode
	(*SetPassword)(nil),             // 5: zitadel.user.v2beta.SetPassword
}
var file_zitadel_user_v2beta_password_proto_depIdxs = []int32{
	0, // 0: zitadel.user.v2beta.SendPasswordResetLink.notification_type:type_name -> zitadel.user.v2beta.NotificationType
	1, // 1: zitadel.user.v2beta.SetPassword.password:type_name -> zitadel.user.v2beta.Password
	2, // 2: zitadel.user.v2beta.SetPassword.hashed_password:type_name -> zitadel.user.v2beta.HashedPassword
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zitadel_user_v2beta_password_proto_init() }
func file_zitadel_user_v2beta_password_proto_init() {
	if File_zitadel_user_v2beta_password_proto != nil {
		return
	}
	file_zitadel_user_v2beta_password_proto_msgTypes[2].OneofWrappers = []any{}
	file_zitadel_user_v2beta_password_proto_msgTypes[4].OneofWrappers = []any{
		(*SetPassword_Password)(nil),
		(*SetPassword_HashedPassword)(nil),
		(*SetPassword_CurrentPassword)(nil),
		(*SetPassword_VerificationCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_user_v2beta_password_proto_rawDesc), len(file_zitadel_user_v2beta_password_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_user_v2beta_password_proto_goTypes,
		DependencyIndexes: file_zitadel_user_v2beta_password_proto_depIdxs,
		EnumInfos:         file_zitadel_user_v2beta_password_proto_enumTypes,
		MessageInfos:      file_zitadel_user_v2beta_password_proto_msgTypes,
	}.Build()
	File_zitadel_user_v2beta_password_proto = out.File
	file_zitadel_user_v2beta_password_proto_goTypes = nil
	file_zitadel_user_v2beta_password_proto_depIdxs = nil
}
