// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/webkey/v2beta/key.proto

package webkey

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	// A newly created key is in the initial state and published to the public key endpoint.
	State_STATE_INITIAL State = 1
	// The active key is used to sign tokens. Only one key can be active at a time.
	State_STATE_ACTIVE State = 2
	// The inactive key is not used to sign tokens anymore, but still published to the public key endpoint.
	State_STATE_INACTIVE State = 3
	// The removed key is not used to sign tokens anymore and not published to the public key endpoint.
	State_STATE_REMOVED State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_INITIAL",
		2: "STATE_ACTIVE",
		3: "STATE_INACTIVE",
		4: "STATE_REMOVED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_INITIAL":     1,
		"STATE_ACTIVE":      2,
		"STATE_INACTIVE":    3,
		"STATE_REMOVED":     4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_webkey_v2beta_key_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_zitadel_webkey_v2beta_key_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{0}
}

type RSABits int32

const (
	RSABits_RSA_BITS_UNSPECIFIED RSABits = 0
	// 2048 bit RSA key
	RSABits_RSA_BITS_2048 RSABits = 1
	// 3072 bit RSA key
	RSABits_RSA_BITS_3072 RSABits = 2
	// 4096 bit RSA key
	RSABits_RSA_BITS_4096 RSABits = 3
)

// Enum value maps for RSABits.
var (
	RSABits_name = map[int32]string{
		0: "RSA_BITS_UNSPECIFIED",
		1: "RSA_BITS_2048",
		2: "RSA_BITS_3072",
		3: "RSA_BITS_4096",
	}
	RSABits_value = map[string]int32{
		"RSA_BITS_UNSPECIFIED": 0,
		"RSA_BITS_2048":        1,
		"RSA_BITS_3072":        2,
		"RSA_BITS_4096":        3,
	}
)

func (x RSABits) Enum() *RSABits {
	p := new(RSABits)
	*p = x
	return p
}

func (x RSABits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RSABits) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_webkey_v2beta_key_proto_enumTypes[1].Descriptor()
}

func (RSABits) Type() protoreflect.EnumType {
	return &file_zitadel_webkey_v2beta_key_proto_enumTypes[1]
}

func (x RSABits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RSABits.Descriptor instead.
func (RSABits) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{1}
}

type RSAHasher int32

const (
	RSAHasher_RSA_HASHER_UNSPECIFIED RSAHasher = 0
	// SHA256 hashing algorithm resulting in the RS256 algorithm header
	RSAHasher_RSA_HASHER_SHA256 RSAHasher = 1
	// SHA384 hashing algorithm resulting in the RS384 algorithm header
	RSAHasher_RSA_HASHER_SHA384 RSAHasher = 2
	// SHA512 hashing algorithm resulting in the RS512 algorithm header
	RSAHasher_RSA_HASHER_SHA512 RSAHasher = 3
)

// Enum value maps for RSAHasher.
var (
	RSAHasher_name = map[int32]string{
		0: "RSA_HASHER_UNSPECIFIED",
		1: "RSA_HASHER_SHA256",
		2: "RSA_HASHER_SHA384",
		3: "RSA_HASHER_SHA512",
	}
	RSAHasher_value = map[string]int32{
		"RSA_HASHER_UNSPECIFIED": 0,
		"RSA_HASHER_SHA256":      1,
		"RSA_HASHER_SHA384":      2,
		"RSA_HASHER_SHA512":      3,
	}
)

func (x RSAHasher) Enum() *RSAHasher {
	p := new(RSAHasher)
	*p = x
	return p
}

func (x RSAHasher) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RSAHasher) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_webkey_v2beta_key_proto_enumTypes[2].Descriptor()
}

func (RSAHasher) Type() protoreflect.EnumType {
	return &file_zitadel_webkey_v2beta_key_proto_enumTypes[2]
}

func (x RSAHasher) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RSAHasher.Descriptor instead.
func (RSAHasher) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{2}
}

type ECDSACurve int32

const (
	ECDSACurve_ECDSA_CURVE_UNSPECIFIED ECDSACurve = 0
	// NIST P-256 curve resulting in the ES256 algorithm header
	ECDSACurve_ECDSA_CURVE_P256 ECDSACurve = 1
	// NIST P-384 curve resulting in the ES384 algorithm header
	ECDSACurve_ECDSA_CURVE_P384 ECDSACurve = 2
	// NIST P-512 curve resulting in the ES512 algorithm header
	ECDSACurve_ECDSA_CURVE_P512 ECDSACurve = 3
)

// Enum value maps for ECDSACurve.
var (
	ECDSACurve_name = map[int32]string{
		0: "ECDSA_CURVE_UNSPECIFIED",
		1: "ECDSA_CURVE_P256",
		2: "ECDSA_CURVE_P384",
		3: "ECDSA_CURVE_P512",
	}
	ECDSACurve_value = map[string]int32{
		"ECDSA_CURVE_UNSPECIFIED": 0,
		"ECDSA_CURVE_P256":        1,
		"ECDSA_CURVE_P384":        2,
		"ECDSA_CURVE_P512":        3,
	}
)

func (x ECDSACurve) Enum() *ECDSACurve {
	p := new(ECDSACurve)
	*p = x
	return p
}

func (x ECDSACurve) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECDSACurve) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_webkey_v2beta_key_proto_enumTypes[3].Descriptor()
}

func (ECDSACurve) Type() protoreflect.EnumType {
	return &file_zitadel_webkey_v2beta_key_proto_enumTypes[3]
}

func (x ECDSACurve) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ECDSACurve.Descriptor instead.
func (ECDSACurve) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{3}
}

type WebKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the key.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The timestamp of the key creation.
	CreationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// The timestamp of the last change to the key (e.g. creation, activation, deactivation).
	ChangeDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=change_date,json=changeDate,proto3" json:"change_date,omitempty"`
	// State of the key
	State State `protobuf:"varint,4,opt,name=state,proto3,enum=zitadel.webkey.v2beta.State" json:"state,omitempty"`
	// Configured type of the key (either RSA, ECDSA or ED25519)
	//
	// Types that are valid to be assigned to Key:
	//
	//	*WebKey_Rsa
	//	*WebKey_Ecdsa
	//	*WebKey_Ed25519
	Key           isWebKey_Key `protobuf_oneof:"key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebKey) Reset() {
	*x = WebKey{}
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebKey) ProtoMessage() {}

func (x *WebKey) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebKey.ProtoReflect.Descriptor instead.
func (*WebKey) Descriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{0}
}

func (x *WebKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebKey) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *WebKey) GetChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeDate
	}
	return nil
}

func (x *WebKey) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *WebKey) GetKey() isWebKey_Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WebKey) GetRsa() *RSA {
	if x != nil {
		if x, ok := x.Key.(*WebKey_Rsa); ok {
			return x.Rsa
		}
	}
	return nil
}

func (x *WebKey) GetEcdsa() *ECDSA {
	if x != nil {
		if x, ok := x.Key.(*WebKey_Ecdsa); ok {
			return x.Ecdsa
		}
	}
	return nil
}

func (x *WebKey) GetEd25519() *ED25519 {
	if x != nil {
		if x, ok := x.Key.(*WebKey_Ed25519); ok {
			return x.Ed25519
		}
	}
	return nil
}

type isWebKey_Key interface {
	isWebKey_Key()
}

type WebKey_Rsa struct {
	Rsa *RSA `protobuf:"bytes,5,opt,name=rsa,proto3,oneof"`
}

type WebKey_Ecdsa struct {
	Ecdsa *ECDSA `protobuf:"bytes,6,opt,name=ecdsa,proto3,oneof"`
}

type WebKey_Ed25519 struct {
	Ed25519 *ED25519 `protobuf:"bytes,7,opt,name=ed25519,proto3,oneof"`
}

func (*WebKey_Rsa) isWebKey_Key() {}

func (*WebKey_Ecdsa) isWebKey_Key() {}

func (*WebKey_Ed25519) isWebKey_Key() {}

type RSA struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bit size of the RSA key. Default is 2048 bits.
	Bits RSABits `protobuf:"varint,1,opt,name=bits,proto3,enum=zitadel.webkey.v2beta.RSABits" json:"bits,omitempty"`
	// Signing algrithm used. Default is SHA256.
	Hasher        RSAHasher `protobuf:"varint,2,opt,name=hasher,proto3,enum=zitadel.webkey.v2beta.RSAHasher" json:"hasher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSA) Reset() {
	*x = RSA{}
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSA) ProtoMessage() {}

func (x *RSA) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSA.ProtoReflect.Descriptor instead.
func (*RSA) Descriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{1}
}

func (x *RSA) GetBits() RSABits {
	if x != nil {
		return x.Bits
	}
	return RSABits_RSA_BITS_UNSPECIFIED
}

func (x *RSA) GetHasher() RSAHasher {
	if x != nil {
		return x.Hasher
	}
	return RSAHasher_RSA_HASHER_UNSPECIFIED
}

type ECDSA struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Curve of the ECDSA key. Default is P-256.
	Curve         ECDSACurve `protobuf:"varint,1,opt,name=curve,proto3,enum=zitadel.webkey.v2beta.ECDSACurve" json:"curve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSA) Reset() {
	*x = ECDSA{}
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSA) ProtoMessage() {}

func (x *ECDSA) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSA.ProtoReflect.Descriptor instead.
func (*ECDSA) Descriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{2}
}

func (x *ECDSA) GetCurve() ECDSACurve {
	if x != nil {
		return x.Curve
	}
	return ECDSACurve_ECDSA_CURVE_UNSPECIFIED
}

type ED25519 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ED25519) Reset() {
	*x = ED25519{}
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ED25519) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ED25519) ProtoMessage() {}

func (x *ED25519) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_webkey_v2beta_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ED25519.ProtoReflect.Descriptor instead.
func (*ED25519) Descriptor() ([]byte, []int) {
	return file_zitadel_webkey_v2beta_key_proto_rawDescGZIP(), []int{3}
}

var File_zitadel_webkey_v2beta_key_proto protoreflect.FileDescriptor

const file_zitadel_webkey_v2beta_key_proto_rawDesc = "" +
	"\n" +
	"\x1fzitadel/webkey/v2beta/key.proto\x12\x15zitadel.webkey.v2beta\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\xcf\x03\n" +
	"\x06WebKey\x12(\n" +
	"\x02id\x18\x01 \x01(\tB\x18\x92A\x15J\x13\"69629012906488334\"R\x02id\x12`\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2024-12-18T07:50:47.492Z\"R\fcreationDate\x12\\\n" +
	"\vchange_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2025-01-23T10:34:18.051Z\"R\n" +
	"changeDate\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.zitadel.webkey.v2beta.StateR\x05state\x12.\n" +
	"\x03rsa\x18\x05 \x01(\v2\x1a.zitadel.webkey.v2beta.RSAH\x00R\x03rsa\x124\n" +
	"\x05ecdsa\x18\x06 \x01(\v2\x1c.zitadel.webkey.v2beta.ECDSAH\x00R\x05ecdsa\x12:\n" +
	"\aed25519\x18\a \x01(\v2\x1e.zitadel.webkey.v2beta.ED25519H\x00R\aed25519B\x05\n" +
	"\x03key\"\xb3\x01\n" +
	"\x03RSA\x12P\n" +
	"\x04bits\x18\x01 \x01(\x0e2\x1e.zitadel.webkey.v2beta.RSABitsB\x1c\x92A\x0f:\rRSA_BITS_2048\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04bits\x12Z\n" +
	"\x06hasher\x18\x02 \x01(\x0e2 .zitadel.webkey.v2beta.RSAHasherB \x92A\x13:\x11RSA_HASHER_SHA256\xfaB\a\x82\x01\x04\x10\x01 \x00R\x06hasher\"a\n" +
	"\x05ECDSA\x12X\n" +
	"\x05curve\x18\x01 \x01(\x0e2!.zitadel.webkey.v2beta.ECDSACurveB\x1f\x92A\x12:\x10ECDSA_CURVE_P256\xfaB\a\x82\x01\x04\x10\x01 \x00R\x05curve\"\t\n" +
	"\aED25519*j\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_INITIAL\x10\x01\x12\x10\n" +
	"\fSTATE_ACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATE_INACTIVE\x10\x03\x12\x11\n" +
	"\rSTATE_REMOVED\x10\x04*\\\n" +
	"\aRSABits\x12\x18\n" +
	"\x14RSA_BITS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rRSA_BITS_2048\x10\x01\x12\x11\n" +
	"\rRSA_BITS_3072\x10\x02\x12\x11\n" +
	"\rRSA_BITS_4096\x10\x03*l\n" +
	"\tRSAHasher\x12\x1a\n" +
	"\x16RSA_HASHER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RSA_HASHER_SHA256\x10\x01\x12\x15\n" +
	"\x11RSA_HASHER_SHA384\x10\x02\x12\x15\n" +
	"\x11RSA_HASHER_SHA512\x10\x03*k\n" +
	"\n" +
	"ECDSACurve\x12\x1b\n" +
	"\x17ECDSA_CURVE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ECDSA_CURVE_P256\x10\x01\x12\x14\n" +
	"\x10ECDSA_CURVE_P384\x10\x02\x12\x14\n" +
	"\x10ECDSA_CURVE_P512\x10\x03B:Z8github.com/zitadel/zitadel/pkg/grpc/webkey/v2beta;webkeyb\x06proto3"

var (
	file_zitadel_webkey_v2beta_key_proto_rawDescOnce sync.Once
	file_zitadel_webkey_v2beta_key_proto_rawDescData []byte
)

func file_zitadel_webkey_v2beta_key_proto_rawDescGZIP() []byte {
	file_zitadel_webkey_v2beta_key_proto_rawDescOnce.Do(func() {
		file_zitadel_webkey_v2beta_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_webkey_v2beta_key_proto_rawDesc), len(file_zitadel_webkey_v2beta_key_proto_rawDesc)))
	})
	return file_zitadel_webkey_v2beta_key_proto_rawDescData
}

var file_zitadel_webkey_v2beta_key_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_zitadel_webkey_v2beta_key_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_zitadel_webkey_v2beta_key_proto_goTypes = []any{
	(State)(0),                    // 0: zitadel.webkey.v2beta.State
	(RSABits)(0),                  // 1: zitadel.webkey.v2beta.RSABits
	(RSAHasher)(0),                // 2: zitadel.webkey.v2beta.RSAHasher
	(ECDSACurve)(0),               // 3: zitadel.webkey.v2beta.ECDSACurve
	(*WebKey)(nil),                // 4: zitadel.webkey.v2beta.WebKey
	(*RSA)(nil),                   // 5: zitadel.webkey.v2beta.RSA
	(*ECDSA)(nil),                 // 6: zitadel.webkey.v2beta.ECDSA
	(*ED25519)(nil),               // 7: zitadel.webkey.v2beta.ED25519
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_zitadel_webkey_v2beta_key_proto_depIdxs = []int32{
	8, // 0: zitadel.webkey.v2beta.WebKey.creation_date:type_name -> google.protobuf.Timestamp
	8, // 1: zitadel.webkey.v2beta.WebKey.change_date:type_name -> google.protobuf.Timestamp
	0, // 2: zitadel.webkey.v2beta.WebKey.state:type_name -> zitadel.webkey.v2beta.State
	5, // 3: zitadel.webkey.v2beta.WebKey.rsa:type_name -> zitadel.webkey.v2beta.RSA
	6, // 4: zitadel.webkey.v2beta.WebKey.ecdsa:type_name -> zitadel.webkey.v2beta.ECDSA
	7, // 5: zitadel.webkey.v2beta.WebKey.ed25519:type_name -> zitadel.webkey.v2beta.ED25519
	1, // 6: zitadel.webkey.v2beta.RSA.bits:type_name -> zitadel.webkey.v2beta.RSABits
	2, // 7: zitadel.webkey.v2beta.RSA.hasher:type_name -> zitadel.webkey.v2beta.RSAHasher
	3, // 8: zitadel.webkey.v2beta.ECDSA.curve:type_name -> zitadel.webkey.v2beta.ECDSACurve
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_zitadel_webkey_v2beta_key_proto_init() }
func file_zitadel_webkey_v2beta_key_proto_init() {
	if File_zitadel_webkey_v2beta_key_proto != nil {
		return
	}
	file_zitadel_webkey_v2beta_key_proto_msgTypes[0].OneofWrappers = []any{
		(*WebKey_Rsa)(nil),
		(*WebKey_Ecdsa)(nil),
		(*WebKey_Ed25519)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_webkey_v2beta_key_proto_rawDesc), len(file_zitadel_webkey_v2beta_key_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_webkey_v2beta_key_proto_goTypes,
		DependencyIndexes: file_zitadel_webkey_v2beta_key_proto_depIdxs,
		EnumInfos:         file_zitadel_webkey_v2beta_key_proto_enumTypes,
		MessageInfos:      file_zitadel_webkey_v2beta_key_proto_msgTypes,
	}.Build()
	File_zitadel_webkey_v2beta_key_proto = out.File
	file_zitadel_webkey_v2beta_key_proto_goTypes = nil
	file_zitadel_webkey_v2beta_key_proto_depIdxs = nil
}
