// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/idp/v2/idp_service.proto

package idp

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/zitadel/zitadel/pkg/grpc/object/v2"
	_ "github.com/zitadel/zitadel/pkg/grpc/protoc/v2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIDPByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDPByIDRequest) Reset() {
	*x = GetIDPByIDRequest{}
	mi := &file_zitadel_idp_v2_idp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDPByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDPByIDRequest) ProtoMessage() {}

func (x *GetIDPByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_idp_v2_idp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDPByIDRequest.ProtoReflect.Descriptor instead.
func (*GetIDPByIDRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_idp_v2_idp_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetIDPByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIDPByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idp           *IDP                   `protobuf:"bytes,1,opt,name=idp,proto3" json:"idp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIDPByIDResponse) Reset() {
	*x = GetIDPByIDResponse{}
	mi := &file_zitadel_idp_v2_idp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIDPByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIDPByIDResponse) ProtoMessage() {}

func (x *GetIDPByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_idp_v2_idp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIDPByIDResponse.ProtoReflect.Descriptor instead.
func (*GetIDPByIDResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_idp_v2_idp_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetIDPByIDResponse) GetIdp() *IDP {
	if x != nil {
		return x.Idp
	}
	return nil
}

var File_zitadel_idp_v2_idp_service_proto protoreflect.FileDescriptor

const file_zitadel_idp_v2_idp_service_proto_rawDesc = "" +
	"\n" +
	" zitadel/idp/v2/idp_service.proto\x12\x0ezitadel.idp.v2\x1a+zitadel/protoc_gen_zitadel/v2/options.proto\x1a\x1ezitadel/object/v2/object.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a\x18zitadel/idp/v2/idp.proto\"/\n" +
	"\x11GetIDPByIDRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x02id\";\n" +
	"\x12GetIDPByIDResponse\x12%\n" +
	"\x03idp\x18\x01 \x01(\v2\x13.zitadel.idp.v2.IDPR\x03idp2\xab\x01\n" +
	"\x17IdentityProviderService\x12\x8f\x01\n" +
	"\n" +
	"GetIDPByID\x12!.zitadel.idp.v2.GetIDPByIDRequest\x1a\".zitadel.idp.v2.GetIDPByIDResponse\":\x92A\rJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02\x0f\x12\r/v2/idps/{id}B\xc0\a\x92A\x8c\a\x12\xea\x01\n" +
	"\x19Identity Provider Service\x12OThis API is intended to manage identity providers (IdPs) in a ZITADEL instance.\".\n" +
	"\aZITADEL\x12\x13https://zitadel.com\x1a\x0ehi@zitadel.com*G\n" +
	"\n" +
	"Apache 2.0\x129https://github.com/zitadel/zitadel/blob/main/LICENSING.md2\x032.0\x1a\x0e$CUSTOM-DOMAIN\"\x01/*\x02\x02\x012\x10application/json2\x10application/grpc2\x1aapplication/grpc-web+proto:\x10application/json:\x10application/grpc:\x1aapplication/grpc-web+protoRm\n" +
	"\x03403\x12f\n" +
	"GReturned when the user does not have permission to access the resource.\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusRP\n" +
	"\x03404\x12I\n" +
	"*Returned when the resource does not exist.\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusZ\xc2\x01\n" +
	"\xbf\x01\n" +
	"\x06OAuth2\x12\xb4\x01\b\x03(\x042!$CUSTOM-DOMAIN/oauth/v2/authorize:\x1d$CUSTOM-DOMAIN/oauth/v2/tokenBl\n" +
	"\x10\n" +
	"\x06openid\x12\x06openid\n" +
	"X\n" +
	"*urn:zitadel:iam:org:project:id:zitadel:aud\x12*urn:zitadel:iam:org:project:id:zitadel:audb@\n" +
	">\n" +
	"\x06OAuth2\x124\n" +
	"\x06openid\n" +
	"*urn:zitadel:iam:org:project:id:zitadel:audr>\n" +
	"\"Detailed information about ZITADEL\x12\x18https://zitadel.com/docsZ.github.com/zitadel/zitadel/pkg/grpc/idp/v2;idpb\x06proto3"

var (
	file_zitadel_idp_v2_idp_service_proto_rawDescOnce sync.Once
	file_zitadel_idp_v2_idp_service_proto_rawDescData []byte
)

func file_zitadel_idp_v2_idp_service_proto_rawDescGZIP() []byte {
	file_zitadel_idp_v2_idp_service_proto_rawDescOnce.Do(func() {
		file_zitadel_idp_v2_idp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_idp_v2_idp_service_proto_rawDesc), len(file_zitadel_idp_v2_idp_service_proto_rawDesc)))
	})
	return file_zitadel_idp_v2_idp_service_proto_rawDescData
}

var file_zitadel_idp_v2_idp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zitadel_idp_v2_idp_service_proto_goTypes = []any{
	(*GetIDPByIDRequest)(nil),  // 0: zitadel.idp.v2.GetIDPByIDRequest
	(*GetIDPByIDResponse)(nil), // 1: zitadel.idp.v2.GetIDPByIDResponse
	(*IDP)(nil),                // 2: zitadel.idp.v2.IDP
}
var file_zitadel_idp_v2_idp_service_proto_depIdxs = []int32{
	2, // 0: zitadel.idp.v2.GetIDPByIDResponse.idp:type_name -> zitadel.idp.v2.IDP
	0, // 1: zitadel.idp.v2.IdentityProviderService.GetIDPByID:input_type -> zitadel.idp.v2.GetIDPByIDRequest
	1, // 2: zitadel.idp.v2.IdentityProviderService.GetIDPByID:output_type -> zitadel.idp.v2.GetIDPByIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zitadel_idp_v2_idp_service_proto_init() }
func file_zitadel_idp_v2_idp_service_proto_init() {
	if File_zitadel_idp_v2_idp_service_proto != nil {
		return
	}
	file_zitadel_idp_v2_idp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_idp_v2_idp_service_proto_rawDesc), len(file_zitadel_idp_v2_idp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zitadel_idp_v2_idp_service_proto_goTypes,
		DependencyIndexes: file_zitadel_idp_v2_idp_service_proto_depIdxs,
		MessageInfos:      file_zitadel_idp_v2_idp_service_proto_msgTypes,
	}.Build()
	File_zitadel_idp_v2_idp_service_proto = out.File
	file_zitadel_idp_v2_idp_service_proto_goTypes = nil
	file_zitadel_idp_v2_idp_service_proto_depIdxs = nil
}
