// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: zitadel/object/v2beta/object.proto

package object

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Organisation with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Organisation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Organisation with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrganisationMultiError, or
// nil if none found.
func (m *Organisation) ValidateAll() error {
	return m.validate(true)
}

func (m *Organisation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Org.(type) {
	case *Organisation_OrgId:
		if v == nil {
			err := OrganisationValidationError{
				field:  "Org",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for OrgId
	case *Organisation_OrgDomain:
		if v == nil {
			err := OrganisationValidationError{
				field:  "Org",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for OrgDomain
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return OrganisationMultiError(errors)
	}

	return nil
}

// OrganisationMultiError is an error wrapping multiple validation errors
// returned by Organisation.ValidateAll() if the designated constraints aren't met.
type OrganisationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganisationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganisationMultiError) AllErrors() []error { return m }

// OrganisationValidationError is the validation error returned by
// Organisation.Validate if the designated constraints aren't met.
type OrganisationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganisationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganisationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganisationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganisationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganisationValidationError) ErrorName() string { return "OrganisationValidationError" }

// Error satisfies the builtin error interface
func (e OrganisationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganisation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganisationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganisationValidationError{}

// Validate checks the field values on Organization with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Organization) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Organization with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrganizationMultiError, or
// nil if none found.
func (m *Organization) ValidateAll() error {
	return m.validate(true)
}

func (m *Organization) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Org.(type) {
	case *Organization_OrgId:
		if v == nil {
			err := OrganizationValidationError{
				field:  "Org",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for OrgId
	case *Organization_OrgDomain:
		if v == nil {
			err := OrganizationValidationError{
				field:  "Org",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for OrgDomain
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return OrganizationMultiError(errors)
	}

	return nil
}

// OrganizationMultiError is an error wrapping multiple validation errors
// returned by Organization.ValidateAll() if the designated constraints aren't met.
type OrganizationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationMultiError) AllErrors() []error { return m }

// OrganizationValidationError is the validation error returned by
// Organization.Validate if the designated constraints aren't met.
type OrganizationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationValidationError) ErrorName() string { return "OrganizationValidationError" }

// Error satisfies the builtin error interface
func (e OrganizationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganization.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationValidationError{}

// Validate checks the field values on RequestContext with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RequestContext) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestContext with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RequestContextMultiError,
// or nil if none found.
func (m *RequestContext) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestContext) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.ResourceOwner.(type) {
	case *RequestContext_OrgId:
		if v == nil {
			err := RequestContextValidationError{
				field:  "ResourceOwner",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for OrgId
	case *RequestContext_Instance:
		if v == nil {
			err := RequestContextValidationError{
				field:  "ResourceOwner",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if m.GetInstance() != true {
			err := RequestContextValidationError{
				field:  "Instance",
				reason: "value must equal true",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return RequestContextMultiError(errors)
	}

	return nil
}

// RequestContextMultiError is an error wrapping multiple validation errors
// returned by RequestContext.ValidateAll() if the designated constraints
// aren't met.
type RequestContextMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestContextMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestContextMultiError) AllErrors() []error { return m }

// RequestContextValidationError is the validation error returned by
// RequestContext.Validate if the designated constraints aren't met.
type RequestContextValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestContextValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestContextValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestContextValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestContextValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestContextValidationError) ErrorName() string { return "RequestContextValidationError" }

// Error satisfies the builtin error interface
func (e RequestContextValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestContext.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestContextValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestContextValidationError{}

// Validate checks the field values on ListQuery with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListQueryMultiError, or nil
// if none found.
func (m *ListQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *ListQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Offset

	// no validation rules for Limit

	// no validation rules for Asc

	if len(errors) > 0 {
		return ListQueryMultiError(errors)
	}

	return nil
}

// ListQueryMultiError is an error wrapping multiple validation errors returned
// by ListQuery.ValidateAll() if the designated constraints aren't met.
type ListQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListQueryMultiError) AllErrors() []error { return m }

// ListQueryValidationError is the validation error returned by
// ListQuery.Validate if the designated constraints aren't met.
type ListQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListQueryValidationError) ErrorName() string { return "ListQueryValidationError" }

// Error satisfies the builtin error interface
func (e ListQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListQueryValidationError{}

// Validate checks the field values on Details with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Details) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Details with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DetailsMultiError, or nil if none found.
func (m *Details) ValidateAll() error {
	return m.validate(true)
}

func (m *Details) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sequence

	if all {
		switch v := interface{}(m.GetChangeDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailsValidationError{
					field:  "ChangeDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailsValidationError{
					field:  "ChangeDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChangeDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailsValidationError{
				field:  "ChangeDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ResourceOwner

	if all {
		switch v := interface{}(m.GetCreationDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DetailsValidationError{
					field:  "CreationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DetailsValidationError{
					field:  "CreationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreationDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DetailsValidationError{
				field:  "CreationDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DetailsMultiError(errors)
	}

	return nil
}

// DetailsMultiError is an error wrapping multiple validation errors returned
// by Details.ValidateAll() if the designated constraints aren't met.
type DetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DetailsMultiError) AllErrors() []error { return m }

// DetailsValidationError is the validation error returned by Details.Validate
// if the designated constraints aren't met.
type DetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DetailsValidationError) ErrorName() string { return "DetailsValidationError" }

// Error satisfies the builtin error interface
func (e DetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DetailsValidationError{}

// Validate checks the field values on ListDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListDetailsMultiError, or
// nil if none found.
func (m *ListDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalResult

	// no validation rules for ProcessedSequence

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDetailsValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDetailsValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDetailsValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListDetailsMultiError(errors)
	}

	return nil
}

// ListDetailsMultiError is an error wrapping multiple validation errors
// returned by ListDetails.ValidateAll() if the designated constraints aren't met.
type ListDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDetailsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDetailsMultiError) AllErrors() []error { return m }

// ListDetailsValidationError is the validation error returned by
// ListDetails.Validate if the designated constraints aren't met.
type ListDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDetailsValidationError) ErrorName() string { return "ListDetailsValidationError" }

// Error satisfies the builtin error interface
func (e ListDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDetailsValidationError{}
