// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: zitadel/project.proto

package project

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	object "github.com/zitadel/zitadel/pkg/grpc/object"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = object.TextQueryMethod(0)
)

// Validate checks the field values on Project with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Project) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Project with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProjectMultiError, or nil if none found.
func (m *Project) ValidateAll() error {
	return m.validate(true)
}

func (m *Project) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ProjectValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ProjectValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ProjectValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Name

	// no validation rules for State

	// no validation rules for ProjectRoleAssertion

	// no validation rules for ProjectRoleCheck

	// no validation rules for HasProjectCheck

	// no validation rules for PrivateLabelingSetting

	if len(errors) > 0 {
		return ProjectMultiError(errors)
	}

	return nil
}

// ProjectMultiError is an error wrapping multiple validation errors returned
// by Project.ValidateAll() if the designated constraints aren't met.
type ProjectMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectMultiError) AllErrors() []error { return m }

// ProjectValidationError is the validation error returned by Project.Validate
// if the designated constraints aren't met.
type ProjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectValidationError) ErrorName() string { return "ProjectValidationError" }

// Error satisfies the builtin error interface
func (e ProjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectValidationError{}

// Validate checks the field values on GrantedProject with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GrantedProject) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantedProject with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GrantedProjectMultiError,
// or nil if none found.
func (m *GrantedProject) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantedProject) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GrantId

	// no validation rules for GrantedOrgId

	// no validation rules for GrantedOrgName

	// no validation rules for State

	// no validation rules for ProjectId

	// no validation rules for ProjectName

	// no validation rules for ProjectOwnerId

	// no validation rules for ProjectOwnerName

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GrantedProjectValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GrantedProjectValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GrantedProjectValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GrantedProjectMultiError(errors)
	}

	return nil
}

// GrantedProjectMultiError is an error wrapping multiple validation errors
// returned by GrantedProject.ValidateAll() if the designated constraints
// aren't met.
type GrantedProjectMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantedProjectMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantedProjectMultiError) AllErrors() []error { return m }

// GrantedProjectValidationError is the validation error returned by
// GrantedProject.Validate if the designated constraints aren't met.
type GrantedProjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantedProjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantedProjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantedProjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantedProjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantedProjectValidationError) ErrorName() string { return "GrantedProjectValidationError" }

// Error satisfies the builtin error interface
func (e GrantedProjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantedProject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantedProjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantedProjectValidationError{}

// Validate checks the field values on ProjectQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProjectQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProjectQueryMultiError, or
// nil if none found.
func (m *ProjectQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *ProjectQuery_NameQuery:
		if v == nil {
			err := ProjectQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetNameQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectQueryValidationError{
						field:  "NameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectQueryValidationError{
						field:  "NameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetNameQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectQueryValidationError{
					field:  "NameQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ProjectQuery_ProjectResourceOwnerQuery:
		if v == nil {
			err := ProjectQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetProjectResourceOwnerQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectQueryValidationError{
						field:  "ProjectResourceOwnerQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectQueryValidationError{
						field:  "ProjectResourceOwnerQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetProjectResourceOwnerQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectQueryValidationError{
					field:  "ProjectResourceOwnerQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := ProjectQueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectQueryMultiError(errors)
	}

	return nil
}

// ProjectQueryMultiError is an error wrapping multiple validation errors
// returned by ProjectQuery.ValidateAll() if the designated constraints aren't met.
type ProjectQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectQueryMultiError) AllErrors() []error { return m }

// ProjectQueryValidationError is the validation error returned by
// ProjectQuery.Validate if the designated constraints aren't met.
type ProjectQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectQueryValidationError) ErrorName() string { return "ProjectQueryValidationError" }

// Error satisfies the builtin error interface
func (e ProjectQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectQueryValidationError{}

// Validate checks the field values on ProjectNameQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProjectNameQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectNameQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectNameQueryMultiError, or nil if none found.
func (m *ProjectNameQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectNameQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) > 200 {
		err := ProjectNameQueryValidationError{
			field:  "Name",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := ProjectNameQueryValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectNameQueryMultiError(errors)
	}

	return nil
}

// ProjectNameQueryMultiError is an error wrapping multiple validation errors
// returned by ProjectNameQuery.ValidateAll() if the designated constraints
// aren't met.
type ProjectNameQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectNameQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectNameQueryMultiError) AllErrors() []error { return m }

// ProjectNameQueryValidationError is the validation error returned by
// ProjectNameQuery.Validate if the designated constraints aren't met.
type ProjectNameQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectNameQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectNameQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectNameQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectNameQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectNameQueryValidationError) ErrorName() string { return "ProjectNameQueryValidationError" }

// Error satisfies the builtin error interface
func (e ProjectNameQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectNameQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectNameQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectNameQueryValidationError{}

// Validate checks the field values on ProjectResourceOwnerQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ProjectResourceOwnerQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectResourceOwnerQuery with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectResourceOwnerQueryMultiError, or nil if none found.
func (m *ProjectResourceOwnerQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectResourceOwnerQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetResourceOwner()) > 200 {
		err := ProjectResourceOwnerQueryValidationError{
			field:  "ResourceOwner",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectResourceOwnerQueryMultiError(errors)
	}

	return nil
}

// ProjectResourceOwnerQueryMultiError is an error wrapping multiple validation
// errors returned by ProjectResourceOwnerQuery.ValidateAll() if the
// designated constraints aren't met.
type ProjectResourceOwnerQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectResourceOwnerQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectResourceOwnerQueryMultiError) AllErrors() []error { return m }

// ProjectResourceOwnerQueryValidationError is the validation error returned by
// ProjectResourceOwnerQuery.Validate if the designated constraints aren't met.
type ProjectResourceOwnerQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectResourceOwnerQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectResourceOwnerQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectResourceOwnerQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectResourceOwnerQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectResourceOwnerQueryValidationError) ErrorName() string {
	return "ProjectResourceOwnerQueryValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectResourceOwnerQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectResourceOwnerQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectResourceOwnerQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectResourceOwnerQueryValidationError{}

// Validate checks the field values on Role with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Role) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Role with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RoleMultiError, or nil if none found.
func (m *Role) ValidateAll() error {
	return m.validate(true)
}

func (m *Role) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	if all {
		switch v := interface{}(m.GetDetails()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RoleValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RoleValidationError{
					field:  "Details",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetails()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RoleValidationError{
				field:  "Details",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DisplayName

	// no validation rules for Group

	if len(errors) > 0 {
		return RoleMultiError(errors)
	}

	return nil
}

// RoleMultiError is an error wrapping multiple validation errors returned by
// Role.ValidateAll() if the designated constraints aren't met.
type RoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleMultiError) AllErrors() []error { return m }

// RoleValidationError is the validation error returned by Role.Validate if the
// designated constraints aren't met.
type RoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleValidationError) ErrorName() string { return "RoleValidationError" }

// Error satisfies the builtin error interface
func (e RoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleValidationError{}

// Validate checks the field values on RoleQuery with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleQueryMultiError, or nil
// if none found.
func (m *RoleQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *RoleQuery_KeyQuery:
		if v == nil {
			err := RoleQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetKeyQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RoleQueryValidationError{
						field:  "KeyQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RoleQueryValidationError{
						field:  "KeyQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetKeyQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RoleQueryValidationError{
					field:  "KeyQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RoleQuery_DisplayNameQuery:
		if v == nil {
			err := RoleQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetDisplayNameQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RoleQueryValidationError{
						field:  "DisplayNameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RoleQueryValidationError{
						field:  "DisplayNameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDisplayNameQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RoleQueryValidationError{
					field:  "DisplayNameQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := RoleQueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RoleQueryMultiError(errors)
	}

	return nil
}

// RoleQueryMultiError is an error wrapping multiple validation errors returned
// by RoleQuery.ValidateAll() if the designated constraints aren't met.
type RoleQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleQueryMultiError) AllErrors() []error { return m }

// RoleQueryValidationError is the validation error returned by
// RoleQuery.Validate if the designated constraints aren't met.
type RoleQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleQueryValidationError) ErrorName() string { return "RoleQueryValidationError" }

// Error satisfies the builtin error interface
func (e RoleQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleQueryValidationError{}

// Validate checks the field values on RoleKeyQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleKeyQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleKeyQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleKeyQueryMultiError, or
// nil if none found.
func (m *RoleKeyQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleKeyQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetKey()) > 200 {
		err := RoleKeyQueryValidationError{
			field:  "Key",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := RoleKeyQueryValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RoleKeyQueryMultiError(errors)
	}

	return nil
}

// RoleKeyQueryMultiError is an error wrapping multiple validation errors
// returned by RoleKeyQuery.ValidateAll() if the designated constraints aren't met.
type RoleKeyQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleKeyQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleKeyQueryMultiError) AllErrors() []error { return m }

// RoleKeyQueryValidationError is the validation error returned by
// RoleKeyQuery.Validate if the designated constraints aren't met.
type RoleKeyQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleKeyQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleKeyQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleKeyQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleKeyQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleKeyQueryValidationError) ErrorName() string { return "RoleKeyQueryValidationError" }

// Error satisfies the builtin error interface
func (e RoleKeyQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleKeyQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleKeyQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleKeyQueryValidationError{}

// Validate checks the field values on RoleDisplayNameQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RoleDisplayNameQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleDisplayNameQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RoleDisplayNameQueryMultiError, or nil if none found.
func (m *RoleDisplayNameQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleDisplayNameQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDisplayName()) > 200 {
		err := RoleDisplayNameQueryValidationError{
			field:  "DisplayName",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := RoleDisplayNameQueryValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RoleDisplayNameQueryMultiError(errors)
	}

	return nil
}

// RoleDisplayNameQueryMultiError is an error wrapping multiple validation
// errors returned by RoleDisplayNameQuery.ValidateAll() if the designated
// constraints aren't met.
type RoleDisplayNameQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleDisplayNameQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleDisplayNameQueryMultiError) AllErrors() []error { return m }

// RoleDisplayNameQueryValidationError is the validation error returned by
// RoleDisplayNameQuery.Validate if the designated constraints aren't met.
type RoleDisplayNameQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleDisplayNameQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleDisplayNameQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleDisplayNameQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleDisplayNameQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleDisplayNameQueryValidationError) ErrorName() string {
	return "RoleDisplayNameQueryValidationError"
}

// Error satisfies the builtin error interface
func (e RoleDisplayNameQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleDisplayNameQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleDisplayNameQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleDisplayNameQueryValidationError{}

// Validate checks the field values on ProjectGrantQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProjectGrantQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectGrantQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProjectGrantQueryMultiError, or nil if none found.
func (m *ProjectGrantQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectGrantQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *ProjectGrantQuery_ProjectNameQuery:
		if v == nil {
			err := ProjectGrantQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetProjectNameQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectGrantQueryValidationError{
						field:  "ProjectNameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectGrantQueryValidationError{
						field:  "ProjectNameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetProjectNameQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectGrantQueryValidationError{
					field:  "ProjectNameQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ProjectGrantQuery_RoleKeyQuery:
		if v == nil {
			err := ProjectGrantQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetRoleKeyQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProjectGrantQueryValidationError{
						field:  "RoleKeyQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProjectGrantQueryValidationError{
						field:  "RoleKeyQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRoleKeyQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProjectGrantQueryValidationError{
					field:  "RoleKeyQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := ProjectGrantQueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectGrantQueryMultiError(errors)
	}

	return nil
}

// ProjectGrantQueryMultiError is an error wrapping multiple validation errors
// returned by ProjectGrantQuery.ValidateAll() if the designated constraints
// aren't met.
type ProjectGrantQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectGrantQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectGrantQueryMultiError) AllErrors() []error { return m }

// ProjectGrantQueryValidationError is the validation error returned by
// ProjectGrantQuery.Validate if the designated constraints aren't met.
type ProjectGrantQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectGrantQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectGrantQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectGrantQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectGrantQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectGrantQueryValidationError) ErrorName() string {
	return "ProjectGrantQueryValidationError"
}

// Error satisfies the builtin error interface
func (e ProjectGrantQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectGrantQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectGrantQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectGrantQueryValidationError{}

// Validate checks the field values on AllProjectGrantQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AllProjectGrantQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AllProjectGrantQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AllProjectGrantQueryMultiError, or nil if none found.
func (m *AllProjectGrantQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *AllProjectGrantQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofQueryPresent := false
	switch v := m.Query.(type) {
	case *AllProjectGrantQuery_ProjectNameQuery:
		if v == nil {
			err := AllProjectGrantQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetProjectNameQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "ProjectNameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "ProjectNameQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetProjectNameQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllProjectGrantQueryValidationError{
					field:  "ProjectNameQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AllProjectGrantQuery_RoleKeyQuery:
		if v == nil {
			err := AllProjectGrantQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetRoleKeyQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "RoleKeyQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "RoleKeyQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRoleKeyQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllProjectGrantQueryValidationError{
					field:  "RoleKeyQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AllProjectGrantQuery_ProjectIdQuery:
		if v == nil {
			err := AllProjectGrantQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetProjectIdQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "ProjectIdQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "ProjectIdQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetProjectIdQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllProjectGrantQueryValidationError{
					field:  "ProjectIdQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AllProjectGrantQuery_GrantedOrgIdQuery:
		if v == nil {
			err := AllProjectGrantQueryValidationError{
				field:  "Query",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofQueryPresent = true

		if all {
			switch v := interface{}(m.GetGrantedOrgIdQuery()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "GrantedOrgIdQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AllProjectGrantQueryValidationError{
						field:  "GrantedOrgIdQuery",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetGrantedOrgIdQuery()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AllProjectGrantQueryValidationError{
					field:  "GrantedOrgIdQuery",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofQueryPresent {
		err := AllProjectGrantQueryValidationError{
			field:  "Query",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AllProjectGrantQueryMultiError(errors)
	}

	return nil
}

// AllProjectGrantQueryMultiError is an error wrapping multiple validation
// errors returned by AllProjectGrantQuery.ValidateAll() if the designated
// constraints aren't met.
type AllProjectGrantQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AllProjectGrantQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AllProjectGrantQueryMultiError) AllErrors() []error { return m }

// AllProjectGrantQueryValidationError is the validation error returned by
// AllProjectGrantQuery.Validate if the designated constraints aren't met.
type AllProjectGrantQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AllProjectGrantQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AllProjectGrantQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AllProjectGrantQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AllProjectGrantQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AllProjectGrantQueryValidationError) ErrorName() string {
	return "AllProjectGrantQueryValidationError"
}

// Error satisfies the builtin error interface
func (e AllProjectGrantQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAllProjectGrantQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AllProjectGrantQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AllProjectGrantQueryValidationError{}

// Validate checks the field values on GrantProjectNameQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrantProjectNameQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantProjectNameQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantProjectNameQueryMultiError, or nil if none found.
func (m *GrantProjectNameQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantProjectNameQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) > 200 {
		err := GrantProjectNameQueryValidationError{
			field:  "Name",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := GrantProjectNameQueryValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GrantProjectNameQueryMultiError(errors)
	}

	return nil
}

// GrantProjectNameQueryMultiError is an error wrapping multiple validation
// errors returned by GrantProjectNameQuery.ValidateAll() if the designated
// constraints aren't met.
type GrantProjectNameQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantProjectNameQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantProjectNameQueryMultiError) AllErrors() []error { return m }

// GrantProjectNameQueryValidationError is the validation error returned by
// GrantProjectNameQuery.Validate if the designated constraints aren't met.
type GrantProjectNameQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantProjectNameQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantProjectNameQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantProjectNameQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantProjectNameQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantProjectNameQueryValidationError) ErrorName() string {
	return "GrantProjectNameQueryValidationError"
}

// Error satisfies the builtin error interface
func (e GrantProjectNameQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantProjectNameQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantProjectNameQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantProjectNameQueryValidationError{}

// Validate checks the field values on GrantRoleKeyQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GrantRoleKeyQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantRoleKeyQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantRoleKeyQueryMultiError, or nil if none found.
func (m *GrantRoleKeyQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantRoleKeyQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRoleKey()) > 200 {
		err := GrantRoleKeyQueryValidationError{
			field:  "RoleKey",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := GrantRoleKeyQueryValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GrantRoleKeyQueryMultiError(errors)
	}

	return nil
}

// GrantRoleKeyQueryMultiError is an error wrapping multiple validation errors
// returned by GrantRoleKeyQuery.ValidateAll() if the designated constraints
// aren't met.
type GrantRoleKeyQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantRoleKeyQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantRoleKeyQueryMultiError) AllErrors() []error { return m }

// GrantRoleKeyQueryValidationError is the validation error returned by
// GrantRoleKeyQuery.Validate if the designated constraints aren't met.
type GrantRoleKeyQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantRoleKeyQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantRoleKeyQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantRoleKeyQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantRoleKeyQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantRoleKeyQueryValidationError) ErrorName() string {
	return "GrantRoleKeyQueryValidationError"
}

// Error satisfies the builtin error interface
func (e GrantRoleKeyQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantRoleKeyQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantRoleKeyQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantRoleKeyQueryValidationError{}

// Validate checks the field values on ProjectIDQuery with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProjectIDQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProjectIDQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProjectIDQueryMultiError,
// or nil if none found.
func (m *ProjectIDQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *ProjectIDQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProjectId()) > 200 {
		err := ProjectIDQueryValidationError{
			field:  "ProjectId",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ProjectIDQueryMultiError(errors)
	}

	return nil
}

// ProjectIDQueryMultiError is an error wrapping multiple validation errors
// returned by ProjectIDQuery.ValidateAll() if the designated constraints
// aren't met.
type ProjectIDQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProjectIDQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProjectIDQueryMultiError) AllErrors() []error { return m }

// ProjectIDQueryValidationError is the validation error returned by
// ProjectIDQuery.Validate if the designated constraints aren't met.
type ProjectIDQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProjectIDQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProjectIDQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProjectIDQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProjectIDQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProjectIDQueryValidationError) ErrorName() string { return "ProjectIDQueryValidationError" }

// Error satisfies the builtin error interface
func (e ProjectIDQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProjectIDQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProjectIDQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProjectIDQueryValidationError{}

// Validate checks the field values on GrantedOrgIDQuery with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GrantedOrgIDQuery) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantedOrgIDQuery with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantedOrgIDQueryMultiError, or nil if none found.
func (m *GrantedOrgIDQuery) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantedOrgIDQuery) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetGrantedOrgId()) > 200 {
		err := GrantedOrgIDQueryValidationError{
			field:  "GrantedOrgId",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GrantedOrgIDQueryMultiError(errors)
	}

	return nil
}

// GrantedOrgIDQueryMultiError is an error wrapping multiple validation errors
// returned by GrantedOrgIDQuery.ValidateAll() if the designated constraints
// aren't met.
type GrantedOrgIDQueryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantedOrgIDQueryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantedOrgIDQueryMultiError) AllErrors() []error { return m }

// GrantedOrgIDQueryValidationError is the validation error returned by
// GrantedOrgIDQuery.Validate if the designated constraints aren't met.
type GrantedOrgIDQueryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantedOrgIDQueryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantedOrgIDQueryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantedOrgIDQueryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantedOrgIDQueryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantedOrgIDQueryValidationError) ErrorName() string {
	return "GrantedOrgIDQueryValidationError"
}

// Error satisfies the builtin error interface
func (e GrantedOrgIDQueryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantedOrgIDQuery.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantedOrgIDQueryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantedOrgIDQueryValidationError{}
