// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: zitadel/action/v2beta/action_service.proto

package actionconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2beta "github.com/zitadel/zitadel/pkg/grpc/action/v2beta"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ActionServiceName is the fully-qualified name of the ActionService service.
	ActionServiceName = "zitadel.action.v2beta.ActionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ActionServiceCreateTargetProcedure is the fully-qualified name of the ActionService's
	// CreateTarget RPC.
	ActionServiceCreateTargetProcedure = "/zitadel.action.v2beta.ActionService/CreateTarget"
	// ActionServiceUpdateTargetProcedure is the fully-qualified name of the ActionService's
	// UpdateTarget RPC.
	ActionServiceUpdateTargetProcedure = "/zitadel.action.v2beta.ActionService/UpdateTarget"
	// ActionServiceDeleteTargetProcedure is the fully-qualified name of the ActionService's
	// DeleteTarget RPC.
	ActionServiceDeleteTargetProcedure = "/zitadel.action.v2beta.ActionService/DeleteTarget"
	// ActionServiceGetTargetProcedure is the fully-qualified name of the ActionService's GetTarget RPC.
	ActionServiceGetTargetProcedure = "/zitadel.action.v2beta.ActionService/GetTarget"
	// ActionServiceListTargetsProcedure is the fully-qualified name of the ActionService's ListTargets
	// RPC.
	ActionServiceListTargetsProcedure = "/zitadel.action.v2beta.ActionService/ListTargets"
	// ActionServiceSetExecutionProcedure is the fully-qualified name of the ActionService's
	// SetExecution RPC.
	ActionServiceSetExecutionProcedure = "/zitadel.action.v2beta.ActionService/SetExecution"
	// ActionServiceListExecutionsProcedure is the fully-qualified name of the ActionService's
	// ListExecutions RPC.
	ActionServiceListExecutionsProcedure = "/zitadel.action.v2beta.ActionService/ListExecutions"
	// ActionServiceListExecutionFunctionsProcedure is the fully-qualified name of the ActionService's
	// ListExecutionFunctions RPC.
	ActionServiceListExecutionFunctionsProcedure = "/zitadel.action.v2beta.ActionService/ListExecutionFunctions"
	// ActionServiceListExecutionMethodsProcedure is the fully-qualified name of the ActionService's
	// ListExecutionMethods RPC.
	ActionServiceListExecutionMethodsProcedure = "/zitadel.action.v2beta.ActionService/ListExecutionMethods"
	// ActionServiceListExecutionServicesProcedure is the fully-qualified name of the ActionService's
	// ListExecutionServices RPC.
	ActionServiceListExecutionServicesProcedure = "/zitadel.action.v2beta.ActionService/ListExecutionServices"
)

// ActionServiceClient is a client for the zitadel.action.v2beta.ActionService service.
type ActionServiceClient interface {
	// Create Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Create a new target to your endpoint, which can be used in executions.
	//
	// Required permission:
	//   - `action.target.write`
	CreateTarget(context.Context, *connect.Request[v2beta.CreateTargetRequest]) (*connect.Response[v2beta.CreateTargetResponse], error)
	// Update Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Update an existing target.
	// To generate a new signing key set the optional expirationSigningKey.
	//
	// Required permission:
	//   - `action.target.write`
	UpdateTarget(context.Context, *connect.Request[v2beta.UpdateTargetRequest]) (*connect.Response[v2beta.UpdateTargetResponse], error)
	// Delete Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Delete an existing target. This will remove it from any configured execution as well.
	// In case the target is not found, the request will return a successful response as
	// the desired state is already achieved.
	//
	// Required permission:
	//   - `action.target.delete`
	DeleteTarget(context.Context, *connect.Request[v2beta.DeleteTargetRequest]) (*connect.Response[v2beta.DeleteTargetResponse], error)
	// Get Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Returns the target identified by the requested ID.
	//
	// Required permission:
	//   - `action.target.read`
	GetTarget(context.Context, *connect.Request[v2beta.GetTargetRequest]) (*connect.Response[v2beta.GetTargetResponse], error)
	// List targets
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all matching targets. By default all targets of the instance are returned.
	// Make sure to include a limit and sorting for pagination.
	//
	// Required permission:
	//   - `action.target.read`
	ListTargets(context.Context, *connect.Request[v2beta.ListTargetsRequest]) (*connect.Response[v2beta.ListTargetsResponse], error)
	// Set Execution
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Sets an execution to call a target or include the targets of another execution.
	// Setting an empty list of targets will remove all targets from the execution, making it a noop.
	//
	// Required permission:
	//   - `action.execution.write`
	SetExecution(context.Context, *connect.Request[v2beta.SetExecutionRequest]) (*connect.Response[v2beta.SetExecutionResponse], error)
	// List Executions
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all matching executions. By default all executions of the instance are returned that have at least one execution target.
	// Make sure to include a limit and sorting for pagination.
	//
	// Required permission:
	//   - `action.execution.read`
	ListExecutions(context.Context, *connect.Request[v2beta.ListExecutionsRequest]) (*connect.Response[v2beta.ListExecutionsResponse], error)
	// List Execution Functions
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all available functions which can be used as condition for executions.
	ListExecutionFunctions(context.Context, *connect.Request[v2beta.ListExecutionFunctionsRequest]) (*connect.Response[v2beta.ListExecutionFunctionsResponse], error)
	// List Execution Methods
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all available methods which can be used as condition for executions.
	ListExecutionMethods(context.Context, *connect.Request[v2beta.ListExecutionMethodsRequest]) (*connect.Response[v2beta.ListExecutionMethodsResponse], error)
	// List Execution Services
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all available services which can be used as condition for executions.
	ListExecutionServices(context.Context, *connect.Request[v2beta.ListExecutionServicesRequest]) (*connect.Response[v2beta.ListExecutionServicesResponse], error)
}

// NewActionServiceClient constructs a client for the zitadel.action.v2beta.ActionService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewActionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ActionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	actionServiceMethods := v2beta.File_zitadel_action_v2beta_action_service_proto.Services().ByName("ActionService").Methods()
	return &actionServiceClient{
		createTarget: connect.NewClient[v2beta.CreateTargetRequest, v2beta.CreateTargetResponse](
			httpClient,
			baseURL+ActionServiceCreateTargetProcedure,
			connect.WithSchema(actionServiceMethods.ByName("CreateTarget")),
			connect.WithClientOptions(opts...),
		),
		updateTarget: connect.NewClient[v2beta.UpdateTargetRequest, v2beta.UpdateTargetResponse](
			httpClient,
			baseURL+ActionServiceUpdateTargetProcedure,
			connect.WithSchema(actionServiceMethods.ByName("UpdateTarget")),
			connect.WithClientOptions(opts...),
		),
		deleteTarget: connect.NewClient[v2beta.DeleteTargetRequest, v2beta.DeleteTargetResponse](
			httpClient,
			baseURL+ActionServiceDeleteTargetProcedure,
			connect.WithSchema(actionServiceMethods.ByName("DeleteTarget")),
			connect.WithClientOptions(opts...),
		),
		getTarget: connect.NewClient[v2beta.GetTargetRequest, v2beta.GetTargetResponse](
			httpClient,
			baseURL+ActionServiceGetTargetProcedure,
			connect.WithSchema(actionServiceMethods.ByName("GetTarget")),
			connect.WithClientOptions(opts...),
		),
		listTargets: connect.NewClient[v2beta.ListTargetsRequest, v2beta.ListTargetsResponse](
			httpClient,
			baseURL+ActionServiceListTargetsProcedure,
			connect.WithSchema(actionServiceMethods.ByName("ListTargets")),
			connect.WithClientOptions(opts...),
		),
		setExecution: connect.NewClient[v2beta.SetExecutionRequest, v2beta.SetExecutionResponse](
			httpClient,
			baseURL+ActionServiceSetExecutionProcedure,
			connect.WithSchema(actionServiceMethods.ByName("SetExecution")),
			connect.WithClientOptions(opts...),
		),
		listExecutions: connect.NewClient[v2beta.ListExecutionsRequest, v2beta.ListExecutionsResponse](
			httpClient,
			baseURL+ActionServiceListExecutionsProcedure,
			connect.WithSchema(actionServiceMethods.ByName("ListExecutions")),
			connect.WithClientOptions(opts...),
		),
		listExecutionFunctions: connect.NewClient[v2beta.ListExecutionFunctionsRequest, v2beta.ListExecutionFunctionsResponse](
			httpClient,
			baseURL+ActionServiceListExecutionFunctionsProcedure,
			connect.WithSchema(actionServiceMethods.ByName("ListExecutionFunctions")),
			connect.WithClientOptions(opts...),
		),
		listExecutionMethods: connect.NewClient[v2beta.ListExecutionMethodsRequest, v2beta.ListExecutionMethodsResponse](
			httpClient,
			baseURL+ActionServiceListExecutionMethodsProcedure,
			connect.WithSchema(actionServiceMethods.ByName("ListExecutionMethods")),
			connect.WithClientOptions(opts...),
		),
		listExecutionServices: connect.NewClient[v2beta.ListExecutionServicesRequest, v2beta.ListExecutionServicesResponse](
			httpClient,
			baseURL+ActionServiceListExecutionServicesProcedure,
			connect.WithSchema(actionServiceMethods.ByName("ListExecutionServices")),
			connect.WithClientOptions(opts...),
		),
	}
}

// actionServiceClient implements ActionServiceClient.
type actionServiceClient struct {
	createTarget           *connect.Client[v2beta.CreateTargetRequest, v2beta.CreateTargetResponse]
	updateTarget           *connect.Client[v2beta.UpdateTargetRequest, v2beta.UpdateTargetResponse]
	deleteTarget           *connect.Client[v2beta.DeleteTargetRequest, v2beta.DeleteTargetResponse]
	getTarget              *connect.Client[v2beta.GetTargetRequest, v2beta.GetTargetResponse]
	listTargets            *connect.Client[v2beta.ListTargetsRequest, v2beta.ListTargetsResponse]
	setExecution           *connect.Client[v2beta.SetExecutionRequest, v2beta.SetExecutionResponse]
	listExecutions         *connect.Client[v2beta.ListExecutionsRequest, v2beta.ListExecutionsResponse]
	listExecutionFunctions *connect.Client[v2beta.ListExecutionFunctionsRequest, v2beta.ListExecutionFunctionsResponse]
	listExecutionMethods   *connect.Client[v2beta.ListExecutionMethodsRequest, v2beta.ListExecutionMethodsResponse]
	listExecutionServices  *connect.Client[v2beta.ListExecutionServicesRequest, v2beta.ListExecutionServicesResponse]
}

// CreateTarget calls zitadel.action.v2beta.ActionService.CreateTarget.
func (c *actionServiceClient) CreateTarget(ctx context.Context, req *connect.Request[v2beta.CreateTargetRequest]) (*connect.Response[v2beta.CreateTargetResponse], error) {
	return c.createTarget.CallUnary(ctx, req)
}

// UpdateTarget calls zitadel.action.v2beta.ActionService.UpdateTarget.
func (c *actionServiceClient) UpdateTarget(ctx context.Context, req *connect.Request[v2beta.UpdateTargetRequest]) (*connect.Response[v2beta.UpdateTargetResponse], error) {
	return c.updateTarget.CallUnary(ctx, req)
}

// DeleteTarget calls zitadel.action.v2beta.ActionService.DeleteTarget.
func (c *actionServiceClient) DeleteTarget(ctx context.Context, req *connect.Request[v2beta.DeleteTargetRequest]) (*connect.Response[v2beta.DeleteTargetResponse], error) {
	return c.deleteTarget.CallUnary(ctx, req)
}

// GetTarget calls zitadel.action.v2beta.ActionService.GetTarget.
func (c *actionServiceClient) GetTarget(ctx context.Context, req *connect.Request[v2beta.GetTargetRequest]) (*connect.Response[v2beta.GetTargetResponse], error) {
	return c.getTarget.CallUnary(ctx, req)
}

// ListTargets calls zitadel.action.v2beta.ActionService.ListTargets.
func (c *actionServiceClient) ListTargets(ctx context.Context, req *connect.Request[v2beta.ListTargetsRequest]) (*connect.Response[v2beta.ListTargetsResponse], error) {
	return c.listTargets.CallUnary(ctx, req)
}

// SetExecution calls zitadel.action.v2beta.ActionService.SetExecution.
func (c *actionServiceClient) SetExecution(ctx context.Context, req *connect.Request[v2beta.SetExecutionRequest]) (*connect.Response[v2beta.SetExecutionResponse], error) {
	return c.setExecution.CallUnary(ctx, req)
}

// ListExecutions calls zitadel.action.v2beta.ActionService.ListExecutions.
func (c *actionServiceClient) ListExecutions(ctx context.Context, req *connect.Request[v2beta.ListExecutionsRequest]) (*connect.Response[v2beta.ListExecutionsResponse], error) {
	return c.listExecutions.CallUnary(ctx, req)
}

// ListExecutionFunctions calls zitadel.action.v2beta.ActionService.ListExecutionFunctions.
func (c *actionServiceClient) ListExecutionFunctions(ctx context.Context, req *connect.Request[v2beta.ListExecutionFunctionsRequest]) (*connect.Response[v2beta.ListExecutionFunctionsResponse], error) {
	return c.listExecutionFunctions.CallUnary(ctx, req)
}

// ListExecutionMethods calls zitadel.action.v2beta.ActionService.ListExecutionMethods.
func (c *actionServiceClient) ListExecutionMethods(ctx context.Context, req *connect.Request[v2beta.ListExecutionMethodsRequest]) (*connect.Response[v2beta.ListExecutionMethodsResponse], error) {
	return c.listExecutionMethods.CallUnary(ctx, req)
}

// ListExecutionServices calls zitadel.action.v2beta.ActionService.ListExecutionServices.
func (c *actionServiceClient) ListExecutionServices(ctx context.Context, req *connect.Request[v2beta.ListExecutionServicesRequest]) (*connect.Response[v2beta.ListExecutionServicesResponse], error) {
	return c.listExecutionServices.CallUnary(ctx, req)
}

// ActionServiceHandler is an implementation of the zitadel.action.v2beta.ActionService service.
type ActionServiceHandler interface {
	// Create Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Create a new target to your endpoint, which can be used in executions.
	//
	// Required permission:
	//   - `action.target.write`
	CreateTarget(context.Context, *connect.Request[v2beta.CreateTargetRequest]) (*connect.Response[v2beta.CreateTargetResponse], error)
	// Update Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Update an existing target.
	// To generate a new signing key set the optional expirationSigningKey.
	//
	// Required permission:
	//   - `action.target.write`
	UpdateTarget(context.Context, *connect.Request[v2beta.UpdateTargetRequest]) (*connect.Response[v2beta.UpdateTargetResponse], error)
	// Delete Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Delete an existing target. This will remove it from any configured execution as well.
	// In case the target is not found, the request will return a successful response as
	// the desired state is already achieved.
	//
	// Required permission:
	//   - `action.target.delete`
	DeleteTarget(context.Context, *connect.Request[v2beta.DeleteTargetRequest]) (*connect.Response[v2beta.DeleteTargetResponse], error)
	// Get Target
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Returns the target identified by the requested ID.
	//
	// Required permission:
	//   - `action.target.read`
	GetTarget(context.Context, *connect.Request[v2beta.GetTargetRequest]) (*connect.Response[v2beta.GetTargetResponse], error)
	// List targets
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all matching targets. By default all targets of the instance are returned.
	// Make sure to include a limit and sorting for pagination.
	//
	// Required permission:
	//   - `action.target.read`
	ListTargets(context.Context, *connect.Request[v2beta.ListTargetsRequest]) (*connect.Response[v2beta.ListTargetsResponse], error)
	// Set Execution
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// Sets an execution to call a target or include the targets of another execution.
	// Setting an empty list of targets will remove all targets from the execution, making it a noop.
	//
	// Required permission:
	//   - `action.execution.write`
	SetExecution(context.Context, *connect.Request[v2beta.SetExecutionRequest]) (*connect.Response[v2beta.SetExecutionResponse], error)
	// List Executions
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all matching executions. By default all executions of the instance are returned that have at least one execution target.
	// Make sure to include a limit and sorting for pagination.
	//
	// Required permission:
	//   - `action.execution.read`
	ListExecutions(context.Context, *connect.Request[v2beta.ListExecutionsRequest]) (*connect.Response[v2beta.ListExecutionsResponse], error)
	// List Execution Functions
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all available functions which can be used as condition for executions.
	ListExecutionFunctions(context.Context, *connect.Request[v2beta.ListExecutionFunctionsRequest]) (*connect.Response[v2beta.ListExecutionFunctionsResponse], error)
	// List Execution Methods
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all available methods which can be used as condition for executions.
	ListExecutionMethods(context.Context, *connect.Request[v2beta.ListExecutionMethodsRequest]) (*connect.Response[v2beta.ListExecutionMethodsResponse], error)
	// List Execution Services
	//
	// Deprecated: please move to the corresponding endpoint under action service v2. This endpoint will be removed with the next major version of ZITADEL.
	//
	// List all available services which can be used as condition for executions.
	ListExecutionServices(context.Context, *connect.Request[v2beta.ListExecutionServicesRequest]) (*connect.Response[v2beta.ListExecutionServicesResponse], error)
}

// NewActionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewActionServiceHandler(svc ActionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	actionServiceMethods := v2beta.File_zitadel_action_v2beta_action_service_proto.Services().ByName("ActionService").Methods()
	actionServiceCreateTargetHandler := connect.NewUnaryHandler(
		ActionServiceCreateTargetProcedure,
		svc.CreateTarget,
		connect.WithSchema(actionServiceMethods.ByName("CreateTarget")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceUpdateTargetHandler := connect.NewUnaryHandler(
		ActionServiceUpdateTargetProcedure,
		svc.UpdateTarget,
		connect.WithSchema(actionServiceMethods.ByName("UpdateTarget")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceDeleteTargetHandler := connect.NewUnaryHandler(
		ActionServiceDeleteTargetProcedure,
		svc.DeleteTarget,
		connect.WithSchema(actionServiceMethods.ByName("DeleteTarget")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceGetTargetHandler := connect.NewUnaryHandler(
		ActionServiceGetTargetProcedure,
		svc.GetTarget,
		connect.WithSchema(actionServiceMethods.ByName("GetTarget")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceListTargetsHandler := connect.NewUnaryHandler(
		ActionServiceListTargetsProcedure,
		svc.ListTargets,
		connect.WithSchema(actionServiceMethods.ByName("ListTargets")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceSetExecutionHandler := connect.NewUnaryHandler(
		ActionServiceSetExecutionProcedure,
		svc.SetExecution,
		connect.WithSchema(actionServiceMethods.ByName("SetExecution")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceListExecutionsHandler := connect.NewUnaryHandler(
		ActionServiceListExecutionsProcedure,
		svc.ListExecutions,
		connect.WithSchema(actionServiceMethods.ByName("ListExecutions")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceListExecutionFunctionsHandler := connect.NewUnaryHandler(
		ActionServiceListExecutionFunctionsProcedure,
		svc.ListExecutionFunctions,
		connect.WithSchema(actionServiceMethods.ByName("ListExecutionFunctions")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceListExecutionMethodsHandler := connect.NewUnaryHandler(
		ActionServiceListExecutionMethodsProcedure,
		svc.ListExecutionMethods,
		connect.WithSchema(actionServiceMethods.ByName("ListExecutionMethods")),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceListExecutionServicesHandler := connect.NewUnaryHandler(
		ActionServiceListExecutionServicesProcedure,
		svc.ListExecutionServices,
		connect.WithSchema(actionServiceMethods.ByName("ListExecutionServices")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zitadel.action.v2beta.ActionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ActionServiceCreateTargetProcedure:
			actionServiceCreateTargetHandler.ServeHTTP(w, r)
		case ActionServiceUpdateTargetProcedure:
			actionServiceUpdateTargetHandler.ServeHTTP(w, r)
		case ActionServiceDeleteTargetProcedure:
			actionServiceDeleteTargetHandler.ServeHTTP(w, r)
		case ActionServiceGetTargetProcedure:
			actionServiceGetTargetHandler.ServeHTTP(w, r)
		case ActionServiceListTargetsProcedure:
			actionServiceListTargetsHandler.ServeHTTP(w, r)
		case ActionServiceSetExecutionProcedure:
			actionServiceSetExecutionHandler.ServeHTTP(w, r)
		case ActionServiceListExecutionsProcedure:
			actionServiceListExecutionsHandler.ServeHTTP(w, r)
		case ActionServiceListExecutionFunctionsProcedure:
			actionServiceListExecutionFunctionsHandler.ServeHTTP(w, r)
		case ActionServiceListExecutionMethodsProcedure:
			actionServiceListExecutionMethodsHandler.ServeHTTP(w, r)
		case ActionServiceListExecutionServicesProcedure:
			actionServiceListExecutionServicesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedActionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedActionServiceHandler struct{}

func (UnimplementedActionServiceHandler) CreateTarget(context.Context, *connect.Request[v2beta.CreateTargetRequest]) (*connect.Response[v2beta.CreateTargetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.CreateTarget is not implemented"))
}

func (UnimplementedActionServiceHandler) UpdateTarget(context.Context, *connect.Request[v2beta.UpdateTargetRequest]) (*connect.Response[v2beta.UpdateTargetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.UpdateTarget is not implemented"))
}

func (UnimplementedActionServiceHandler) DeleteTarget(context.Context, *connect.Request[v2beta.DeleteTargetRequest]) (*connect.Response[v2beta.DeleteTargetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.DeleteTarget is not implemented"))
}

func (UnimplementedActionServiceHandler) GetTarget(context.Context, *connect.Request[v2beta.GetTargetRequest]) (*connect.Response[v2beta.GetTargetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.GetTarget is not implemented"))
}

func (UnimplementedActionServiceHandler) ListTargets(context.Context, *connect.Request[v2beta.ListTargetsRequest]) (*connect.Response[v2beta.ListTargetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.ListTargets is not implemented"))
}

func (UnimplementedActionServiceHandler) SetExecution(context.Context, *connect.Request[v2beta.SetExecutionRequest]) (*connect.Response[v2beta.SetExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.SetExecution is not implemented"))
}

func (UnimplementedActionServiceHandler) ListExecutions(context.Context, *connect.Request[v2beta.ListExecutionsRequest]) (*connect.Response[v2beta.ListExecutionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.ListExecutions is not implemented"))
}

func (UnimplementedActionServiceHandler) ListExecutionFunctions(context.Context, *connect.Request[v2beta.ListExecutionFunctionsRequest]) (*connect.Response[v2beta.ListExecutionFunctionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.ListExecutionFunctions is not implemented"))
}

func (UnimplementedActionServiceHandler) ListExecutionMethods(context.Context, *connect.Request[v2beta.ListExecutionMethodsRequest]) (*connect.Response[v2beta.ListExecutionMethodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.ListExecutionMethods is not implemented"))
}

func (UnimplementedActionServiceHandler) ListExecutionServices(context.Context, *connect.Request[v2beta.ListExecutionServicesRequest]) (*connect.Response[v2beta.ListExecutionServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.action.v2beta.ActionService.ListExecutionServices is not implemented"))
}
