// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: zitadel/session/v2/session_service.proto

package sessionconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/zitadel/zitadel/pkg/grpc/session/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "zitadel.session.v2.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceListSessionsProcedure is the fully-qualified name of the SessionService's
	// ListSessions RPC.
	SessionServiceListSessionsProcedure = "/zitadel.session.v2.SessionService/ListSessions"
	// SessionServiceGetSessionProcedure is the fully-qualified name of the SessionService's GetSession
	// RPC.
	SessionServiceGetSessionProcedure = "/zitadel.session.v2.SessionService/GetSession"
	// SessionServiceCreateSessionProcedure is the fully-qualified name of the SessionService's
	// CreateSession RPC.
	SessionServiceCreateSessionProcedure = "/zitadel.session.v2.SessionService/CreateSession"
	// SessionServiceSetSessionProcedure is the fully-qualified name of the SessionService's SetSession
	// RPC.
	SessionServiceSetSessionProcedure = "/zitadel.session.v2.SessionService/SetSession"
	// SessionServiceDeleteSessionProcedure is the fully-qualified name of the SessionService's
	// DeleteSession RPC.
	SessionServiceDeleteSessionProcedure = "/zitadel.session.v2.SessionService/DeleteSession"
)

// SessionServiceClient is a client for the zitadel.session.v2.SessionService service.
type SessionServiceClient interface {
	// List sessions
	//
	// Searches for sessions matching the given query. You can search by session ID, user ID,
	// creation date, creator, user agent or expiration date.
	//
	// Required permissions:
	//   - `session.read`
	//   - no permission required to search for own sessions
	ListSessions(context.Context, *connect.Request[v2.ListSessionsRequest]) (*connect.Response[v2.ListSessionsResponse], error)
	// Get Session
	//
	// Retrieve a session by its ID. Returns all information about the session, including
	// the factors that were verified, the metadata, user agent information and possible expiration date.
	// The session token is required unless either of the following conditions is met:
	//   - the caller created the session
	//   - the authenticated user requests their own session (checked user)
	//   - the security token provided in the authorization header has the same user agent as the session
	//   - the caller is granted the permission session.read permission on either the instance or on the checked user's organization
	//
	// Required permissions:
	//   - `session.read`
	//   - no permission required to get own sessions (see above) or when providing the current session token
	GetSession(context.Context, *connect.Request[v2.GetSessionRequest]) (*connect.Response[v2.GetSessionResponse], error)
	// Create Session
	//
	// Create a new session with initial checks, metadata and challenges for further verification.
	// A token will be returned, which is required for using the session as authentication, e.g.
	// when authenticating an OIDC auth request or SAML request.
	// Additionally, the session token can be used as OAuth2 access token to authenticate against
	// the ZITADEL APIs.
	//
	// Required permissions:
	//   - `session.write`
	CreateSession(context.Context, *connect.Request[v2.CreateSessionRequest]) (*connect.Response[v2.CreateSessionResponse], error)
	// Set Session
	//
	// Update an existing session with new information like additional checks or metadata
	// or request additional challenges.
	// A new session token will be returned. Note that the previous token will be invalidated.
	//
	// Required permissions:
	//   - `session.write`
	SetSession(context.Context, *connect.Request[v2.SetSessionRequest]) (*connect.Response[v2.SetSessionResponse], error)
	// DeleteSession
	//
	// Terminate an existing session. This invalidates the session and its token.
	// The session can no longer be used for the authentication of other resources
	// or to authenticate against the ZITADEL APIs.
	//
	// You can only terminate your own session, unless you are granted the `session.delete` permission.
	//
	// Required permissions:
	//   - `session.delete`
	//   - no permission required for own sessions or when providing the current session token
	DeleteSession(context.Context, *connect.Request[v2.DeleteSessionRequest]) (*connect.Response[v2.DeleteSessionResponse], error)
}

// NewSessionServiceClient constructs a client for the zitadel.session.v2.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v2.File_zitadel_session_v2_session_service_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		listSessions: connect.NewClient[v2.ListSessionsRequest, v2.ListSessionsResponse](
			httpClient,
			baseURL+SessionServiceListSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v2.GetSessionRequest, v2.GetSessionResponse](
			httpClient,
			baseURL+SessionServiceGetSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		createSession: connect.NewClient[v2.CreateSessionRequest, v2.CreateSessionResponse](
			httpClient,
			baseURL+SessionServiceCreateSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		setSession: connect.NewClient[v2.SetSessionRequest, v2.SetSessionResponse](
			httpClient,
			baseURL+SessionServiceSetSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetSession")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[v2.DeleteSessionRequest, v2.DeleteSessionResponse](
			httpClient,
			baseURL+SessionServiceDeleteSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	listSessions  *connect.Client[v2.ListSessionsRequest, v2.ListSessionsResponse]
	getSession    *connect.Client[v2.GetSessionRequest, v2.GetSessionResponse]
	createSession *connect.Client[v2.CreateSessionRequest, v2.CreateSessionResponse]
	setSession    *connect.Client[v2.SetSessionRequest, v2.SetSessionResponse]
	deleteSession *connect.Client[v2.DeleteSessionRequest, v2.DeleteSessionResponse]
}

// ListSessions calls zitadel.session.v2.SessionService.ListSessions.
func (c *sessionServiceClient) ListSessions(ctx context.Context, req *connect.Request[v2.ListSessionsRequest]) (*connect.Response[v2.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// GetSession calls zitadel.session.v2.SessionService.GetSession.
func (c *sessionServiceClient) GetSession(ctx context.Context, req *connect.Request[v2.GetSessionRequest]) (*connect.Response[v2.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// CreateSession calls zitadel.session.v2.SessionService.CreateSession.
func (c *sessionServiceClient) CreateSession(ctx context.Context, req *connect.Request[v2.CreateSessionRequest]) (*connect.Response[v2.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// SetSession calls zitadel.session.v2.SessionService.SetSession.
func (c *sessionServiceClient) SetSession(ctx context.Context, req *connect.Request[v2.SetSessionRequest]) (*connect.Response[v2.SetSessionResponse], error) {
	return c.setSession.CallUnary(ctx, req)
}

// DeleteSession calls zitadel.session.v2.SessionService.DeleteSession.
func (c *sessionServiceClient) DeleteSession(ctx context.Context, req *connect.Request[v2.DeleteSessionRequest]) (*connect.Response[v2.DeleteSessionResponse], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the zitadel.session.v2.SessionService service.
type SessionServiceHandler interface {
	// List sessions
	//
	// Searches for sessions matching the given query. You can search by session ID, user ID,
	// creation date, creator, user agent or expiration date.
	//
	// Required permissions:
	//   - `session.read`
	//   - no permission required to search for own sessions
	ListSessions(context.Context, *connect.Request[v2.ListSessionsRequest]) (*connect.Response[v2.ListSessionsResponse], error)
	// Get Session
	//
	// Retrieve a session by its ID. Returns all information about the session, including
	// the factors that were verified, the metadata, user agent information and possible expiration date.
	// The session token is required unless either of the following conditions is met:
	//   - the caller created the session
	//   - the authenticated user requests their own session (checked user)
	//   - the security token provided in the authorization header has the same user agent as the session
	//   - the caller is granted the permission session.read permission on either the instance or on the checked user's organization
	//
	// Required permissions:
	//   - `session.read`
	//   - no permission required to get own sessions (see above) or when providing the current session token
	GetSession(context.Context, *connect.Request[v2.GetSessionRequest]) (*connect.Response[v2.GetSessionResponse], error)
	// Create Session
	//
	// Create a new session with initial checks, metadata and challenges for further verification.
	// A token will be returned, which is required for using the session as authentication, e.g.
	// when authenticating an OIDC auth request or SAML request.
	// Additionally, the session token can be used as OAuth2 access token to authenticate against
	// the ZITADEL APIs.
	//
	// Required permissions:
	//   - `session.write`
	CreateSession(context.Context, *connect.Request[v2.CreateSessionRequest]) (*connect.Response[v2.CreateSessionResponse], error)
	// Set Session
	//
	// Update an existing session with new information like additional checks or metadata
	// or request additional challenges.
	// A new session token will be returned. Note that the previous token will be invalidated.
	//
	// Required permissions:
	//   - `session.write`
	SetSession(context.Context, *connect.Request[v2.SetSessionRequest]) (*connect.Response[v2.SetSessionResponse], error)
	// DeleteSession
	//
	// Terminate an existing session. This invalidates the session and its token.
	// The session can no longer be used for the authentication of other resources
	// or to authenticate against the ZITADEL APIs.
	//
	// You can only terminate your own session, unless you are granted the `session.delete` permission.
	//
	// Required permissions:
	//   - `session.delete`
	//   - no permission required for own sessions or when providing the current session token
	DeleteSession(context.Context, *connect.Request[v2.DeleteSessionRequest]) (*connect.Response[v2.DeleteSessionResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v2.File_zitadel_session_v2_session_service_proto.Services().ByName("SessionService").Methods()
	sessionServiceListSessionsHandler := connect.NewUnaryHandler(
		SessionServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetSessionHandler := connect.NewUnaryHandler(
		SessionServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceCreateSessionHandler := connect.NewUnaryHandler(
		SessionServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetSessionHandler := connect.NewUnaryHandler(
		SessionServiceSetSessionProcedure,
		svc.SetSession,
		connect.WithSchema(sessionServiceMethods.ByName("SetSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceDeleteSessionHandler := connect.NewUnaryHandler(
		SessionServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(sessionServiceMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/zitadel.session.v2.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceListSessionsProcedure:
			sessionServiceListSessionsHandler.ServeHTTP(w, r)
		case SessionServiceGetSessionProcedure:
			sessionServiceGetSessionHandler.ServeHTTP(w, r)
		case SessionServiceCreateSessionProcedure:
			sessionServiceCreateSessionHandler.ServeHTTP(w, r)
		case SessionServiceSetSessionProcedure:
			sessionServiceSetSessionHandler.ServeHTTP(w, r)
		case SessionServiceDeleteSessionProcedure:
			sessionServiceDeleteSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) ListSessions(context.Context, *connect.Request[v2.ListSessionsRequest]) (*connect.Response[v2.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.session.v2.SessionService.ListSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetSession(context.Context, *connect.Request[v2.GetSessionRequest]) (*connect.Response[v2.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.session.v2.SessionService.GetSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) CreateSession(context.Context, *connect.Request[v2.CreateSessionRequest]) (*connect.Response[v2.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.session.v2.SessionService.CreateSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetSession(context.Context, *connect.Request[v2.SetSessionRequest]) (*connect.Response[v2.SetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.session.v2.SessionService.SetSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) DeleteSession(context.Context, *connect.Request[v2.DeleteSessionRequest]) (*connect.Response[v2.DeleteSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("zitadel.session.v2.SessionService.DeleteSession is not implemented"))
}
