// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/user/v2/pat.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v2 "github.com/zitadel/zitadel/pkg/grpc/filter/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalAccessTokenFieldName int32

const (
	PersonalAccessTokenFieldName_PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED     PersonalAccessTokenFieldName = 0
	PersonalAccessTokenFieldName_PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE    PersonalAccessTokenFieldName = 1
	PersonalAccessTokenFieldName_PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID              PersonalAccessTokenFieldName = 2
	PersonalAccessTokenFieldName_PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID         PersonalAccessTokenFieldName = 3
	PersonalAccessTokenFieldName_PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID PersonalAccessTokenFieldName = 4
	PersonalAccessTokenFieldName_PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE PersonalAccessTokenFieldName = 5
)

// Enum value maps for PersonalAccessTokenFieldName.
var (
	PersonalAccessTokenFieldName_name = map[int32]string{
		0: "PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED",
		1: "PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE",
		2: "PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID",
		3: "PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID",
		4: "PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID",
		5: "PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE",
	}
	PersonalAccessTokenFieldName_value = map[string]int32{
		"PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED":     0,
		"PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE":    1,
		"PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID":              2,
		"PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID":         3,
		"PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID": 4,
		"PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE": 5,
	}
)

func (x PersonalAccessTokenFieldName) Enum() *PersonalAccessTokenFieldName {
	p := new(PersonalAccessTokenFieldName)
	*p = x
	return p
}

func (x PersonalAccessTokenFieldName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonalAccessTokenFieldName) Descriptor() protoreflect.EnumDescriptor {
	return file_zitadel_user_v2_pat_proto_enumTypes[0].Descriptor()
}

func (PersonalAccessTokenFieldName) Type() protoreflect.EnumType {
	return &file_zitadel_user_v2_pat_proto_enumTypes[0]
}

func (x PersonalAccessTokenFieldName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonalAccessTokenFieldName.Descriptor instead.
func (PersonalAccessTokenFieldName) EnumDescriptor() ([]byte, []int) {
	return file_zitadel_user_v2_pat_proto_rawDescGZIP(), []int{0}
}

type PersonalAccessToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp of the personal access token creation.
	CreationDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// The timestamp of the last change of the personal access token.
	ChangeDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=change_date,json=changeDate,proto3" json:"change_date,omitempty"`
	// The unique identifier of the personal access token.
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// The unique identifier of the user the personal access token belongs to.
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The unique identifier of the organization the personal access token belongs to.
	OrganizationId string `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// The personal access tokens expiration date.
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersonalAccessToken) Reset() {
	*x = PersonalAccessToken{}
	mi := &file_zitadel_user_v2_pat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalAccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalAccessToken) ProtoMessage() {}

func (x *PersonalAccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2_pat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalAccessToken.ProtoReflect.Descriptor instead.
func (*PersonalAccessToken) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2_pat_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalAccessToken) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *PersonalAccessToken) GetChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeDate
	}
	return nil
}

func (x *PersonalAccessToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonalAccessToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PersonalAccessToken) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *PersonalAccessToken) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

type PersonalAccessTokensSearchFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Filter:
	//
	//	*PersonalAccessTokensSearchFilter_TokenIdFilter
	//	*PersonalAccessTokensSearchFilter_UserIdFilter
	//	*PersonalAccessTokensSearchFilter_OrganizationIdFilter
	//	*PersonalAccessTokensSearchFilter_CreatedDateFilter
	//	*PersonalAccessTokensSearchFilter_ExpirationDateFilter
	Filter        isPersonalAccessTokensSearchFilter_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalAccessTokensSearchFilter) Reset() {
	*x = PersonalAccessTokensSearchFilter{}
	mi := &file_zitadel_user_v2_pat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalAccessTokensSearchFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalAccessTokensSearchFilter) ProtoMessage() {}

func (x *PersonalAccessTokensSearchFilter) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_user_v2_pat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalAccessTokensSearchFilter.ProtoReflect.Descriptor instead.
func (*PersonalAccessTokensSearchFilter) Descriptor() ([]byte, []int) {
	return file_zitadel_user_v2_pat_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalAccessTokensSearchFilter) GetFilter() isPersonalAccessTokensSearchFilter_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *PersonalAccessTokensSearchFilter) GetTokenIdFilter() *v2.IDFilter {
	if x != nil {
		if x, ok := x.Filter.(*PersonalAccessTokensSearchFilter_TokenIdFilter); ok {
			return x.TokenIdFilter
		}
	}
	return nil
}

func (x *PersonalAccessTokensSearchFilter) GetUserIdFilter() *v2.IDFilter {
	if x != nil {
		if x, ok := x.Filter.(*PersonalAccessTokensSearchFilter_UserIdFilter); ok {
			return x.UserIdFilter
		}
	}
	return nil
}

func (x *PersonalAccessTokensSearchFilter) GetOrganizationIdFilter() *v2.IDFilter {
	if x != nil {
		if x, ok := x.Filter.(*PersonalAccessTokensSearchFilter_OrganizationIdFilter); ok {
			return x.OrganizationIdFilter
		}
	}
	return nil
}

func (x *PersonalAccessTokensSearchFilter) GetCreatedDateFilter() *v2.TimestampFilter {
	if x != nil {
		if x, ok := x.Filter.(*PersonalAccessTokensSearchFilter_CreatedDateFilter); ok {
			return x.CreatedDateFilter
		}
	}
	return nil
}

func (x *PersonalAccessTokensSearchFilter) GetExpirationDateFilter() *v2.TimestampFilter {
	if x != nil {
		if x, ok := x.Filter.(*PersonalAccessTokensSearchFilter_ExpirationDateFilter); ok {
			return x.ExpirationDateFilter
		}
	}
	return nil
}

type isPersonalAccessTokensSearchFilter_Filter interface {
	isPersonalAccessTokensSearchFilter_Filter()
}

type PersonalAccessTokensSearchFilter_TokenIdFilter struct {
	TokenIdFilter *v2.IDFilter `protobuf:"bytes,1,opt,name=token_id_filter,json=tokenIdFilter,proto3,oneof"`
}

type PersonalAccessTokensSearchFilter_UserIdFilter struct {
	UserIdFilter *v2.IDFilter `protobuf:"bytes,2,opt,name=user_id_filter,json=userIdFilter,proto3,oneof"`
}

type PersonalAccessTokensSearchFilter_OrganizationIdFilter struct {
	OrganizationIdFilter *v2.IDFilter `protobuf:"bytes,3,opt,name=organization_id_filter,json=organizationIdFilter,proto3,oneof"`
}

type PersonalAccessTokensSearchFilter_CreatedDateFilter struct {
	CreatedDateFilter *v2.TimestampFilter `protobuf:"bytes,4,opt,name=created_date_filter,json=createdDateFilter,proto3,oneof"`
}

type PersonalAccessTokensSearchFilter_ExpirationDateFilter struct {
	ExpirationDateFilter *v2.TimestampFilter `protobuf:"bytes,5,opt,name=expiration_date_filter,json=expirationDateFilter,proto3,oneof"`
}

func (*PersonalAccessTokensSearchFilter_TokenIdFilter) isPersonalAccessTokensSearchFilter_Filter() {}

func (*PersonalAccessTokensSearchFilter_UserIdFilter) isPersonalAccessTokensSearchFilter_Filter() {}

func (*PersonalAccessTokensSearchFilter_OrganizationIdFilter) isPersonalAccessTokensSearchFilter_Filter() {
}

func (*PersonalAccessTokensSearchFilter_CreatedDateFilter) isPersonalAccessTokensSearchFilter_Filter() {
}

func (*PersonalAccessTokensSearchFilter_ExpirationDateFilter) isPersonalAccessTokensSearchFilter_Filter() {
}

var File_zitadel_user_v2_pat_proto protoreflect.FileDescriptor

const file_zitadel_user_v2_pat_proto_rawDesc = "" +
	"\n" +
	"\x19zitadel/user/v2/pat.proto\x12\x0fzitadel.user.v2\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x1ezitadel/filter/v2/filter.proto\"\xdb\x03\n" +
	"\x13PersonalAccessToken\x12`\n" +
	"\rcreation_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2024-12-18T07:50:47.492Z\"R\fcreationDate\x12\\\n" +
	"\vchange_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2024-12-18T07:50:47.492Z\"R\n" +
	"changeDate\x12(\n" +
	"\x02id\x18\x03 \x01(\tB\x18\x92A\x15J\x13\"69629012906488334\"R\x02id\x121\n" +
	"\auser_id\x18\x04 \x01(\tB\x18\x92A\x15J\x13\"69629012906488334\"R\x06userId\x12A\n" +
	"\x0forganization_id\x18\x05 \x01(\tB\x18\x92A\x15J\x13\"69629012906488334\"R\x0eorganizationId\x12d\n" +
	"\x0fexpiration_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2024-12-18T07:50:47.492Z\"R\x0eexpirationDate\"\xc4\x03\n" +
	" PersonalAccessTokensSearchFilter\x12E\n" +
	"\x0ftoken_id_filter\x18\x01 \x01(\v2\x1b.zitadel.filter.v2.IDFilterH\x00R\rtokenIdFilter\x12C\n" +
	"\x0euser_id_filter\x18\x02 \x01(\v2\x1b.zitadel.filter.v2.IDFilterH\x00R\fuserIdFilter\x12S\n" +
	"\x16organization_id_filter\x18\x03 \x01(\v2\x1b.zitadel.filter.v2.IDFilterH\x00R\x14organizationIdFilter\x12T\n" +
	"\x13created_date_filter\x18\x04 \x01(\v2\".zitadel.filter.v2.TimestampFilterH\x00R\x11createdDateFilter\x12Z\n" +
	"\x16expiration_date_filter\x18\x05 \x01(\v2\".zitadel.filter.v2.TimestampFilterH\x00R\x14expirationDateFilterB\r\n" +
	"\x06filter\x12\x03\xf8B\x01*\xc6\x02\n" +
	"\x1cPersonalAccessTokenFieldName\x120\n" +
	",PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED\x10\x00\x121\n" +
	"-PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE\x10\x01\x12'\n" +
	"#PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID\x10\x02\x12,\n" +
	"(PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID\x10\x03\x124\n" +
	"0PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID\x10\x04\x124\n" +
	"0PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE\x10\x05B2Z0github.com/zitadel/zitadel/pkg/grpc/user/v2;userb\x06proto3"

var (
	file_zitadel_user_v2_pat_proto_rawDescOnce sync.Once
	file_zitadel_user_v2_pat_proto_rawDescData []byte
)

func file_zitadel_user_v2_pat_proto_rawDescGZIP() []byte {
	file_zitadel_user_v2_pat_proto_rawDescOnce.Do(func() {
		file_zitadel_user_v2_pat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_user_v2_pat_proto_rawDesc), len(file_zitadel_user_v2_pat_proto_rawDesc)))
	})
	return file_zitadel_user_v2_pat_proto_rawDescData
}

var file_zitadel_user_v2_pat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zitadel_user_v2_pat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zitadel_user_v2_pat_proto_goTypes = []any{
	(PersonalAccessTokenFieldName)(0),        // 0: zitadel.user.v2.PersonalAccessTokenFieldName
	(*PersonalAccessToken)(nil),              // 1: zitadel.user.v2.PersonalAccessToken
	(*PersonalAccessTokensSearchFilter)(nil), // 2: zitadel.user.v2.PersonalAccessTokensSearchFilter
	(*timestamppb.Timestamp)(nil),            // 3: google.protobuf.Timestamp
	(*v2.IDFilter)(nil),                      // 4: zitadel.filter.v2.IDFilter
	(*v2.TimestampFilter)(nil),               // 5: zitadel.filter.v2.TimestampFilter
}
var file_zitadel_user_v2_pat_proto_depIdxs = []int32{
	3, // 0: zitadel.user.v2.PersonalAccessToken.creation_date:type_name -> google.protobuf.Timestamp
	3, // 1: zitadel.user.v2.PersonalAccessToken.change_date:type_name -> google.protobuf.Timestamp
	3, // 2: zitadel.user.v2.PersonalAccessToken.expiration_date:type_name -> google.protobuf.Timestamp
	4, // 3: zitadel.user.v2.PersonalAccessTokensSearchFilter.token_id_filter:type_name -> zitadel.filter.v2.IDFilter
	4, // 4: zitadel.user.v2.PersonalAccessTokensSearchFilter.user_id_filter:type_name -> zitadel.filter.v2.IDFilter
	4, // 5: zitadel.user.v2.PersonalAccessTokensSearchFilter.organization_id_filter:type_name -> zitadel.filter.v2.IDFilter
	5, // 6: zitadel.user.v2.PersonalAccessTokensSearchFilter.created_date_filter:type_name -> zitadel.filter.v2.TimestampFilter
	5, // 7: zitadel.user.v2.PersonalAccessTokensSearchFilter.expiration_date_filter:type_name -> zitadel.filter.v2.TimestampFilter
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_zitadel_user_v2_pat_proto_init() }
func file_zitadel_user_v2_pat_proto_init() {
	if File_zitadel_user_v2_pat_proto != nil {
		return
	}
	file_zitadel_user_v2_pat_proto_msgTypes[1].OneofWrappers = []any{
		(*PersonalAccessTokensSearchFilter_TokenIdFilter)(nil),
		(*PersonalAccessTokensSearchFilter_UserIdFilter)(nil),
		(*PersonalAccessTokensSearchFilter_OrganizationIdFilter)(nil),
		(*PersonalAccessTokensSearchFilter_CreatedDateFilter)(nil),
		(*PersonalAccessTokensSearchFilter_ExpirationDateFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_user_v2_pat_proto_rawDesc), len(file_zitadel_user_v2_pat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zitadel_user_v2_pat_proto_goTypes,
		DependencyIndexes: file_zitadel_user_v2_pat_proto_depIdxs,
		EnumInfos:         file_zitadel_user_v2_pat_proto_enumTypes,
		MessageInfos:      file_zitadel_user_v2_pat_proto_msgTypes,
	}.Build()
	File_zitadel_user_v2_pat_proto = out.File
	file_zitadel_user_v2_pat_proto_goTypes = nil
	file_zitadel_user_v2_pat_proto_depIdxs = nil
}
