// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: zitadel/org/v2beta/org.proto

package org

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	object "github.com/zitadel/zitadel/pkg/grpc/object/v2beta"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = object.TextQueryMethod(0)
)

// Validate checks the field values on Organization with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Organization) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Organization with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrganizationMultiError, or
// nil if none found.
func (m *Organization) ValidateAll() error {
	return m.validate(true)
}

func (m *Organization) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetCreationDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrganizationValidationError{
					field:  "CreationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrganizationValidationError{
					field:  "CreationDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreationDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrganizationValidationError{
				field:  "CreationDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetChangedDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrganizationValidationError{
					field:  "ChangedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrganizationValidationError{
					field:  "ChangedDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetChangedDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrganizationValidationError{
				field:  "ChangedDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for State

	// no validation rules for Name

	// no validation rules for PrimaryDomain

	if len(errors) > 0 {
		return OrganizationMultiError(errors)
	}

	return nil
}

// OrganizationMultiError is an error wrapping multiple validation errors
// returned by Organization.ValidateAll() if the designated constraints aren't met.
type OrganizationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationMultiError) AllErrors() []error { return m }

// OrganizationValidationError is the validation error returned by
// Organization.Validate if the designated constraints aren't met.
type OrganizationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationValidationError) ErrorName() string { return "OrganizationValidationError" }

// Error satisfies the builtin error interface
func (e OrganizationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganization.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationValidationError{}

// Validate checks the field values on OrganizationSearchFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrganizationSearchFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrganizationSearchFilter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrganizationSearchFilterMultiError, or nil if none found.
func (m *OrganizationSearchFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *OrganizationSearchFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofFilterPresent := false
	switch v := m.Filter.(type) {
	case *OrganizationSearchFilter_NameFilter:
		if v == nil {
			err := OrganizationSearchFilterValidationError{
				field:  "Filter",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFilterPresent = true

		if all {
			switch v := interface{}(m.GetNameFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "NameFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "NameFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetNameFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrganizationSearchFilterValidationError{
					field:  "NameFilter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *OrganizationSearchFilter_DomainFilter:
		if v == nil {
			err := OrganizationSearchFilterValidationError{
				field:  "Filter",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFilterPresent = true

		if all {
			switch v := interface{}(m.GetDomainFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "DomainFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "DomainFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDomainFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrganizationSearchFilterValidationError{
					field:  "DomainFilter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *OrganizationSearchFilter_StateFilter:
		if v == nil {
			err := OrganizationSearchFilterValidationError{
				field:  "Filter",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFilterPresent = true

		if all {
			switch v := interface{}(m.GetStateFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "StateFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "StateFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetStateFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrganizationSearchFilterValidationError{
					field:  "StateFilter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *OrganizationSearchFilter_IdFilter:
		if v == nil {
			err := OrganizationSearchFilterValidationError{
				field:  "Filter",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFilterPresent = true

		if all {
			switch v := interface{}(m.GetIdFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "IdFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrganizationSearchFilterValidationError{
						field:  "IdFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetIdFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrganizationSearchFilterValidationError{
					field:  "IdFilter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofFilterPresent {
		err := OrganizationSearchFilterValidationError{
			field:  "Filter",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrganizationSearchFilterMultiError(errors)
	}

	return nil
}

// OrganizationSearchFilterMultiError is an error wrapping multiple validation
// errors returned by OrganizationSearchFilter.ValidateAll() if the designated
// constraints aren't met.
type OrganizationSearchFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrganizationSearchFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrganizationSearchFilterMultiError) AllErrors() []error { return m }

// OrganizationSearchFilterValidationError is the validation error returned by
// OrganizationSearchFilter.Validate if the designated constraints aren't met.
type OrganizationSearchFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrganizationSearchFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrganizationSearchFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrganizationSearchFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrganizationSearchFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrganizationSearchFilterValidationError) ErrorName() string {
	return "OrganizationSearchFilterValidationError"
}

// Error satisfies the builtin error interface
func (e OrganizationSearchFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrganizationSearchFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrganizationSearchFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrganizationSearchFilterValidationError{}

// Validate checks the field values on OrgNameFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrgNameFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrgNameFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrgNameFilterMultiError, or
// nil if none found.
func (m *OrgNameFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *OrgNameFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) > 200 {
		err := OrgNameFilterValidationError{
			field:  "Name",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := OrgNameFilterValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrgNameFilterMultiError(errors)
	}

	return nil
}

// OrgNameFilterMultiError is an error wrapping multiple validation errors
// returned by OrgNameFilter.ValidateAll() if the designated constraints
// aren't met.
type OrgNameFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgNameFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgNameFilterMultiError) AllErrors() []error { return m }

// OrgNameFilterValidationError is the validation error returned by
// OrgNameFilter.Validate if the designated constraints aren't met.
type OrgNameFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgNameFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgNameFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgNameFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgNameFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgNameFilterValidationError) ErrorName() string { return "OrgNameFilterValidationError" }

// Error satisfies the builtin error interface
func (e OrgNameFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrgNameFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgNameFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgNameFilterValidationError{}

// Validate checks the field values on OrgDomainFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *OrgDomainFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrgDomainFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrgDomainFilterMultiError, or nil if none found.
func (m *OrgDomainFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *OrgDomainFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDomain()) > 200 {
		err := OrgDomainFilterValidationError{
			field:  "Domain",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := OrgDomainFilterValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrgDomainFilterMultiError(errors)
	}

	return nil
}

// OrgDomainFilterMultiError is an error wrapping multiple validation errors
// returned by OrgDomainFilter.ValidateAll() if the designated constraints
// aren't met.
type OrgDomainFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgDomainFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgDomainFilterMultiError) AllErrors() []error { return m }

// OrgDomainFilterValidationError is the validation error returned by
// OrgDomainFilter.Validate if the designated constraints aren't met.
type OrgDomainFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgDomainFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgDomainFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgDomainFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgDomainFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgDomainFilterValidationError) ErrorName() string { return "OrgDomainFilterValidationError" }

// Error satisfies the builtin error interface
func (e OrgDomainFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrgDomainFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgDomainFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgDomainFilterValidationError{}

// Validate checks the field values on OrgStateFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrgStateFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrgStateFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrgStateFilterMultiError,
// or nil if none found.
func (m *OrgStateFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *OrgStateFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := OrgState_name[int32(m.GetState())]; !ok {
		err := OrgStateFilterValidationError{
			field:  "State",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrgStateFilterMultiError(errors)
	}

	return nil
}

// OrgStateFilterMultiError is an error wrapping multiple validation errors
// returned by OrgStateFilter.ValidateAll() if the designated constraints
// aren't met.
type OrgStateFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgStateFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgStateFilterMultiError) AllErrors() []error { return m }

// OrgStateFilterValidationError is the validation error returned by
// OrgStateFilter.Validate if the designated constraints aren't met.
type OrgStateFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgStateFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgStateFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgStateFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgStateFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgStateFilterValidationError) ErrorName() string { return "OrgStateFilterValidationError" }

// Error satisfies the builtin error interface
func (e OrgStateFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrgStateFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgStateFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgStateFilterValidationError{}

// Validate checks the field values on OrgIDFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrgIDFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrgIDFilter with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrgIDFilterMultiError, or
// nil if none found.
func (m *OrgIDFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *OrgIDFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) > 200 {
		err := OrgIDFilterValidationError{
			field:  "Id",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrgIDFilterMultiError(errors)
	}

	return nil
}

// OrgIDFilterMultiError is an error wrapping multiple validation errors
// returned by OrgIDFilter.ValidateAll() if the designated constraints aren't met.
type OrgIDFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrgIDFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrgIDFilterMultiError) AllErrors() []error { return m }

// OrgIDFilterValidationError is the validation error returned by
// OrgIDFilter.Validate if the designated constraints aren't met.
type OrgIDFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgIDFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgIDFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgIDFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgIDFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgIDFilterValidationError) ErrorName() string { return "OrgIDFilterValidationError" }

// Error satisfies the builtin error interface
func (e OrgIDFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrgIDFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgIDFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgIDFilterValidationError{}

// Validate checks the field values on DomainSearchFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DomainSearchFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainSearchFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DomainSearchFilterMultiError, or nil if none found.
func (m *DomainSearchFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainSearchFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	oneofFilterPresent := false
	switch v := m.Filter.(type) {
	case *DomainSearchFilter_DomainNameFilter:
		if v == nil {
			err := DomainSearchFilterValidationError{
				field:  "Filter",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		oneofFilterPresent = true

		if all {
			switch v := interface{}(m.GetDomainNameFilter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DomainSearchFilterValidationError{
						field:  "DomainNameFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DomainSearchFilterValidationError{
						field:  "DomainNameFilter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDomainNameFilter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DomainSearchFilterValidationError{
					field:  "DomainNameFilter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}
	if !oneofFilterPresent {
		err := DomainSearchFilterValidationError{
			field:  "Filter",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DomainSearchFilterMultiError(errors)
	}

	return nil
}

// DomainSearchFilterMultiError is an error wrapping multiple validation errors
// returned by DomainSearchFilter.ValidateAll() if the designated constraints
// aren't met.
type DomainSearchFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainSearchFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainSearchFilterMultiError) AllErrors() []error { return m }

// DomainSearchFilterValidationError is the validation error returned by
// DomainSearchFilter.Validate if the designated constraints aren't met.
type DomainSearchFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainSearchFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainSearchFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainSearchFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainSearchFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainSearchFilterValidationError) ErrorName() string {
	return "DomainSearchFilterValidationError"
}

// Error satisfies the builtin error interface
func (e DomainSearchFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainSearchFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainSearchFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainSearchFilterValidationError{}

// Validate checks the field values on DomainNameFilter with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DomainNameFilter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DomainNameFilter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DomainNameFilterMultiError, or nil if none found.
func (m *DomainNameFilter) ValidateAll() error {
	return m.validate(true)
}

func (m *DomainNameFilter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) > 200 {
		err := DomainNameFilterValidationError{
			field:  "Name",
			reason: "value length must be at most 200 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := object.TextQueryMethod_name[int32(m.GetMethod())]; !ok {
		err := DomainNameFilterValidationError{
			field:  "Method",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DomainNameFilterMultiError(errors)
	}

	return nil
}

// DomainNameFilterMultiError is an error wrapping multiple validation errors
// returned by DomainNameFilter.ValidateAll() if the designated constraints
// aren't met.
type DomainNameFilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainNameFilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainNameFilterMultiError) AllErrors() []error { return m }

// DomainNameFilterValidationError is the validation error returned by
// DomainNameFilter.Validate if the designated constraints aren't met.
type DomainNameFilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainNameFilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainNameFilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainNameFilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainNameFilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainNameFilterValidationError) ErrorName() string { return "DomainNameFilterValidationError" }

// Error satisfies the builtin error interface
func (e DomainNameFilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomainNameFilter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainNameFilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainNameFilterValidationError{}

// Validate checks the field values on Domain with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Domain) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Domain with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DomainMultiError, or nil if none found.
func (m *Domain) ValidateAll() error {
	return m.validate(true)
}

func (m *Domain) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrganizationId

	// no validation rules for DomainName

	// no validation rules for IsVerified

	// no validation rules for IsPrimary

	// no validation rules for ValidationType

	if len(errors) > 0 {
		return DomainMultiError(errors)
	}

	return nil
}

// DomainMultiError is an error wrapping multiple validation errors returned by
// Domain.ValidateAll() if the designated constraints aren't met.
type DomainMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DomainMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DomainMultiError) AllErrors() []error { return m }

// DomainValidationError is the validation error returned by Domain.Validate if
// the designated constraints aren't met.
type DomainValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DomainValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DomainValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DomainValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DomainValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DomainValidationError) ErrorName() string { return "DomainValidationError" }

// Error satisfies the builtin error interface
func (e DomainValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDomain.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DomainValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DomainValidationError{}
