// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zitadel/action/v2/action_service.proto

package action

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v2 "github.com/zitadel/zitadel/pkg/grpc/filter/v2"
	_ "github.com/zitadel/zitadel/pkg/grpc/protoc/v2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Defines the target type and how the response of the target is treated.
	//
	// Types that are valid to be assigned to TargetType:
	//
	//	*CreateTargetRequest_RestWebhook
	//	*CreateTargetRequest_RestCall
	//	*CreateTargetRequest_RestAsync
	TargetType isCreateTargetRequest_TargetType `protobuf_oneof:"target_type"`
	// Timeout defines the duration until ZITADEL cancels the execution.
	// If the target doesn't respond before this timeout expires, then the connection is closed and the action fails.
	// Depending on the target type and possible setting on `interrupt_on_error` following targets will not be called.
	// In case of a `rest_async` target only this specific target will fail, without any influence on other targets of the same execution.
	// The maximum timeout is 270 seconds or 4.5 minutes.
	Timeout *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// The URL of the endpoint to call.
	Endpoint      string `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTargetRequest) Reset() {
	*x = CreateTargetRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetRequest) ProtoMessage() {}

func (x *CreateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetRequest.ProtoReflect.Descriptor instead.
func (*CreateTargetRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTargetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTargetRequest) GetTargetType() isCreateTargetRequest_TargetType {
	if x != nil {
		return x.TargetType
	}
	return nil
}

func (x *CreateTargetRequest) GetRestWebhook() *RESTWebhook {
	if x != nil {
		if x, ok := x.TargetType.(*CreateTargetRequest_RestWebhook); ok {
			return x.RestWebhook
		}
	}
	return nil
}

func (x *CreateTargetRequest) GetRestCall() *RESTCall {
	if x != nil {
		if x, ok := x.TargetType.(*CreateTargetRequest_RestCall); ok {
			return x.RestCall
		}
	}
	return nil
}

func (x *CreateTargetRequest) GetRestAsync() *RESTAsync {
	if x != nil {
		if x, ok := x.TargetType.(*CreateTargetRequest_RestAsync); ok {
			return x.RestAsync
		}
	}
	return nil
}

func (x *CreateTargetRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *CreateTargetRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type isCreateTargetRequest_TargetType interface {
	isCreateTargetRequest_TargetType()
}

type CreateTargetRequest_RestWebhook struct {
	// The HTTP call to this target will be a POST request.
	// The response of the target will only be checked for the status code.
	// The returned body will be ignored.
	// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
	// the execution will be aborted and no further targets will be called.
	RestWebhook *RESTWebhook `protobuf:"bytes,2,opt,name=rest_webhook,json=restWebhook,proto3,oneof"`
}

type CreateTargetRequest_RestCall struct {
	// The HTTP call to this target will be a POST request.
	// The response of the target will be checked for the status code and the body.
	// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
	// the execution will be aborted and no further targets will be called.
	// In case of a successful status code (2xx) the body will be parsed and mapped.
	// This allows to modify the payload of request and response executions.
	RestCall *RESTCall `protobuf:"bytes,3,opt,name=rest_call,json=restCall,proto3,oneof"`
}

type CreateTargetRequest_RestAsync struct {
	// The HTTP call to this target will be a POST request.
	// The call is sent asynchronously and ZITADEL does not wait for the response.
	// The response of the target is ignored, no status or body is checked.
	// This is typically used for executions of type "events".
	RestAsync *RESTAsync `protobuf:"bytes,4,opt,name=rest_async,json=restAsync,proto3,oneof"`
}

func (*CreateTargetRequest_RestWebhook) isCreateTargetRequest_TargetType() {}

func (*CreateTargetRequest_RestCall) isCreateTargetRequest_TargetType() {}

func (*CreateTargetRequest_RestAsync) isCreateTargetRequest_TargetType() {}

type CreateTargetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the newly created target.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The timestamp of the target creation.
	CreationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// Key used to sign and check payload sent to the target.
	// The key can be used to verify the integrity and authenticity of the request
	// on the receiver side. The key should be treated as a secret and only known to ZITADEL and the receiver.
	// The signature is included in the request header `X-ZITADEL-Signature`
	// and calculated over the raw body of the request using HMAC with SHA256.
	SigningKey    string `protobuf:"bytes,3,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTargetResponse) Reset() {
	*x = CreateTargetResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTargetResponse) ProtoMessage() {}

func (x *CreateTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTargetResponse.ProtoReflect.Descriptor instead.
func (*CreateTargetResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTargetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTargetResponse) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *CreateTargetResponse) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

type UpdateTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Optionally, update the name of the target.
	// If not set, the name will not be changed.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Defines the target type and how the response of the target is treated.
	//
	// Types that are valid to be assigned to TargetType:
	//
	//	*UpdateTargetRequest_RestWebhook
	//	*UpdateTargetRequest_RestCall
	//	*UpdateTargetRequest_RestAsync
	TargetType isUpdateTargetRequest_TargetType `protobuf_oneof:"target_type"`
	// Timeout defines the duration until ZITADEL cancels the execution.
	// If the target doesn't respond before this timeout expires, then the connection is closed and the action fails.
	// Depending on the target type and possible setting on `interrupt_on_error` following targets will not be called.
	// In case of a `rest_async` target only this specific target will fail, without any influence on other targets of the same execution.
	// The maximum timeout is 270 seconds or 4.5 minutes.
	// If not set, the timeout will not be changed.
	Timeout *durationpb.Duration `protobuf:"bytes,6,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	// The new URL of the endpoint to call.
	// If not set, the endpoint will not be changed.
	Endpoint *string `protobuf:"bytes,7,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	// Regenerate the key used for signing and checking the payload sent to the target.
	// Set the graceful period for the existing key. During that time, the previous
	// signing key and the new one will be used to sign the request to allow you a smooth
	// transition onf your API.
	//
	// Note that we currently only allow an immediate rotation ("0s") and will support
	// longer expirations in the future.
	ExpirationSigningKey *durationpb.Duration `protobuf:"bytes,8,opt,name=expiration_signing_key,json=expirationSigningKey,proto3,oneof" json:"expiration_signing_key,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTargetRequest) Reset() {
	*x = UpdateTargetRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetRequest) ProtoMessage() {}

func (x *UpdateTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetRequest.ProtoReflect.Descriptor instead.
func (*UpdateTargetRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTargetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTargetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTargetRequest) GetTargetType() isUpdateTargetRequest_TargetType {
	if x != nil {
		return x.TargetType
	}
	return nil
}

func (x *UpdateTargetRequest) GetRestWebhook() *RESTWebhook {
	if x != nil {
		if x, ok := x.TargetType.(*UpdateTargetRequest_RestWebhook); ok {
			return x.RestWebhook
		}
	}
	return nil
}

func (x *UpdateTargetRequest) GetRestCall() *RESTCall {
	if x != nil {
		if x, ok := x.TargetType.(*UpdateTargetRequest_RestCall); ok {
			return x.RestCall
		}
	}
	return nil
}

func (x *UpdateTargetRequest) GetRestAsync() *RESTAsync {
	if x != nil {
		if x, ok := x.TargetType.(*UpdateTargetRequest_RestAsync); ok {
			return x.RestAsync
		}
	}
	return nil
}

func (x *UpdateTargetRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *UpdateTargetRequest) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *UpdateTargetRequest) GetExpirationSigningKey() *durationpb.Duration {
	if x != nil {
		return x.ExpirationSigningKey
	}
	return nil
}

type isUpdateTargetRequest_TargetType interface {
	isUpdateTargetRequest_TargetType()
}

type UpdateTargetRequest_RestWebhook struct {
	// The HTTP call to this target will be a POST request.
	// The response of the target will only be checked for the status code.
	// The returned body will be ignored.
	// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
	// the execution will be aborted and no further targets will be called.
	RestWebhook *RESTWebhook `protobuf:"bytes,3,opt,name=rest_webhook,json=restWebhook,proto3,oneof"`
}

type UpdateTargetRequest_RestCall struct {
	// The HTTP call to this target will be a POST request.
	// The response of the target will be checked for the status code and the body.
	// In case of an error status code (non 2xx) and interrupt_on_error is set to true,
	// the execution will be aborted and no further targets will be called.
	// In case of a successful status code (2xx) the body will be parsed and mapped.
	// This allows to modify the payload of request and response executions.
	RestCall *RESTCall `protobuf:"bytes,4,opt,name=rest_call,json=restCall,proto3,oneof"`
}

type UpdateTargetRequest_RestAsync struct {
	// The HTTP call to this target will be a POST request.
	// The call is sent asynchronously and ZITADEL does not wait for the response.
	// The response of the target is ignored, no status or body is checked.
	// This is typically used for executions of type "events".
	RestAsync *RESTAsync `protobuf:"bytes,5,opt,name=rest_async,json=restAsync,proto3,oneof"`
}

func (*UpdateTargetRequest_RestWebhook) isUpdateTargetRequest_TargetType() {}

func (*UpdateTargetRequest_RestCall) isUpdateTargetRequest_TargetType() {}

func (*UpdateTargetRequest_RestAsync) isUpdateTargetRequest_TargetType() {}

type UpdateTargetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp of the change of the target.
	ChangeDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=change_date,json=changeDate,proto3" json:"change_date,omitempty"`
	// Key used to sign and check payload sent to the target.
	// The key can be used to verify the integrity and authenticity of the request
	// on the receiver side. The key should be treated as a secret and only known to ZITADEL and the receiver.
	// The signature is included in the request header `X-ZITADEL-Signature`
	// and calculated over the raw body of the request using HMAC with SHA256.
	// The key is only returned if expirationSigningKey was set in the request.
	SigningKey    *string `protobuf:"bytes,2,opt,name=signing_key,json=signingKey,proto3,oneof" json:"signing_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTargetResponse) Reset() {
	*x = UpdateTargetResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTargetResponse) ProtoMessage() {}

func (x *UpdateTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTargetResponse.ProtoReflect.Descriptor instead.
func (*UpdateTargetResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTargetResponse) GetChangeDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeDate
	}
	return nil
}

func (x *UpdateTargetResponse) GetSigningKey() string {
	if x != nil && x.SigningKey != nil {
		return *x.SigningKey
	}
	return ""
}

type DeleteTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetRequest) Reset() {
	*x = DeleteTargetRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetRequest) ProtoMessage() {}

func (x *DeleteTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTargetRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTargetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTargetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp of the deletion of the target.
	// Note that the deletion date is only guaranteed to be set if the deletion was successful during the request.
	// In case the deletion occurred in a previous request, the deletion date might be empty.
	DeletionDate  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deletion_date,json=deletionDate,proto3" json:"deletion_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTargetResponse) Reset() {
	*x = DeleteTargetResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTargetResponse) ProtoMessage() {}

func (x *DeleteTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTargetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTargetResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTargetResponse) GetDeletionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionDate
	}
	return nil
}

type GetTargetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the target to retrieve.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetRequest) Reset() {
	*x = GetTargetRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetRequest) ProtoMessage() {}

func (x *GetTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetRequest.ProtoReflect.Descriptor instead.
func (*GetTargetRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTargetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Target                `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetResponse) Reset() {
	*x = GetTargetResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetResponse) ProtoMessage() {}

func (x *GetTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetResponse.ProtoReflect.Descriptor instead.
func (*GetTargetResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTargetResponse) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

type ListTargetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List limitations and ordering.
	Pagination *v2.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	// The field the result is sorted by. The default is the creation date. Beware that if you change this, your result pagination might be inconsistent.
	SortingColumn *TargetFieldName `protobuf:"varint,2,opt,name=sorting_column,json=sortingColumn,proto3,enum=zitadel.action.v2.TargetFieldName,oneof" json:"sorting_column,omitempty"`
	// Define the criteria to query for.
	Filters       []*TargetSearchFilter `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetsRequest) Reset() {
	*x = ListTargetsRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsRequest) ProtoMessage() {}

func (x *ListTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetsRequest.ProtoReflect.Descriptor instead.
func (*ListTargetsRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListTargetsRequest) GetPagination() *v2.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTargetsRequest) GetSortingColumn() TargetFieldName {
	if x != nil && x.SortingColumn != nil {
		return *x.SortingColumn
	}
	return TargetFieldName_TARGET_FIELD_NAME_UNSPECIFIED
}

func (x *ListTargetsRequest) GetFilters() []*TargetSearchFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListTargetsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *v2.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// List of all targets matching the query.
	Targets       []*Target `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTargetsResponse) Reset() {
	*x = ListTargetsResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsResponse) ProtoMessage() {}

func (x *ListTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTargetsResponse.ProtoReflect.Descriptor instead.
func (*ListTargetsResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTargetsResponse) GetPagination() *v2.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTargetsResponse) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

type SetExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Condition defining when the execution should be used.
	Condition *Condition `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	// Ordered list of targets called during the execution.
	Targets       []string `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExecutionRequest) Reset() {
	*x = SetExecutionRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExecutionRequest) ProtoMessage() {}

func (x *SetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExecutionRequest.ProtoReflect.Descriptor instead.
func (*SetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{10}
}

func (x *SetExecutionRequest) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *SetExecutionRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type SetExecutionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp of the execution set.
	SetDate       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=set_date,json=setDate,proto3" json:"set_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExecutionResponse) Reset() {
	*x = SetExecutionResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExecutionResponse) ProtoMessage() {}

func (x *SetExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExecutionResponse.ProtoReflect.Descriptor instead.
func (*SetExecutionResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{11}
}

func (x *SetExecutionResponse) GetSetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SetDate
	}
	return nil
}

type ListExecutionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List limitations and ordering.
	Pagination *v2.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	// The field the result is sorted by. The default is the creation date.
	// Beware that if you change this, your result pagination might be inconsistent.
	SortingColumn *ExecutionFieldName `protobuf:"varint,2,opt,name=sorting_column,json=sortingColumn,proto3,enum=zitadel.action.v2.ExecutionFieldName,oneof" json:"sorting_column,omitempty"`
	// Define the criteria to query for.
	Filters       []*ExecutionSearchFilter `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListExecutionsRequest) GetPagination() *v2.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListExecutionsRequest) GetSortingColumn() ExecutionFieldName {
	if x != nil && x.SortingColumn != nil {
		return *x.SortingColumn
	}
	return ExecutionFieldName_EXECUTION_FIELD_NAME_UNSPECIFIED
}

func (x *ListExecutionsRequest) GetFilters() []*ExecutionSearchFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListExecutionsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pagination *v2.PaginationResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// List of all executions matching the query.
	Executions    []*Execution `protobuf:"bytes,2,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListExecutionsResponse) GetPagination() *v2.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListExecutionsResponse) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

type ListExecutionFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionFunctionsRequest) Reset() {
	*x = ListExecutionFunctionsRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionFunctionsRequest) ProtoMessage() {}

func (x *ListExecutionFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{14}
}

type ListExecutionFunctionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All available functions to use in conditions.
	Functions     []string `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionFunctionsResponse) Reset() {
	*x = ListExecutionFunctionsResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionFunctionsResponse) ProtoMessage() {}

func (x *ListExecutionFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListExecutionFunctionsResponse) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

type ListExecutionMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionMethodsRequest) Reset() {
	*x = ListExecutionMethodsRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionMethodsRequest) ProtoMessage() {}

func (x *ListExecutionMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionMethodsRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{16}
}

type ListExecutionMethodsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All available methods to use in conditions.
	Methods       []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionMethodsResponse) Reset() {
	*x = ListExecutionMethodsResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionMethodsResponse) ProtoMessage() {}

func (x *ListExecutionMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionMethodsResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListExecutionMethodsResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ListExecutionServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionServicesRequest) Reset() {
	*x = ListExecutionServicesRequest{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionServicesRequest) ProtoMessage() {}

func (x *ListExecutionServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionServicesRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionServicesRequest) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{18}
}

type ListExecutionServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All available services to use in conditions.
	Services      []string `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionServicesResponse) Reset() {
	*x = ListExecutionServicesResponse{}
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionServicesResponse) ProtoMessage() {}

func (x *ListExecutionServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zitadel_action_v2_action_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionServicesResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionServicesResponse) Descriptor() ([]byte, []int) {
	return file_zitadel_action_v2_action_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListExecutionServicesResponse) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_zitadel_action_v2_action_service_proto protoreflect.FileDescriptor

const file_zitadel_action_v2_action_service_proto_rawDesc = "" +
	"\n" +
	"&zitadel/action/v2/action_service.proto\x12\x11zitadel.action.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\x1a+zitadel/protoc_gen_zitadel/v2/options.proto\x1a\x1ezitadel/action/v2/target.proto\x1a!zitadel/action/v2/execution.proto\x1a\x1dzitadel/action/v2/query.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ezitadel/filter/v2/filter.proto\"\xd9\x04\n" +
	"\x13CreateTargetRequest\x12;\n" +
	"\x04name\x18\x01 \x01(\tB'\x92A\x17J\x0f\"ip_allow_list\"x\xe8\a\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xe8\aR\x04name\x12C\n" +
	"\frest_webhook\x18\x02 \x01(\v2\x1e.zitadel.action.v2.RESTWebhookH\x00R\vrestWebhook\x12:\n" +
	"\trest_call\x18\x03 \x01(\v2\x1b.zitadel.action.v2.RESTCallH\x00R\brestCall\x12=\n" +
	"\n" +
	"rest_async\x18\x04 \x01(\v2\x1c.zitadel.action.v2.RESTAsyncH\x00R\trestAsync\x12L\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationB\x17\x92A\aJ\x05\"10s\"\xfaB\n" +
	"\xaa\x01\a\"\x03\b\x8e\x022\x00R\atimeout\x12X\n" +
	"\bendpoint\x18\x06 \x01(\tB<\x92A,J$\"https://example.com/hooks/ip_check\"x\x80\x10\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\x80\x10R\bendpoint:\x88\x01\x92A\x84\x012\x81\x01{\"name\": \"ip_allow_list\",\"restWebhook\":{\"interruptOnError\":true},\"timeout\":\"10s\",\"endpoint\":\"https://example.com/hooks/ip_check\"}B\x12\n" +
	"\vtarget_type\x12\x03\xf8B\x01\"\xd4\x01\n" +
	"\x14CreateTargetResponse\x12(\n" +
	"\x02id\x18\x01 \x01(\tB\x18\x92A\x15J\x13\"69629012906488334\"R\x02id\x12`\n" +
	"\rcreation_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2024-12-18T07:50:47.492Z\"R\fcreationDate\x120\n" +
	"\vsigning_key\x18\x03 \x01(\tB\x0f\x92A\fJ\n" +
	"\"98KmsU67\"R\n" +
	"signingKey\"\xd9\x06\n" +
	"\x13UpdateTargetRequest\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A\x1bJ\x13\"69629026806489455\"x\xc8\x01\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x02id\x12=\n" +
	"\x04name\x18\x02 \x01(\tB$\x92A\x17J\x0f\"ip_allow_list\"x\xe8\a\x80\x01\x01\xfaB\ar\x05\x10\x01\x18\xe8\aH\x01R\x04name\x88\x01\x01\x12C\n" +
	"\frest_webhook\x18\x03 \x01(\v2\x1e.zitadel.action.v2.RESTWebhookH\x00R\vrestWebhook\x12:\n" +
	"\trest_call\x18\x04 \x01(\v2\x1b.zitadel.action.v2.RESTCallH\x00R\brestCall\x12=\n" +
	"\n" +
	"rest_async\x18\x05 \x01(\v2\x1c.zitadel.action.v2.RESTAsyncH\x00R\trestAsync\x12Q\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationB\x17\x92A\aJ\x05\"10s\"\xfaB\n" +
	"\xaa\x01\a\"\x03\b\x8e\x022\x00H\x02R\atimeout\x88\x01\x01\x12Z\n" +
	"\bendpoint\x18\a \x01(\tB9\x92A,J$\"https://example.com/hooks/ip_check\"x\x80\x10\x80\x01\x01\xfaB\ar\x05\x10\x01\x18\x80\x10H\x03R\bendpoint\x88\x01\x01\x12g\n" +
	"\x16expiration_signing_key\x18\b \x01(\v2\x19.google.protobuf.DurationB\x11\x92A\x06J\x04\"0s\"\xfaB\x05\xaa\x01\x02\x12\x00H\x04R\x14expirationSigningKey\x88\x01\x01:\xa1\x01\x92A\x9d\x012\x9a\x01{\"name\": \"ip_allow_list\",\"restCall\":{\"interruptOnError\":true},\"timeout\":\"10s\",\"endpoint\":\"https://example.com/hooks/ip_check\",\"expirationSigningKey\":\"0s\"}B\r\n" +
	"\vtarget_typeB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_timeoutB\v\n" +
	"\t_endpointB\x19\n" +
	"\x17_expiration_signing_key\"\xbb\x01\n" +
	"\x14UpdateTargetResponse\x12\\\n" +
	"\vchange_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2025-01-23T10:34:18.051Z\"R\n" +
	"changeDate\x125\n" +
	"\vsigning_key\x18\x02 \x01(\tB\x0f\x92A\fJ\n" +
	"\"98KmsU67\"H\x00R\n" +
	"signingKey\x88\x01\x01B\x0e\n" +
	"\f_signing_key\"R\n" +
	"\x13DeleteTargetRequest\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A\x1bJ\x13\"69629026806489455\"x\xc8\x01\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x02id\"x\n" +
	"\x14DeleteTargetResponse\x12`\n" +
	"\rdeletion_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2025-01-23T10:34:18.051Z\"R\fdeletionDate\"O\n" +
	"\x10GetTargetRequest\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A\x1bJ\x13\"69629026806489455\"x\xc8\x01\x80\x01\x01\xe0A\x02\xfaB\ar\x05\x10\x01\x18\xc8\x01R\x02id\"F\n" +
	"\x11GetTargetResponse\x121\n" +
	"\x06target\x18\x01 \x01(\v2\x19.zitadel.action.v2.TargetR\x06target\"\xd9\x04\n" +
	"\x12ListTargetsRequest\x12I\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2$.zitadel.filter.v2.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01\x12v\n" +
	"\x0esorting_column\x18\x02 \x01(\x0e2\".zitadel.action.v2.TargetFieldNameB&\x92A#:!\"TARGET_FIELD_NAME_CREATION_DATE\"H\x01R\rsortingColumn\x88\x01\x01\x12?\n" +
	"\afilters\x18\x03 \x03(\v2%.zitadel.action.v2.TargetSearchFilterR\afilters:\x9c\x02\x92A\x98\x022\x95\x02{\"pagination\":{\"offset\":0,\"limit\":0,\"asc\":true},\"sortingColumn\":\"TARGET_FIELD_NAME_CREATION_DATE\",\"filters\":[{\"targetNameFilter\":{\"targetName\":\"ip_allow_list\",\"method\":\"TEXT_FILTER_METHOD_EQUALS\"}},{\"inTargetIdsFilter\":{\"targetIds\":[\"69629023906488334\",\"69622366012355662\"]}}]}B\r\n" +
	"\v_paginationB\x11\n" +
	"\x0f_sorting_column\"\x99\x01\n" +
	"\x13ListTargetsResponse\x12E\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2%.zitadel.filter.v2.PaginationResponseR\n" +
	"pagination\x123\n" +
	"\atargets\x18\x02 \x03(\v2\x19.zitadel.action.v2.TargetR\atargetsR\x06result\"\xf5\x01\n" +
	"\x13SetExecutionRequest\x12:\n" +
	"\tcondition\x18\x01 \x01(\v2\x1c.zitadel.action.v2.ConditionR\tcondition\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets:\x87\x01\x92A\x83\x012\x80\x01{\"condition\":{\"request\":{\"method\":\"zitadel.session.v2.SessionService/ListSessions\"}},\"targets\":[{\"target\":\"69629026806489455\"}]}\"n\n" +
	"\x14SetExecutionResponse\x12V\n" +
	"\bset_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x1f\x92A\x1cJ\x1a\"2024-12-18T07:50:47.492Z\"R\asetDate\"\xe8\x03\n" +
	"\x15ListExecutionsRequest\x12I\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2$.zitadel.filter.v2.PaginationRequestH\x00R\n" +
	"pagination\x88\x01\x01\x12|\n" +
	"\x0esorting_column\x18\x02 \x01(\x0e2%.zitadel.action.v2.ExecutionFieldNameB)\x92A&:$\"EXECUTION_FIELD_NAME_CREATION_DATE\"H\x01R\rsortingColumn\x88\x01\x01\x12B\n" +
	"\afilters\x18\x03 \x03(\v2(.zitadel.action.v2.ExecutionSearchFilterR\afilters:\x9f\x01\x92A\x9b\x012\x98\x01{\"pagination\":{\"offset\":0,\"limit\":0,\"asc\":true},\"sortingColumn\":\"EXECUTION_FIELD_NAME_ID\",\"filters\":[{\"targetFilter\":{\"targetId\":\"69629023906488334\"}}]}B\r\n" +
	"\v_paginationB\x11\n" +
	"\x0f_sorting_column\"\xa5\x01\n" +
	"\x16ListExecutionsResponse\x12E\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2%.zitadel.filter.v2.PaginationResponseR\n" +
	"pagination\x12<\n" +
	"\n" +
	"executions\x18\x02 \x03(\v2\x1c.zitadel.action.v2.ExecutionR\n" +
	"executionsR\x06result\"\x1f\n" +
	"\x1dListExecutionFunctionsRequest\">\n" +
	"\x1eListExecutionFunctionsResponse\x12\x1c\n" +
	"\tfunctions\x18\x01 \x03(\tR\tfunctions\"\x1d\n" +
	"\x1bListExecutionMethodsRequest\"8\n" +
	"\x1cListExecutionMethodsResponse\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\"\x1e\n" +
	"\x1cListExecutionServicesRequest\";\n" +
	"\x1dListExecutionServicesResponse\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices2\xe7\x15\n" +
	"\rActionService\x12\xa9\x02\n" +
	"\fCreateTarget\x12&.zitadel.action.v2.CreateTargetRequest\x1a'.zitadel.action.v2.CreateTargetResponse\"\xc7\x01\x92A\x8a\x01J$\n" +
	"\x03200\x12\x1d\n" +
	"\x1bTarget created successfullyJ3\n" +
	"\x03400\x12,\n" +
	"*The feature flag `actions` is not enabled.J-\n" +
	"\x03409\x12&\n" +
	"$The target to create already exists.\x8a\xb5\x18\x17\n" +
	"\x15\n" +
	"\x13action.target.write\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v2/actions/targets\x12\xc0\x02\n" +
	"\fUpdateTarget\x12&.zitadel.action.v2.UpdateTargetRequest\x1a'.zitadel.action.v2.UpdateTargetResponse\"\xde\x01\x92A\x9c\x01J6\n" +
	"\x03200\x12/\n" +
	"-Target successfully updated or left unchangedJ3\n" +
	"\x03400\x12,\n" +
	"*The feature flag `actions` is not enabled.J-\n" +
	"\x03404\x12&\n" +
	"$The target to update does not exist.\x8a\xb5\x18\x17\n" +
	"\x15\n" +
	"\x13action.target.write\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/actions/targets/{id}\x12\xfc\x01\n" +
	"\fDeleteTarget\x12&.zitadel.action.v2.DeleteTargetRequest\x1a'.zitadel.action.v2.DeleteTargetResponse\"\x9a\x01\x92A[J$\n" +
	"\x03200\x12\x1d\n" +
	"\x1bTarget deleted successfullyJ3\n" +
	"\x03400\x12,\n" +
	"*The feature flag `actions` is not enabled.\x8a\xb5\x18\x18\n" +
	"\x16\n" +
	"\x14action.target.delete\x82\xd3\xe4\x93\x02\x1a*\x18/v2/actions/targets/{id}\x12\xa3\x02\n" +
	"\tGetTarget\x12#.zitadel.action.v2.GetTargetRequest\x1a$.zitadel.action.v2.GetTargetResponse\"\xca\x01\x92A\x8c\x01J&\n" +
	"\x03200\x12\x1f\n" +
	"\x1dTarget retrieved successfullyJ3\n" +
	"\x03400\x12,\n" +
	"*The feature flag `actions` is not enabled.J-\n" +
	"\x03404\x12&\n" +
	"$The target to update does not exist.\x8a\xb5\x18\x16\n" +
	"\x14\n" +
	"\x12action.target.read\x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/actions/targets/{id}\x12\x89\x02\n" +
	"\vListTargets\x12%.zitadel.action.v2.ListTargetsRequest\x1a&.zitadel.action.v2.ListTargetsResponse\"\xaa\x01\x92AhJ1\n" +
	"\x03200\x12*\n" +
	"(A list of all targets matching the queryJ3\n" +
	"\x03400\x12,\n" +
	"*The feature flag `actions` is not enabled.\x8a\xb5\x18\x16\n" +
	"\x14\n" +
	"\x12action.target.read\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v2/actions/targets/search\x12\xc2\x02\n" +
	"\fSetExecution\x12&.zitadel.action.v2.SetExecutionRequest\x1a'.zitadel.action.v2.SetExecutionResponse\"\xe0\x01\x92A\x9d\x01J9\n" +
	"\x03200\x122\n" +
	"0Execution successfully updated or left unchangedJ`\n" +
	"\x03400\x12Y\n" +
	"WCondition to set execution does not exist or the feature flag `actions` is not enabled.\x8a\xb5\x18\x1a\n" +
	"\x18\n" +
	"\x16action.execution.write\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v2/actions/executions\x12\xbb\x02\n" +
	"\x0eListExecutions\x12(.zitadel.action.v2.ListExecutionsRequest\x1a).zitadel.action.v2.ListExecutionsResponse\"\xd3\x01\x92A\x8a\x01J=\n" +
	"\x03200\x126\n" +
	"4A list of all non noop executions matching the queryJI\n" +
	"\x03400\x12B\n" +
	"@Invalid list query or the feature flag `actions` is not enabled.\x8a\xb5\x18\x19\n" +
	"\x17\n" +
	"\x15action.execution.read\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v2/actions/executions/search\x12\xe9\x01\n" +
	"\x16ListExecutionFunctions\x120.zitadel.action.v2.ListExecutionFunctionsRequest\x1a1.zitadel.action.v2.ListExecutionFunctionsResponse\"j\x92A*J(\n" +
	"\x03200\x12!\n" +
	"\x1fList all functions successfully\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02\"\x12 /v2/actions/executions/functions\x12\xdf\x01\n" +
	"\x14ListExecutionMethods\x12..zitadel.action.v2.ListExecutionMethodsRequest\x1a/.zitadel.action.v2.ListExecutionMethodsResponse\"f\x92A(J&\n" +
	"\x03200\x12\x1f\n" +
	"\x1dList all methods successfully\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02 \x12\x1e/v2/actions/executions/methods\x12\xe4\x01\n" +
	"\x15ListExecutionServices\x12/.zitadel.action.v2.ListExecutionServicesRequest\x1a0.zitadel.action.v2.ListExecutionServicesResponse\"h\x92A)J'\n" +
	"\x03200\x12 \n" +
	"\x1eList all services successfully\x8a\xb5\x18\x11\n" +
	"\x0f\n" +
	"\rauthenticated\x82\xd3\xe4\x93\x02!\x12\x1f/v2/actions/executions/servicesB\xd1\a\x92A\x97\a\x12\xf5\x01\n" +
	"\x0eAction Service\x12eThis API is intended to manage custom executions (previously known as actions) in a ZITADEL instance.\".\n" +
	"\aZITADEL\x12\x13https://zitadel.com\x1a\x0ehi@zitadel.com*G\n" +
	"\n" +
	"Apache 2.0\x129https://github.com/zitadel/zitadel/blob/main/LICENSING.md2\x032.0\x1a\x0e$CUSTOM-DOMAIN\"\x01/*\x02\x02\x012\x10application/json2\x10application/grpc2\x1aapplication/grpc-web+proto:\x10application/json:\x10application/grpc:\x1aapplication/grpc-web+protoRm\n" +
	"\x03403\x12f\n" +
	"GReturned when the user does not have permission to access the resource.\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusRP\n" +
	"\x03404\x12I\n" +
	"*Returned when the resource does not exist.\x12\x1b\n" +
	"\x19\x1a\x17#/definitions/rpcStatusZ\xc2\x01\n" +
	"\xbf\x01\n" +
	"\x06OAuth2\x12\xb4\x01\b\x03(\x042!$CUSTOM-DOMAIN/oauth/v2/authorize:\x1d$CUSTOM-DOMAIN/oauth/v2/tokenBl\n" +
	"\x10\n" +
	"\x06openid\x12\x06openid\n" +
	"X\n" +
	"*urn:zitadel:iam:org:project:id:zitadel:aud\x12*urn:zitadel:iam:org:project:id:zitadel:audb@\n" +
	">\n" +
	"\x06OAuth2\x124\n" +
	"\x06openid\n" +
	"*urn:zitadel:iam:org:project:id:zitadel:audr>\n" +
	"\"Detailed information about ZITADEL\x12\x18https://zitadel.com/docsZ4github.com/zitadel/zitadel/pkg/grpc/action/v2;actionb\x06proto3"

var (
	file_zitadel_action_v2_action_service_proto_rawDescOnce sync.Once
	file_zitadel_action_v2_action_service_proto_rawDescData []byte
)

func file_zitadel_action_v2_action_service_proto_rawDescGZIP() []byte {
	file_zitadel_action_v2_action_service_proto_rawDescOnce.Do(func() {
		file_zitadel_action_v2_action_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zitadel_action_v2_action_service_proto_rawDesc), len(file_zitadel_action_v2_action_service_proto_rawDesc)))
	})
	return file_zitadel_action_v2_action_service_proto_rawDescData
}

var file_zitadel_action_v2_action_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_zitadel_action_v2_action_service_proto_goTypes = []any{
	(*CreateTargetRequest)(nil),            // 0: zitadel.action.v2.CreateTargetRequest
	(*CreateTargetResponse)(nil),           // 1: zitadel.action.v2.CreateTargetResponse
	(*UpdateTargetRequest)(nil),            // 2: zitadel.action.v2.UpdateTargetRequest
	(*UpdateTargetResponse)(nil),           // 3: zitadel.action.v2.UpdateTargetResponse
	(*DeleteTargetRequest)(nil),            // 4: zitadel.action.v2.DeleteTargetRequest
	(*DeleteTargetResponse)(nil),           // 5: zitadel.action.v2.DeleteTargetResponse
	(*GetTargetRequest)(nil),               // 6: zitadel.action.v2.GetTargetRequest
	(*GetTargetResponse)(nil),              // 7: zitadel.action.v2.GetTargetResponse
	(*ListTargetsRequest)(nil),             // 8: zitadel.action.v2.ListTargetsRequest
	(*ListTargetsResponse)(nil),            // 9: zitadel.action.v2.ListTargetsResponse
	(*SetExecutionRequest)(nil),            // 10: zitadel.action.v2.SetExecutionRequest
	(*SetExecutionResponse)(nil),           // 11: zitadel.action.v2.SetExecutionResponse
	(*ListExecutionsRequest)(nil),          // 12: zitadel.action.v2.ListExecutionsRequest
	(*ListExecutionsResponse)(nil),         // 13: zitadel.action.v2.ListExecutionsResponse
	(*ListExecutionFunctionsRequest)(nil),  // 14: zitadel.action.v2.ListExecutionFunctionsRequest
	(*ListExecutionFunctionsResponse)(nil), // 15: zitadel.action.v2.ListExecutionFunctionsResponse
	(*ListExecutionMethodsRequest)(nil),    // 16: zitadel.action.v2.ListExecutionMethodsRequest
	(*ListExecutionMethodsResponse)(nil),   // 17: zitadel.action.v2.ListExecutionMethodsResponse
	(*ListExecutionServicesRequest)(nil),   // 18: zitadel.action.v2.ListExecutionServicesRequest
	(*ListExecutionServicesResponse)(nil),  // 19: zitadel.action.v2.ListExecutionServicesResponse
	(*RESTWebhook)(nil),                    // 20: zitadel.action.v2.RESTWebhook
	(*RESTCall)(nil),                       // 21: zitadel.action.v2.RESTCall
	(*RESTAsync)(nil),                      // 22: zitadel.action.v2.RESTAsync
	(*durationpb.Duration)(nil),            // 23: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),          // 24: google.protobuf.Timestamp
	(*Target)(nil),                         // 25: zitadel.action.v2.Target
	(*v2.PaginationRequest)(nil),           // 26: zitadel.filter.v2.PaginationRequest
	(TargetFieldName)(0),                   // 27: zitadel.action.v2.TargetFieldName
	(*TargetSearchFilter)(nil),             // 28: zitadel.action.v2.TargetSearchFilter
	(*v2.PaginationResponse)(nil),          // 29: zitadel.filter.v2.PaginationResponse
	(*Condition)(nil),                      // 30: zitadel.action.v2.Condition
	(ExecutionFieldName)(0),                // 31: zitadel.action.v2.ExecutionFieldName
	(*ExecutionSearchFilter)(nil),          // 32: zitadel.action.v2.ExecutionSearchFilter
	(*Execution)(nil),                      // 33: zitadel.action.v2.Execution
}
var file_zitadel_action_v2_action_service_proto_depIdxs = []int32{
	20, // 0: zitadel.action.v2.CreateTargetRequest.rest_webhook:type_name -> zitadel.action.v2.RESTWebhook
	21, // 1: zitadel.action.v2.CreateTargetRequest.rest_call:type_name -> zitadel.action.v2.RESTCall
	22, // 2: zitadel.action.v2.CreateTargetRequest.rest_async:type_name -> zitadel.action.v2.RESTAsync
	23, // 3: zitadel.action.v2.CreateTargetRequest.timeout:type_name -> google.protobuf.Duration
	24, // 4: zitadel.action.v2.CreateTargetResponse.creation_date:type_name -> google.protobuf.Timestamp
	20, // 5: zitadel.action.v2.UpdateTargetRequest.rest_webhook:type_name -> zitadel.action.v2.RESTWebhook
	21, // 6: zitadel.action.v2.UpdateTargetRequest.rest_call:type_name -> zitadel.action.v2.RESTCall
	22, // 7: zitadel.action.v2.UpdateTargetRequest.rest_async:type_name -> zitadel.action.v2.RESTAsync
	23, // 8: zitadel.action.v2.UpdateTargetRequest.timeout:type_name -> google.protobuf.Duration
	23, // 9: zitadel.action.v2.UpdateTargetRequest.expiration_signing_key:type_name -> google.protobuf.Duration
	24, // 10: zitadel.action.v2.UpdateTargetResponse.change_date:type_name -> google.protobuf.Timestamp
	24, // 11: zitadel.action.v2.DeleteTargetResponse.deletion_date:type_name -> google.protobuf.Timestamp
	25, // 12: zitadel.action.v2.GetTargetResponse.target:type_name -> zitadel.action.v2.Target
	26, // 13: zitadel.action.v2.ListTargetsRequest.pagination:type_name -> zitadel.filter.v2.PaginationRequest
	27, // 14: zitadel.action.v2.ListTargetsRequest.sorting_column:type_name -> zitadel.action.v2.TargetFieldName
	28, // 15: zitadel.action.v2.ListTargetsRequest.filters:type_name -> zitadel.action.v2.TargetSearchFilter
	29, // 16: zitadel.action.v2.ListTargetsResponse.pagination:type_name -> zitadel.filter.v2.PaginationResponse
	25, // 17: zitadel.action.v2.ListTargetsResponse.targets:type_name -> zitadel.action.v2.Target
	30, // 18: zitadel.action.v2.SetExecutionRequest.condition:type_name -> zitadel.action.v2.Condition
	24, // 19: zitadel.action.v2.SetExecutionResponse.set_date:type_name -> google.protobuf.Timestamp
	26, // 20: zitadel.action.v2.ListExecutionsRequest.pagination:type_name -> zitadel.filter.v2.PaginationRequest
	31, // 21: zitadel.action.v2.ListExecutionsRequest.sorting_column:type_name -> zitadel.action.v2.ExecutionFieldName
	32, // 22: zitadel.action.v2.ListExecutionsRequest.filters:type_name -> zitadel.action.v2.ExecutionSearchFilter
	29, // 23: zitadel.action.v2.ListExecutionsResponse.pagination:type_name -> zitadel.filter.v2.PaginationResponse
	33, // 24: zitadel.action.v2.ListExecutionsResponse.executions:type_name -> zitadel.action.v2.Execution
	0,  // 25: zitadel.action.v2.ActionService.CreateTarget:input_type -> zitadel.action.v2.CreateTargetRequest
	2,  // 26: zitadel.action.v2.ActionService.UpdateTarget:input_type -> zitadel.action.v2.UpdateTargetRequest
	4,  // 27: zitadel.action.v2.ActionService.DeleteTarget:input_type -> zitadel.action.v2.DeleteTargetRequest
	6,  // 28: zitadel.action.v2.ActionService.GetTarget:input_type -> zitadel.action.v2.GetTargetRequest
	8,  // 29: zitadel.action.v2.ActionService.ListTargets:input_type -> zitadel.action.v2.ListTargetsRequest
	10, // 30: zitadel.action.v2.ActionService.SetExecution:input_type -> zitadel.action.v2.SetExecutionRequest
	12, // 31: zitadel.action.v2.ActionService.ListExecutions:input_type -> zitadel.action.v2.ListExecutionsRequest
	14, // 32: zitadel.action.v2.ActionService.ListExecutionFunctions:input_type -> zitadel.action.v2.ListExecutionFunctionsRequest
	16, // 33: zitadel.action.v2.ActionService.ListExecutionMethods:input_type -> zitadel.action.v2.ListExecutionMethodsRequest
	18, // 34: zitadel.action.v2.ActionService.ListExecutionServices:input_type -> zitadel.action.v2.ListExecutionServicesRequest
	1,  // 35: zitadel.action.v2.ActionService.CreateTarget:output_type -> zitadel.action.v2.CreateTargetResponse
	3,  // 36: zitadel.action.v2.ActionService.UpdateTarget:output_type -> zitadel.action.v2.UpdateTargetResponse
	5,  // 37: zitadel.action.v2.ActionService.DeleteTarget:output_type -> zitadel.action.v2.DeleteTargetResponse
	7,  // 38: zitadel.action.v2.ActionService.GetTarget:output_type -> zitadel.action.v2.GetTargetResponse
	9,  // 39: zitadel.action.v2.ActionService.ListTargets:output_type -> zitadel.action.v2.ListTargetsResponse
	11, // 40: zitadel.action.v2.ActionService.SetExecution:output_type -> zitadel.action.v2.SetExecutionResponse
	13, // 41: zitadel.action.v2.ActionService.ListExecutions:output_type -> zitadel.action.v2.ListExecutionsResponse
	15, // 42: zitadel.action.v2.ActionService.ListExecutionFunctions:output_type -> zitadel.action.v2.ListExecutionFunctionsResponse
	17, // 43: zitadel.action.v2.ActionService.ListExecutionMethods:output_type -> zitadel.action.v2.ListExecutionMethodsResponse
	19, // 44: zitadel.action.v2.ActionService.ListExecutionServices:output_type -> zitadel.action.v2.ListExecutionServicesResponse
	35, // [35:45] is the sub-list for method output_type
	25, // [25:35] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_zitadel_action_v2_action_service_proto_init() }
func file_zitadel_action_v2_action_service_proto_init() {
	if File_zitadel_action_v2_action_service_proto != nil {
		return
	}
	file_zitadel_action_v2_target_proto_init()
	file_zitadel_action_v2_execution_proto_init()
	file_zitadel_action_v2_query_proto_init()
	file_zitadel_action_v2_action_service_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateTargetRequest_RestWebhook)(nil),
		(*CreateTargetRequest_RestCall)(nil),
		(*CreateTargetRequest_RestAsync)(nil),
	}
	file_zitadel_action_v2_action_service_proto_msgTypes[2].OneofWrappers = []any{
		(*UpdateTargetRequest_RestWebhook)(nil),
		(*UpdateTargetRequest_RestCall)(nil),
		(*UpdateTargetRequest_RestAsync)(nil),
	}
	file_zitadel_action_v2_action_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_zitadel_action_v2_action_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_zitadel_action_v2_action_service_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zitadel_action_v2_action_service_proto_rawDesc), len(file_zitadel_action_v2_action_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zitadel_action_v2_action_service_proto_goTypes,
		DependencyIndexes: file_zitadel_action_v2_action_service_proto_depIdxs,
		MessageInfos:      file_zitadel_action_v2_action_service_proto_msgTypes,
	}.Build()
	File_zitadel_action_v2_action_service_proto = out.File
	file_zitadel_action_v2_action_service_proto_goTypes = nil
	file_zitadel_action_v2_action_service_proto_depIdxs = nil
}
